//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2Interface.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_RECORD_ITEM
    {
        public string UUID { get; set; }
        public string MW_RECORD_ID { get; set; }
        public string MW_ITEM_CODE { get; set; }
        public string LOCATION_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string RELEVANT_REFERENCE { get; set; }
        public string REVISION { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string STATUS_CODE { get; set; }
        public string RRM_SYN_STATUS { get; set; }
        public string LAST_MODIFIED_FORM_CODE { get; set; }
        public string FILE_ITEM_UUID { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
    }
}
