





SELECT  TABLE_NAME FROM all_tables 
WHERE OWNER='MWMS2'
ORDER BY TABLE_NAME


ALTER TABLE AA_TEST_TABLE rename TO Z_AA_TEST_TABLE;
ALTER TABLE AAA_LOG rename TO Z_AAA_LOG;

ALTER TABLE B_BCIS_ADDRESS rename TO Z_B_BCIS_ADDRESS;
ALTER TABLE B_S_USER_ACCOUNT_DELETED rename TO Z_B_S_USER_ACCOUNT_DELETED;
ALTER TABLE B_S_USER_ACCOUNT_GROUP_INFO rename TO Z_B_S_USER_ACCOUNT_GROUP_INFO;
ALTER TABLE B_S_USER_GROUP rename TO Z_B_S_USER_GROUP;
ALTER TABLE B_S_USER_GROUP_FUNCTION_INFO rename TO Z_B_S_USER_GROUP_FUNCTION_INFO;
ALTER TABLE B_S_MODULE rename TO Z_B_S_MODULE;
ALTER TABLE B_S_LOG rename TO Z_B_S_LOG;
ALTER TABLE B_S_FUNCTION rename TO Z_B_S_FUNCTION;


ALTER TABLE C_S_FUNCTION rename TO Z_C_S_FUNCTION;
ALTER TABLE C_S_MODULE rename TO Z_C_S_MODULE;

ALTER TABLE C_S_USER_ACCOUNT rename TO Z_C_S_USER_ACCOUNT;
ALTER TABLE C_S_USER_ACCOUNT_GROUP_INFO rename TO Z_C_S_USER_ACCOUNT_GROUP_INFO;

ALTER TABLE C_S_USER_GROUP rename TO Z_C_S_USER_GROUP;

ALTER TABLE C_S_USER_GROUP_FUNCTION_INFO rename TO Z_C_S_USER_GROUP_FUNCTION_INFO;


ALTER TABLE C_S_USER_GROUP_CONV_INFO DROP COLUMN USERGROUP_ID;

ALTER TABLE BCIS_ADDRESS_KEY rename TO Z_BCIS_ADDRESS_KEY;
ALTER TABLE BCIS_ADDRESS rename TO Z_BCIS_ADDRESS;

ALTER TABLE MBID_FORM_SUBMISSION_RECORD RENAME TO P_MBID_FORM_SUBMISSION_RECORD;
ALTER TABLE MW_RECORD_AL_FOLLOW_UP RENAME TO P_MW_RECORD_AL_FOLLOW_UP;
ALTER TABLE MW_RECORD_AL_FOLLOW_UP_OFFENCES RENAME TO P_MW_RECORD_AL_FOLLOW_UP_OFFENCES;
ALTER TABLE MW_RECORD_REFERRED_TO_LSS_EBD RENAME TO P_MW_RECORD_REFERRED_TO_LSS_EBD;
ALTER TABLE MW_RECORD_WL_FOLLOW_UP RENAME TO P_MW_RECORD_WL_FOLLOW_UP;



ALTER TABLE P_ACACTIONX RENAME TO Z_P_ACACTIONX;
ALTER TABLE P_ACGROUP1 RENAME TO Z_P_ACGROUP1;
ALTER TABLE P_ACRESOURCETYPEX RENAME TO Z_P_ACRESOURCETYPEX;
ALTER TABLE P_ACRESOURCEX RENAME TO Z_P_ACRESOURCEX;
ALTER TABLE P_ACROLEGROUPX RENAME TO Z_P_ACROLEGROUPX;
ALTER TABLE P_ACROLERESOURCEX RENAME TO Z_P_ACROLERESOURCEX;
ALTER TABLE P_ACROLEUSERX RENAME TO Z_P_ACROLEUSERX;
ALTER TABLE P_ACROLEX RENAME TO Z_P_ACROLEX;
ALTER TABLE P_ACTION_RECORD RENAME TO Z_P_ACTION_RECORD;
ALTER TABLE P_ACUSERDELEGATE RENAME TO Z_P_ACUSERDELEGATE;
ALTER TABLE P_ACUSERGROUPX RENAME TO Z_P_ACUSERGROUPX;
ALTER TABLE P_ACUSERMGRGROUP RENAME TO Z_P_ACUSERMGRGROUP;
ALTER TABLE P_ANNOUNCEMENT RENAME TO Z_P_ANNOUNCEMENT;
ALTER TABLE P_AP_END_PROCESS RENAME TO Z_P_AP_END_PROCESS;
ALTER TABLE P_AP_SETUP_PROCESS RENAME TO Z_P_AP_SETUP_PROCESS;
ALTER TABLE P_ATTACHHISTORY RENAME TO Z_P_ATTACHHISTORY;
ALTER TABLE P_ATTACHMENT RENAME TO Z_P_ATTACHMENT;
ALTER TABLE P_ATTACHMENTLOCK RENAME TO Z_P_ATTACHMENTLOCK;
ALTER TABLE P_CITY RENAME TO Z_P_CITY;
ALTER TABLE P_COMPANY RENAME TO Z_P_COMPANY;
ALTER TABLE P_CONN_SYSTEM RENAME TO Z_P_CONN_SYSTEM;
ALTER TABLE P_CONTENT_GROUP RENAME TO Z_P_CONTENT_GROUP;
ALTER TABLE P_CONTENT_INFO RENAME TO Z_P_CONTENT_INFO;
ALTER TABLE P_CONTENT_PRIORITY RENAME TO Z_P_CONTENT_PRIORITY;
ALTER TABLE P_CONTENT_STATUS RENAME TO Z_P_CONTENT_STATUS;
ALTER TABLE P_CONTENT_TYPE RENAME TO Z_P_CONTENT_TYPE;
ALTER TABLE P_COUNTY RENAME TO Z_P_COUNTY;
ALTER TABLE P_DASHBOARD RENAME TO Z_P_DASHBOARD;
ALTER TABLE P_DOCUMENT RENAME TO Z_P_DOCUMENT;
ALTER TABLE P_DOCUMENTTYPE RENAME TO Z_P_DOCUMENTTYPE;
ALTER TABLE P_EXCEL_DATA RENAME TO Z_P_EXCEL_DATA;
ALTER TABLE P_EXCEL_TABLE RENAME TO Z_P_EXCEL_TABLE;
ALTER TABLE P_EXCEL_TABLE_COLUMN RENAME TO Z_P_EXCEL_TABLE_COLUMN;
ALTER TABLE P_EXCEL_TEMPLATE RENAME TO Z_P_EXCEL_TEMPLATE;
ALTER TABLE P_GENKEY RENAME TO Z_P_GENKEY;
ALTER TABLE P_GRAPHCOMPMAPPING RENAME TO Z_P_GRAPHCOMPMAPPING;
ALTER TABLE P_GRAPHLINKMAPPING RENAME TO Z_P_GRAPHLINKMAPPING;
ALTER TABLE P_GROUPS RENAME TO Z_P_GROUPS;
ALTER TABLE P_GROUPTYPE RENAME TO Z_P_GROUPTYPE;
ALTER TABLE P_HOLIDAY RENAME TO Z_P_HOLIDAY;

ALTER TABLE P_IPADDRESS RENAME TO Z_P_IPADDRESS;

ALTER TABLE P_LOCATION RENAME TO Z_P_LOCATION;
ALTER TABLE P_LOCATIONTYPE RENAME TO Z_P_LOCATIONTYPE;
ALTER TABLE P_MAILINFO RENAME TO Z_P_MAILINFO;
ALTER TABLE P_MAPPER RENAME TO Z_P_MAPPER;
ALTER TABLE P_MCUSTOMERMODULE RENAME TO Z_P_MCUSTOMERMODULE;
ALTER TABLE P_MENUROLES RENAME TO Z_P_MENUROLES;
ALTER TABLE P_MINOR_WORK_INFO RENAME TO Z_P_MINOR_WORK_INFO;

ALTER TABLE P_MLEFTL1 RENAME TO Z_P_MLEFTL1;
ALTER TABLE P_MLEFTL1RLEFTL2 RENAME TO Z_P_MLEFTL1RLEFTL2;
ALTER TABLE P_MLEFTL2 RENAME TO Z_P_MLEFTL2;
ALTER TABLE P_MMODULTYPE RENAME TO Z_P_MMODULTYPE;
ALTER TABLE P_MODULENAMEDICTIONARY RENAME TO Z_P_MODULENAMEDICTIONARY;

ALTER TABLE P_MONTH RENAME TO Z_P_MONTH;
ALTER TABLE P_MSYSTEMTYPE RENAME TO Z_P_MSYSTEMTYPE;
ALTER TABLE P_MTOP RENAME TO Z_P_MTOP;
ALTER TABLE P_MTOPRLEFTL1 RENAME TO Z_P_MTOPRLEFTL1;
ALTER TABLE P_MTOPRSYSTEM RENAME TO Z_P_MTOPRSYSTEM;





ALTER TABLE P_OPERATIONSTATUS RENAME TO Z_P_OPERATIONSTATUS;
ALTER TABLE P_ORG_EDUCATION RENAME TO Z_P_ORG_EDUCATION;
ALTER TABLE P_ORG_INFO RENAME TO Z_P_ORG_INFO;
ALTER TABLE P_ORG_POSITION RENAME TO Z_P_ORG_POSITION;
ALTER TABLE P_ORG_POSITION_R RENAME TO Z_P_ORG_POSITION_R;
ALTER TABLE P_ORG_R RENAME TO Z_P_ORG_R;
ALTER TABLE P_ORG_RACE RENAME TO Z_P_ORG_RACE;
ALTER TABLE P_ORG_STATUS RENAME TO Z_P_ORG_STATUS;
ALTER TABLE P_ORG_TITLE RENAME TO Z_P_ORG_TITLE;
ALTER TABLE P_ORG_TYPE RENAME TO Z_P_ORG_TYPE;
ALTER TABLE P_ORG_USER RENAME TO Z_P_ORG_USER;
ALTER TABLE P_ORG_USERPOSITION_R RENAME TO Z_P_ORG_USERPOSITION_R;
ALTER TABLE P_ORG_USERTITLE_R RENAME TO Z_P_ORG_USERTITLE_R;
ALTER TABLE P_ORG_USER_R RENAME TO Z_P_ORG_USER_R;
ALTER TABLE P_ORG_USER_TYPE RENAME TO Z_P_ORG_USER_TYPE;
ALTER TABLE P_PROCESS RENAME TO Z_P_PROCESS;
ALTER TABLE P_PROCESSLOCK RENAME TO Z_P_PROCESSLOCK;
ALTER TABLE P_PROCESSSTATUS RENAME TO Z_P_PROCESSSTATUS;
ALTER TABLE P_PROCESSTYPES RENAME TO Z_P_PROCESSTYPES;
ALTER TABLE P_PROCESS_STATUS RENAME TO Z_P_PROCESS_STATUS;
ALTER TABLE P_PROVINCE RENAME TO Z_P_PROVINCE;
ALTER TABLE P_RELATING_PRICE RENAME TO Z_P_RELATING_PRICE;
ALTER TABLE P_REPORT RENAME TO Z_P_REPORT;
ALTER TABLE P_REPORTDATA RENAME TO Z_P_REPORTDATA;
ALTER TABLE P_RULEDATA RENAME TO Z_P_RULEDATA;
ALTER TABLE P_RULETYPE RENAME TO Z_P_RULETYPE;


ALTER TABLE P_SERVER RENAME TO Z_P_SERVER;
ALTER TABLE P_SERVERTYPE RENAME TO Z_P_SERVERTYPE;
ALTER TABLE P_SERVICELOG RENAME TO Z_P_SERVICELOG;
ALTER TABLE P_SERVICETYPE RENAME TO Z_P_SERVICETYPE;
ALTER TABLE P_STATUSTYPE RENAME TO Z_P_STATUSTYPE;
ALTER TABLE P_SYSTEMPARAMS RENAME TO Z_P_SYSTEMPARAMS;
ALTER TABLE P_SYS_LOGGER_CONFIG RENAME TO Z_P_SYS_LOGGER_CONFIG;



ALTER TABLE P_S_FUNCTION RENAME TO Z_P_S_FUNCTION;
ALTER TABLE P_S_POST RENAME TO Z_P_S_POST;
ALTER TABLE P_S_ROLE_AND_FUNCTION RENAME TO Z_P_S_ROLE_AND_FUNCTION;
ALTER TABLE P_S_USER RENAME TO Z_P_S_USER;
ALTER TABLE P_S_USER_AND_ROLE RENAME TO Z_P_S_USER_AND_ROLE;

ALTER TABLE P_S_USER RENAME TO Z_P_S_USER;
ALTER TABLE P_S_USER_AND_ROLE RENAME TO Z_P_S_USER_AND_ROLE;

ALTER TABLE P_TEST RENAME TO Z_P_TEST;
ALTER TABLE P_TEST_REPORT RENAME TO Z_P_TEST_REPORT;
ALTER TABLE P_USERDELEGATION RENAME TO Z_P_USERDELEGATION;
ALTER TABLE P_USERLOCATIONDICTIONARY RENAME TO Z_P_USERLOCATIONDICTIONARY;
ALTER TABLE P_USERS RENAME TO Z_P_USERS;
ALTER TABLE P_WFALERTION RENAME TO Z_P_WFALERTION;
ALTER TABLE P_WFAPPDEFINEDATA RENAME TO Z_P_WFAPPDEFINEDATA;
ALTER TABLE P_WFAPPLICATION RENAME TO Z_P_WFAPPLICATION;
ALTER TABLE P_WFEMAILTEMPLATE RENAME TO Z_P_WFEMAILTEMPLATE;
ALTER TABLE P_WFESCALATION RENAME TO Z_P_WFESCALATION;
ALTER TABLE P_WFEVENT RENAME TO Z_P_WFEVENT;
ALTER TABLE P_WFEVENTSEVERITY RENAME TO Z_P_WFEVENTSEVERITY;
ALTER TABLE P_WFEVENTSUBTYPE RENAME TO Z_P_WFEVENTSUBTYPE;
ALTER TABLE P_WFEVENTTYPE RENAME TO Z_P_WFEVENTTYPE;
ALTER TABLE P_WFINSTACTIVITY1 RENAME TO Z_P_WFINSTACTIVITY1;
ALTER TABLE P_WFINSTACTIVITY2 RENAME TO Z_P_WFINSTACTIVITY2;
ALTER TABLE P_WFINSTANCE RENAME TO Z_P_WFINSTANCE;
ALTER TABLE P_WFINSTANCE1 RENAME TO Z_P_WFINSTANCE1;
ALTER TABLE P_WFINSTANCE2 RENAME TO Z_P_WFINSTANCE2;
ALTER TABLE P_WFINSTANCEPROPERTIES RENAME TO Z_P_WFINSTANCEPROPERTIES;
ALTER TABLE P_WFJOB RENAME TO Z_P_WFJOB;
ALTER TABLE P_WFJOBCONTEXT RENAME TO Z_P_WFJOBCONTEXT;
ALTER TABLE P_WFJOBPROP RENAME TO Z_P_WFJOBPROP;
ALTER TABLE P_WFMEASURE RENAME TO Z_P_WFMEASURE;
ALTER TABLE P_WFNOTIFYEVENT RENAME TO Z_P_WFNOTIFYEVENT;
ALTER TABLE P_WFPRIORITY RENAME TO Z_P_WFPRIORITY;
ALTER TABLE P_WFPROPERTY RENAME TO Z_P_WFPROPERTY;
ALTER TABLE P_WFREMINDING RENAME TO Z_P_WFREMINDING;
ALTER TABLE P_WFREPORTTEMPLATE RENAME TO Z_P_WFREPORTTEMPLATE;
ALTER TABLE P_WFROUNDROBINSCHEDULE RENAME TO Z_P_WFROUNDROBINSCHEDULE;
ALTER TABLE P_WFSTATUS RENAME TO Z_P_WFSTATUS;
ALTER TABLE P_WFTASKPROPERTIES RENAME TO Z_P_WFTASKPROPERTIES;
ALTER TABLE P_WFTASKREQUEST RENAME TO Z_P_WFTASKREQUEST;
ALTER TABLE P_WFTASKTYPE RENAME TO Z_P_WFTASKTYPE;
ALTER TABLE P_WFTEMPLATE RENAME TO Z_P_WFTEMPLATE;
ALTER TABLE P_WFTEMPLATECATEGORY RENAME TO Z_P_WFTEMPLATECATEGORY;
ALTER TABLE P_WFWAITBLOCK RENAME TO Z_P_WFWAITBLOCK;

ALTER TABLE P_TASKTOUSER RENAME TO P_WF_TASKTOUSER;
ALTER TABLE S_OFFICER_ROSTER RENAME TO Z_S_OFFICER_ROSTER;




SELECT * FROM C_APPLICANT_SCORING


CREATE TABLE C_APPLICANT_SCORING
	(
	UUID                          VARCHAR2 (36) NOT NULL,
	CATEGORY                      VARCHAR2 (40),
	REGISTRATION_NO               VARCHAR2 (25),
	AS_UUID                       VARCHAR2 (36),
	REMARK                        VARCHAR2 (2000),
	CONSTRAINT C_APPLICANT_SCORING PRIMARY KEY (UUID)
	);


CREATE TABLE C_APPLICANT_SCORING_COURSE
	(
	UUID                          VARCHAR2 (36) NOT NULL,
    C_APPLICANT_SCORING_ID         VARCHAR2 (36),
   	course_CERT_NO                     VARCHAR2 (50),
   	course_ISSUE_DT                      DATE,
	course_NAME                      VARCHAR2 (100),
	course_DETAILS                      VARCHAR2 (2000),
	course_SCORE                      NUMBER (10,2),
	CONSTRAINT C_APPLICANT_SCORING_COURSE PRIMARY KEY (UUID),
	CONSTRAINT FK_ASC_01 FOREIGN KEY (C_APPLICANT_SCORING_ID) REFERENCES C_APPLICANT_SCORING (UUID)
	);

ALTER TABLE W_S_SYSTEM_VALUE ADD (REMARK VARCHAR2(200));

CREATE TABLE W_S_OFFENSE_SCORE
	(
	UUID                          VARCHAR2 (36) NOT NULL,
    OFFENSE_ID         VARCHAR2 (36),
     SCORE  NUMBER (10,2),
   	EFFECTIVE_DT                      DATE,
	CONSTRAINT C_W_S_OFFENSE_SCORE PRIMARY KEY (UUID),
	CONSTRAINT FK_SSV_01 FOREIGN KEY (OFFENSE_ID) REFERENCES W_S_SYSTEM_VALUE (UUID)
	);

ALTER TABLE W_WL_TYPE_OF_OFFENSE ADD (OFFENSE_ID VARCHAR2(36));

ALTER TABLE W_WL_TYPE_OF_OFFENSE ADD  CONSTRAINT  FK_W_S_SYSTEM_VALUE_ID 
FOREIGN KEY (OFFENSE_ID)  REFERENCES W_S_SYSTEM_VALUE(UUID);


ALTER TABLE W_WL_TYPE_OF_OFFENSE ADD (SCORE  NUMBER (10,2));

	CREATED_BY           VARCHAR2 (20),
	CREATED_DATE         DATE,
	MODIFIED_BY          VARCHAR2 (20),
	MODIFIED_DATE        DATE,


SELECT  
' ALTER TABLE ' || TABLE_NAME || ' ADD (CREATED_BY VARCHAR2(100)); ' || CHR(10) ||
' ALTER TABLE ' || TABLE_NAME || ' ADD (CREATED_DATE DATE); '  ||  CHR(10) ||
' ALTER TABLE ' || TABLE_NAME || ' ADD (MODIFIED_BY VARCHAR2(100)); ' || CHR(10) ||
' ALTER TABLE ' || TABLE_NAME || ' ADD (MODIFIED_DATE DATE); '  ||  CHR(10)   AS SQLS
FROM ALL_TABLES
WHERE OWNER = 'MWMS2' AND  TABLE_NAME NOT LIKE 'Z_%' ;
 
 
SELECT  
' ALTER TABLE ' || TABLE_NAME || ' modify (CREATED_BY VARCHAR2(100)); ' || CHR(10) ||
' ALTER TABLE ' || TABLE_NAME || ' modify (MODIFIED_BY VARCHAR2(100)); ' || CHR(10) AS SQLS
FROM ALL_TAB_COLS
WHERE OWNER = 'MWMS2' AND COLUMN_NAME IN ('CREATED_BY','MODIFIED_BY');


ALTER TABLE B_SV_RECORD ADD  CONSTRAINT  FK_BSR_SYS_POST_01
FOREIGN KEY (TO_USER_ID)  REFERENCES SYS_POST(UUID);
 
ALTER TABLE B_SV_RECORD ADD  CONSTRAINT  FK_BSR_SYS_POST_02
FOREIGN KEY (PO_USER_ID)  REFERENCES SYS_POST(UUID);

ALTER TABLE B_SV_RECORD ADD  CONSTRAINT  FK_BSR_SYS_POST_03
FOREIGN KEY (SPO_USER_ID)  REFERENCES SYS_POST(UUID);