


---------------------------------------------------
----BDIS-------------------------------------------
DROP USER ITF_BDIS CASCADE;

CREATE USER ITF_BDIS IDENTIFIED BY cD84#573;

GRANT CONNECT, RESOURCE, CREATE SESSION TO ITF_BDIS;

GRant select on MWMS2.C_APPLICANT to ITF_BDIS;
GRant select on MWMS2.C_COMP_APPLICANT_INFO to ITF_BDIS;
GRant select on MWMS2.C_COMP_APPLICANT_INFO_DETAIL to ITF_BDIS;
GRant select on MWMS2.C_COMP_APPLICANT_MW_ITEM to ITF_BDIS;
GRant select on MWMS2.C_COMP_APPLICATION to ITF_BDIS;
GRant execute  on MWMS2.C_CONCAT_BUILDING_SAFETY_ID to ITF_BDIS;
GRant execute  on MWMS2.C_CONCAT_BUILDING_SAFETY_ID_ALL to ITF_BDIS;
GRant execute  on MWMS2.C_GET_AS_LIST_HTML to ITF_BDIS;
GRant execute  on MWMS2.C_GET_AS_LIST_WITH_CHINESE_HTML to ITF_BDIS;
GRant execute  on MWMS2.C_GET_MW_COMP_AS_CLASS_TYPE to ITF_BDIS;
GRant execute  on MWMS2.C_GET_MW_COMP_CLASS_TYPE to ITF_BDIS;
GRant select on MWMS2.C_IND_APPLICATION to ITF_BDIS;
GRant select on MWMS2.C_IND_APPLICATION_MW_ITEM to ITF_BDIS;
GRant select on MWMS2.C_IND_CERTIFICATE to ITF_BDIS;
GRant select on MWMS2.C_S_CATEGORY_CODE to ITF_BDIS;
GRant select on MWMS2.C_S_SYSTEM_VALUE to ITF_BDIS;



CREATE OR REPLACE SYNONYM ITF_BDIS.APPLICANT FOR MWMS2.C_APPLICANT;
CREATE OR REPLACE SYNONYM ITF_BDIS.COMP_APPLICANT_INFO FOR MWMS2.C_COMP_APPLICANT_INFO;
CREATE OR REPLACE SYNONYM ITF_BDIS.COMP_APPLICANT_INFO_DETAIL	FOR MWMS2.C_COMP_APPLICANT_INFO_DETAIL;
CREATE OR REPLACE SYNONYM ITF_BDIS.COMP_APPLICANT_MW_ITEM	FOR MWMS2.C_COMP_APPLICANT_MW_ITEM;
CREATE OR REPLACE SYNONYM ITF_BDIS.COMP_APPLICATION	FOR MWMS2.C_COMP_APPLICATION;
CREATE OR REPLACE SYNONYM ITF_BDIS.CONCAT_BUILDING_SAFETY_ID	FOR MWMS2.C_CONCAT_BUILDING_SAFETY_ID;
CREATE OR REPLACE SYNONYM ITF_BDIS.CONCAT_BUILDING_SAFETY_ID_ALL	FOR MWMS2.C_CONCAT_BUILDING_SAFETY_ID_ALL;
CREATE OR REPLACE SYNONYM ITF_BDIS.GET_AS_LIST_HTML	FOR MWMS2.C_GET_AS_LIST_HTML;
CREATE OR REPLACE SYNONYM ITF_BDIS.GET_AS_LIST_WITH_CHINESE_HTML FOR MWMS2.C_GET_AS_LIST_WITH_CHINESE_HTML;
CREATE OR REPLACE SYNONYM ITF_BDIS.GET_MW_COMP_AS_CLASS_TYPE FOR MWMS2.C_GET_MW_COMP_AS_CLASS_TYPE;
CREATE OR REPLACE SYNONYM ITF_BDIS.GET_MW_COMP_CLASS_TYPE FOR MWMS2.C_GET_MW_COMP_CLASS_TYPE;
CREATE OR REPLACE SYNONYM ITF_BDIS.IND_APPLICATION FOR MWMS2.C_IND_APPLICATION;
CREATE OR REPLACE SYNONYM ITF_BDIS.IND_APPLICATION_MW_ITEM	FOR MWMS2.C_IND_APPLICATION_MW_ITEM;
CREATE OR REPLACE SYNONYM ITF_BDIS.IND_CERTIFICATE	FOR MWMS2.C_IND_CERTIFICATE;
CREATE OR REPLACE SYNONYM ITF_BDIS.S_CATEGORY_CODE	FOR MWMS2.C_S_CATEGORY_CODE;
CREATE OR REPLACE SYNONYM ITF_BDIS.S_SYSTEM_VALUE	FOR MWMS2.C_S_SYSTEM_VALUE;

-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------


---------------------------------------------------
CREATE OR REPLACE VIEW MWMS2.C_AS_LIST
AS
(select UUID, APP_UUID, SURNAME, GIVEN_NAME, CHINESE_NAME, ENGLISH_NAME_COMPANY, 
CHINESE_NAME_COMPANY, REGISTRATION_NUMBER, CONTACT_TEL_NO, STATUS, CATEGORY, HIGHEST_CLASS
from MWMS2.C_as_list_full_info);

ALTER TABLE C_as_list_full_info ADD (HIGHEST_CLASS VARCHAR2(50));
ALTER TABLE C_as_list_full_info ADD (CATEGORY VARCHAR2(10));


---- BD Website------------------------------------
DROP USER ITF_BD_WEBSITE CASCADE;

CREATE USER ITF_BD_WEBSITE IDENTIFIED BY asdf#1358;

GRANT CONNECT, RESOURCE, CREATE SESSION TO ITF_BD_WEBSITE;
GRant select on MWMS2.C_SEARCH_REGISTRATION_BS to ITF_BD_WEBSITE;
GRant select on MWMS2.C_SEARCH_REGISTRATION_ITEM_NO to ITF_BD_WEBSITE;
GRant select on MWMS2.C_SEARCH_REGISTRATION_QP to ITF_BD_WEBSITE;
GRant select on MWMS2.C_SEARCH_REGISTRATION_TYPE to ITF_BD_WEBSITE;
GRant select on MWMS2.C_AS_LIST to ITF_BD_WEBSITE;
GRant select on MWMS2.C_AS_CATEGORY to ITF_BD_WEBSITE;


CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.SEARCH_REGISTRATION_BS FOR MWMS2.C_SEARCH_REGISTRATION_BS;
CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.SEARCH_REGISTRATION_ITEM_NO FOR MWMS2.C_SEARCH_REGISTRATION_BS;
CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.COMP_APPLICANT_INFO_DETAIL	FOR MWMS2.C_SEARCH_REGISTRATION_ITEM_NO;
CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.COMP_APPLICANT_MW_ITEM	FOR MWMS2.C_SEARCH_REGISTRATION_TYPE;
CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.COMP_APPLICATION	FOR MWMS2.C_AS_LIST;
CREATE OR REPLACE SYNONYM ITF_BD_WEBSITE.CONCAT_BUILDING_SAFETY_ID	FOR MWMS2.C_AS_CATEGORY;

-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------


---- BD SMIS------------------------------------
DROP USER ITF_SMIS  CASCADE;

CREATE USER ITF_SMIS IDENTIFIED BY Dsdf#1S48;

GRANT CONNECT, RESOURCE, CREATE SESSION TO ITF_SMIS;
GRant select on MWMS2.P_MW_RECORD to ITF_SMIS;
GRant select on MWMS2.P_MW_REFERENCE_NO to ITF_SMIS;
GRant select on MWMS2.P_MW_APPOINTED_PROFESSIONAL to ITF_SMIS;
GRant select on MWMS2.P_MW_PERSON_CONTACT to ITF_SMIS;


CREATE OR REPLACE SYNONYM ITF_SMIS.MW_RECORD FOR MWMS2.P_MW_RECORD;
CREATE OR REPLACE SYNONYM ITF_SMIS.MW_REFERENCE_NO FOR MWMS2.P_MW_REFERENCE_NO;
CREATE OR REPLACE SYNONYM ITF_SMIS.MW_APPOINTED_PROFESSIONAL	FOR MWMS2.P_MW_APPOINTED_PROFESSIONAL;
CREATE OR REPLACE SYNONYM ITF_SMIS.MW_PERSON_CONTACT	FOR MWMS2.P_MW_PERSON_CONTACT;


-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------