drop table P_MW_RECORD_AL_FOLLOW_UP;
CREATE TABLE P_MW_RECORD_AL_FOLLOW_UP (
	UUID VARCHAR2(36)
	, MW_RECORD_ID VARCHAR2(36)
	, FOLLOW_UP_DATE DATE
	, IS_MINOR VARCHAR2(1)
	, IS_INVOLVE_MAJOR_OFFENCE VARCHAR2(1)  
	, CREATED_BY VARCHAR2(100)
	, CREATED_DATE DATE
	, MODIFIED_BY VARCHAR2(100)
	, MODIFIED_DATE DATE
	, constraint P_MW_RECORD_AL_FOLLOW_UP_PK primary key (uuid)
);

drop table P_MW_RECORD_AL_FOLLOW_UP_OFFENCES;
CREATE TABLE P_MW_RECORD_AL_FOLLOW_UP_OFFENCES (
  UUID VARCHAR2(36)
  , MASTER_ID VARCHAR2(36)
  , SV_QUESTION_ID VARCHAR2(36)
  , IS_RECTIFIED VARCHAR2(1)
  , REMARKS VARCHAR2(500)
  , CREATED_BY VARCHAR2(100)
  , CREATED_DATE DATE
  , MODIFIED_BY VARCHAR2(100)
  , MODIFIED_DATE DATE
  , constraint P_MW_RECORD_AL_FOLLOW_UP_OFFENCES_PK primary key (uuid)
  , constraint P_MW_RECORD_AL_FOLLOW_UP_MASTER_ID_FK foreign key (MASTER_ID) references P_MW_RECORD_AL_FOLLOW_UP(uuid) 
  , constraint P_MW_RECORD_AL_FOLLOW_UP_OFFENCES_SV_QUESTION_ID_FK foreign key (SV_QUESTION_ID) references P_S_SYSTEM_VALUE(uuid)  
);

  drop table P_MW_RECORD_WL_FOLLOW_UP;
  CREATE TABLE P_MW_RECORD_WL_FOLLOW_UP (
    "UUID" VARCHAR2(36 BYTE), 
	"MW_RECORD_ID" VARCHAR2(36 BYTE), 
	"REFERRAL_LSS_DATE" DATE, 
	"REFERRAL_EBD_DATE" DATE, 
	"DISCOVERY_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
    , constraint P_MW_RECORD_WL_FOLLOW_UP_PK primary key (uuid)
    , constraint P_MW_RECORD_WL_FOLLOW_UP_MW_RECORD_ID_FK foreign key (MW_RECORD_ID) references P_MW_RECORD(uuid)  
   );


  drop table P_MW_RECORD_REFERRED_TO_LSS_EBD;
  CREATE TABLE "P_MW_RECORD_REFERRED_TO_LSS_EBD" 
   (	"UUID" VARCHAR2(36 BYTE), 
	"MW_RECORD_ID" VARCHAR2(36 BYTE),  
	"DROPPED_WITHDRAWN_DATE" DATE, 
	"SUMMON_DATE" DATE, 
	"HEARING_DATE" DATE, 
	"TOTAL_FINE" VARCHAR2(10 BYTE), 
	"REMARKS" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(50 BYTE),
    "CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
    , constraint P_MW_RECORD_REFERRED_TO_LSS_EBD_PK primary key (uuid)
    , constraint P_MW_RECORD_REFERRED_TO_LSS_EBD_MW_RECORD_ID_FK foreign key (MW_RECORD_ID) references P_MW_RECORD(uuid)      
   )