create or replace PROCEDURE       Housing_Authority  AS

BEGIN

EXECUTE IMMEDIATE 'DELETE HA_DATA.ADDRESS cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.S_SYSTEM_VALUE cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.APPLICANT cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.BUILDING_SAFETY_INFO cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.S_CATEGORY_CODE cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.COMP_APPLICATION cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.COMP_APPLICANT_INFO cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.COMP_APPLICANT_MW_ITEM cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.IND_APPLICATION cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.IND_APPLICATION_MW_ITEM cascade';
EXECUTE IMMEDIATE 'DELETE HA_DATA.IND_CERTIFICATE cascade';


INSERT INTO HA_DATA.ADDRESS (UUID, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_LINE5, CREATED_BY, 
CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
SELECT UUID, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ADDRESS_LINE5,
 CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
FROM MWMS2.C_ADDRESS ;


INSERT INTO HA_DATA.S_SYSTEM_VALUE (UUID, REGISTRATION_TYPE, SYSTEM_TYPE_ID, CODE, PARENT_ID, ENGLISH_DESCRIPTION, CHINESE_DESCRIPTION, IS_ACTIVE, ORDERING, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
SELECT UUID, REGISTRATION_TYPE, SYSTEM_TYPE_ID, CODE, PARENT_ID, ENGLISH_DESCRIPTION, CHINESE_DESCRIPTION, IS_ACTIVE, ORDERING, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
FROM MWMS2.C_S_SYSTEM_VALUE ;


INSERT INTO HA_DATA.APPLICANT (UUID, HKID, PASSPORT_NO, SURNAME, GIVEN_NAME_ON_ID, GENDER, CHINESE_NAME, IS_POOLING, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, TITLE_ID)
SELECT UUID, HKID, PASSPORT_NO, SURNAME, GIVEN_NAME_ON_ID, GENDER, CHINESE_NAME, IS_POOLING, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, TITLE_ID
FROM MWMS2.C_APPLICANT;


INSERT INTO HA_DATA.BUILDING_SAFETY_INFO (UUID, REGISTRATION_TYPE, MASTER_ID, BUILDING_SAFETY_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
SELECT UUID, REGISTRATION_TYPE, MASTER_ID, BUILDING_SAFETY_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
FROM MWMS2.C_BUILDING_SAFETY_INFO;



INSERT INTO HA_DATA.S_CATEGORY_CODE (UUID, CODE, ENGLISH_DESCRIPTION, CHINESE_DESCRIPTION, CATEGORY_GROUP_ID, REGISTRATION_TYPE, ENGLISH_SUB_TITLE_DESCRIPTION, CHINESE_SUB_TITLE_DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, ACTIVE)
SELECT UUID, CODE, ENGLISH_DESCRIPTION, CHINESE_DESCRIPTION, CATEGORY_GROUP_ID, REGISTRATION_TYPE, ENGLISH_SUB_TITLE_DESCRIPTION, CHINESE_SUB_TITLE_DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, ACTIVE
FROM MWMS2.C_S_CATEGORY_CODE;


INSERT INTO HA_DATA.COMP_APPLICATION (UUID, REGISTRATION_TYPE, FILE_REFERENCE_NO, CERTIFICATION_NO, BR_NO, BRANCH_NO, OLD_FILE_REFERENCE, CATEGORY_ID, ENGLISH_COMPANY_NAME, CHINESE_COMPANY_NAME, APPLICANT_NAME, COMPANY_TYPE_ID, ENGLISH_CARE_OF, CHINESE_CARE_OF, ENGLISH_ADDRESS_ID, CHINESE_ADDRESS_ID, PERIOD_OF_VALIDITY_ID, APPLICATION_FORM_ID, APPLICATION_DATE, GAZETTE_DATE, REGISTRATION_DATE, APPROVAL_DATE, EXPIRY_DATE, RESTORE_DATE, RESTORATION_APPLICATION_DATE, RETENTION_DATE, RETENTION_APPLICATION_DATE, SUSPENSION_DATE, REMOVAL_DATE, REMARKS, DOCUMENT_MAIL_DATE, MISS_DOCUMENT_TYPE, VETTING_DATE, TELEPHONE_NO1, TELEPHONE_NO2, TELEPHONE_NO3, FAX_NO1, FAX_NO2, EMAIL_ADDRESS, PROSECUTION_DISCIPLINARY_REC, IS_PUBLIC_INFO, PRACTICE_NOTES_ID, ENGLISH_BS_ADDRESS_ID, CHINESE_BS_ADDRESS_ID, BS_TELEPHONE_NO1, BS_FAX_NO1, ENGLISH_BS_CARE_OF, CHINESE_BS_CARE_OF, APPLICATION_STATUS_ID, EXTEND_DATE, REGION_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CORRESPONDENCE_LANG_ID, BS_EMAIL_ADDRESS, BS_REGION_CODE_ID, WILLINGNESS_QP, WILLINGNESS_QP_DATE, DUE_DATE, DUE_DATE_CLASS, FIRST_APPLICATION_DATE, INTERESTED_FSS, INTERESTED_FSS_DATE)
SELECT UUID, REGISTRATION_TYPE, FILE_REFERENCE_NO, CERTIFICATION_NO, BR_NO, BRANCH_NO, OLD_FILE_REFERENCE, CATEGORY_ID, ENGLISH_COMPANY_NAME, CHINESE_COMPANY_NAME, APPLICANT_NAME, COMPANY_TYPE_ID, ENGLISH_CARE_OF, CHINESE_CARE_OF, ENGLISH_ADDRESS_ID, CHINESE_ADDRESS_ID, PERIOD_OF_VALIDITY_ID, APPLICATION_FORM_ID, APPLICATION_DATE, GAZETTE_DATE, REGISTRATION_DATE, APPROVAL_DATE, EXPIRY_DATE, RESTORE_DATE, RESTORATION_APPLICATION_DATE, RETENTION_DATE, RETENTION_APPLICATION_DATE, SUSPENSION_DATE, REMOVAL_DATE, REMARKS, DOCUMENT_MAIL_DATE, MISS_DOCUMENT_TYPE, VETTING_DATE, TELEPHONE_NO1, TELEPHONE_NO2, TELEPHONE_NO3, FAX_NO1, FAX_NO2, EMAIL_ADDRESS, PROSECUTION_DISCIPLINARY_REC, IS_PUBLIC_INFO, PRACTICE_NOTES_ID, ENGLISH_BS_ADDRESS_ID, CHINESE_BS_ADDRESS_ID, BS_TELEPHONE_NO1, BS_FAX_NO1, ENGLISH_BS_CARE_OF, CHINESE_BS_CARE_OF, APPLICATION_STATUS_ID, EXTEND_DATE, REGION_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CORRESPONDENCE_LANG_ID, BS_EMAIL_ADDRESS, BS_REGION_CODE_ID, WILLINGNESS_QP, WILLINGNESS_QP_DATE, DUE_DATE, DUE_DATE_CLASS, FIRST_APPLICATION_DATE, INTERESTED_FSS, INTERESTED_FSS_DATE
FROM MWMS2.C_COMP_APPLICATION;



INSERT INTO HA_DATA.COMP_APPLICANT_INFO (UUID, MASTER_ID, APPLICANT_ID, APPLICANT_ROLE_ID, REMARK, ACCEPT_DATE, REMOVAL_DATE, CANDIDATE_NUMBER, LAST_INTERVIEW_NUMBER, LAST_ASSESSMENT_NUMBER, VETTING_STATUS, FILE_PATH_RESTRICTED, APPLICANT_STATUS_ID, FILE_PATH_NONRESTRICTED, INTERVIEW_REFUSAL_DATE, INTERVIEW_WITHDRAWN_DATE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, SUPPORTED_BY_ID, CORRESPONDENCE_LANG_ID, CARD_EXPIRY_DATE, CARD_ISSUE_DATE, CARD_RETURN_DATE, CARD_SERIAL_NO, OFFICE_TEL, MOBILE_TEL, RES_TEL, EMAIL1, EMAIL2, RES_ADDRESS_E1, RES_ADDRESS_E2, RES_ADDRESS_E3, RES_ADDRESS_E4, RES_ADDRESS_E5, RES_ADDRESS_C1, RES_ADDRESS_C2, RES_ADDRESS_C3, RES_ADDRESS_C4, RES_ADDRESS_C5)
SELECT UUID, MASTER_ID, APPLICANT_ID, APPLICANT_ROLE_ID, REMARK, ACCEPT_DATE, REMOVAL_DATE, CANDIDATE_NUMBER, LAST_INTERVIEW_NUMBER, LAST_ASSESSMENT_NUMBER, VETTING_STATUS, FILE_PATH_RESTRICTED, APPLICANT_STATUS_ID, FILE_PATH_NONRESTRICTED, INTERVIEW_REFUSAL_DATE, INTERVIEW_WITHDRAWN_DATE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, SUPPORTED_BY_ID, CORRESPONDENCE_LANG_ID, CARD_EXPIRY_DATE, CARD_ISSUE_DATE, CARD_RETURN_DATE, CARD_SERIAL_NO, OFFICE_TEL, MOBILE_TEL, RES_TEL, EMAIL1, EMAIL2, RES_ADDRESS_E1, RES_ADDRESS_E2, RES_ADDRESS_E3, RES_ADDRESS_E4, RES_ADDRESS_E5, RES_ADDRESS_C1, RES_ADDRESS_C2, RES_ADDRESS_C3, RES_ADDRESS_C4, RES_ADDRESS_C5
FROM MWMS2.C_COMP_APPLICANT_INFO;


INSERT INTO HA_DATA.COMP_APPLICANT_MW_ITEM (UUID, COMPANY_APPLICANTS_ID, ITEM_TYPE_ID, ITEM_CLASS_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
SELECT UUID, COMPANY_APPLICANTS_ID, ITEM_TYPE_ID, ITEM_CLASS_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
FROM MWMS2.C_COMP_APPLICANT_MW_ITEM;


INSERT INTO HA_DATA.IND_APPLICATION (UUID, REGISTRATION_TYPE, FILE_REFERENCE_NO, APPLICANT_ID, POST_TO, EMERGENCY_NO1, EMERGENCY_NO2, EMERGENCY_NO3, TELEPHONE_NO1, TELEPHONE_NO2, TELEPHONE_NO3, FAX_NO1, FAX_NO2, PRACTICE_NOTES_ID, EMAIL, ENGLISH_HOME_ADDRESS_ID, CHINESE_HOME_ADDRESS_ID, ENGLISH_OFFICE_ADDRESS_ID, CHINESE_OFFICE_ADDRESS_ID, ENGLISH_BS_ADDRESS_ID, CHINESE_BS_ADDRESS_ID, BS_TELEPHONE_NO1, BS_FAX_NO1, REMARKS, ENGLISH_CARE_OF, CHINESE_CARE_OF, ENGLISH_BS_CARE_OF, CHINESE_BS_CARE_OF, QUALIFICATION, REGION_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CORRESPONDENCE_LANG_ID, BS_EMAIL, BS_REGION_CODE_ID, WILLINGNESS_QP, WILLINGNESS_QP_DATE, INTERESTED_FSS, INTERESTED_FSS_DATE, MBIS_RI)
SELECT UUID, REGISTRATION_TYPE, FILE_REFERENCE_NO, APPLICANT_ID, POST_TO, EMERGENCY_NO1, EMERGENCY_NO2, EMERGENCY_NO3, TELEPHONE_NO1, TELEPHONE_NO2, TELEPHONE_NO3, FAX_NO1, FAX_NO2, PRACTICE_NOTES_ID, EMAIL, ENGLISH_HOME_ADDRESS_ID, CHINESE_HOME_ADDRESS_ID, ENGLISH_OFFICE_ADDRESS_ID, CHINESE_OFFICE_ADDRESS_ID, ENGLISH_BS_ADDRESS_ID, CHINESE_BS_ADDRESS_ID, BS_TELEPHONE_NO1, BS_FAX_NO1, REMARKS, ENGLISH_CARE_OF, CHINESE_CARE_OF, ENGLISH_BS_CARE_OF, CHINESE_BS_CARE_OF, QUALIFICATION, REGION_CODE_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CORRESPONDENCE_LANG_ID, BS_EMAIL, BS_REGION_CODE_ID, WILLINGNESS_QP, WILLINGNESS_QP_DATE, INTERESTED_FSS, INTERESTED_FSS_DATE, MBIS_RI
FROM MWMS2.C_IND_APPLICATION;


INSERT INTO HA_DATA.IND_APPLICATION_MW_ITEM (UUID, MASTER_ID, ITEM_TYPE_ID, ITEM_CLASS_ID, ITEM_DETAILS_ID, SUPPORTED_BY_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
SELECT UUID, MASTER_ID,	 ITEM_TYPE_ID, ITEM_CLASS_ID, ITEM_DETAILS_ID, SUPPORTED_BY_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
FROM MWMS2.C_IND_APPLICATION_MW_ITEM;

INSERT INTO HA_DATA.IND_CERTIFICATE (UUID, MASTER_ID, CATEGORY_ID, CERTIFICATION_NO, PERIOD_OF_VALIDITY_ID, EXTENDED_DATE, GAZETTE_DATE, APPROVAL_DATE, REGISTRATION_DATE, EXPIRY_DATE, SUSPENSION_DATE, REMOVAL_DATE, REMARKS, RESTORE_DATE, RESTORATION_APPLICATION_DATE, RETENTION_DATE, RETENTION_APPLICATION_DATE, APPLICATION_DATE, APPLICATION_FORM_ID, CANDIDATE_NUMBER, APPLICATION_STATUS_ID, DOCUMENT_MAIL_DATE, MISS_DOCUMENT_TYPE, VETTING_DATE, USE_OLD_CATEGORY_CODE, FILE_PATH_NONRESTRICTED, FILE_PATH_RESTRICTED, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CARD_EXPIRY_DATE, CARD_ISSUE_DATE, CARD_RETURN_DATE, CARD_SERIAL_NO, CARD_APP_DATE, QP_ADDRESS_E1, QP_ADDRESS_E2, QP_ADDRESS_E3, QP_ADDRESS_E4, QP_ADDRESS_E5, QP_ADDRESS_C1, QP_ADDRESS_C2, QP_ADDRESS_C3, QP_ADDRESS_C4, QP_ADDRESS_C5)
SELECT UUID, MASTER_ID, CATEGORY_ID, CERTIFICATION_NO, PERIOD_OF_VALIDITY_ID, EXTENDED_DATE, GAZETTE_DATE, APPROVAL_DATE, REGISTRATION_DATE, EXPIRY_DATE, SUSPENSION_DATE, REMOVAL_DATE, REMARKS, RESTORE_DATE, RESTORATION_APPLICATION_DATE, RETENTION_DATE, RETENTION_APPLICATION_DATE, APPLICATION_DATE, APPLICATION_FORM_ID, CANDIDATE_NUMBER, APPLICATION_STATUS_ID, DOCUMENT_MAIL_DATE, MISS_DOCUMENT_TYPE, VETTING_DATE, USE_OLD_CATEGORY_CODE, FILE_PATH_NONRESTRICTED, FILE_PATH_RESTRICTED, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, CARD_EXPIRY_DATE, CARD_ISSUE_DATE, CARD_RETURN_DATE, CARD_SERIAL_NO, CARD_APP_DATE, QP_ADDRESS_E1, QP_ADDRESS_E2, QP_ADDRESS_E3, QP_ADDRESS_E4, QP_ADDRESS_E5, QP_ADDRESS_C1, QP_ADDRESS_C2, QP_ADDRESS_C3, QP_ADDRESS_C4, QP_ADDRESS_C5
FROM MWMS2.C_IND_CERTIFICATE;


COMMIT;

END;















create public database link 
Bravodblink connect to PEM_DATA 
identified by "123456" Using 
'(DESCRIPTION=(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.88.200)(PORT = 1521)))(CONNECT_DATA=(SERVICE_NAME = ORCL.bd.net)))';




create public database link 
BCISdblink connect to BCISPROD_P7 
identified by "123456" Using 
'(DESCRIPTION=(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.5.113.143)(PORT = 1521)))(CONNECT_DATA=(SID = BCIS)))';



alter session set "_ORACLE_SCRIPT"= true;
CREATE USER HA_DATA IDENTIFIED BY 123456;
create directory dmp_dir as  'C:\HA\'
  grant read, write on directory dmp_dir to HA_DATA
  

Grant CONNECT TO FPIS_DATA;
Grant RESOURCE TO FPIS_DATA;



alter session set "_ORACLE_SCRIPT"= true;
CREATE USER HA_DATA IDENTIFIED BY 123456;


Grant CONNECT TO HA_DATA;
Grant RESOURCE TO HA_DATA;
alter user ha_data quota unlimited on USERS
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.S_SYSTEM_VALUE TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.APPLICANT TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.BUILDING_SAFETY_INFO TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.S_CATEGORY_CODE TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.COMP_APPLICATION TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.COMP_APPLICANT_INFO TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.COMP_APPLICANT_MW_ITEM TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.IND_APPLICATION TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.IND_APPLICATION_MW_ITEM TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.IND_CERTIFICATE TO MWMS2;
GRANT SELECT, INSERT,UPDATE , DELETE ON HA_DATA.ADDRESS TO MWMS2;
CREATE TABLE ADDRESS
	(
	UUID          VARCHAR2 (36) NOT NULL,
	ADDRESS_LINE1 NVARCHAR2 (40),
	ADDRESS_LINE2 NVARCHAR2 (40),
	ADDRESS_LINE3 NVARCHAR2 (40),
	ADDRESS_LINE4 NVARCHAR2 (40),
	ADDRESS_LINE5 NVARCHAR2 (40),
	CREATED_BY    VARCHAR2 (20) NOT NULL,
	CREATED_DATE  DATE NOT NULL,
	MODIFIED_BY   VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	CONSTRAINT PK_ADDRESS PRIMARY KEY (UUID)
	)


CREATE TABLE S_SYSTEM_TYPE
	(
	UUID          VARCHAR2 (36) NOT NULL,
	TYPE          VARCHAR2 (30) NOT NULL,
	CREATED_BY    VARCHAR2 (20) NOT NULL,
	CREATED_DATE  DATE NOT NULL,
	MODIFIED_BY   VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	CONSTRAINT PK_SYSTEM_TYPE PRIMARY KEY (UUID)
	)

CREATE TABLE S_SYSTEM_VALUE
	(
	UUID                VARCHAR2 (36) NOT NULL,
	REGISTRATION_TYPE   VARCHAR2 (15) NOT NULL,
	SYSTEM_TYPE_ID      VARCHAR2 (36) NOT NULL,
	CODE                VARCHAR2 (50) NOT NULL,
	PARENT_ID           VARCHAR2 (36),
	ENGLISH_DESCRIPTION VARCHAR2 (2000),
	CHINESE_DESCRIPTION NVARCHAR2 (500),
	IS_ACTIVE           VARCHAR2 (1),
	ORDERING            NUMBER (38),
	CREATED_BY          VARCHAR2 (20) NOT NULL,
	CREATED_DATE        DATE NOT NULL,
	MODIFIED_BY         VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE       DATE NOT NULL,
	CONSTRAINT PK_SYSTEM_VALUE PRIMARY KEY (UUID),
	CONSTRAINT SYSTEM_VALUE_SYSTEM_VALUE_FK FOREIGN KEY (PARENT_ID) REFERENCES S_SYSTEM_VALUE (UUID) DISABLE NOVALIDATE,
	CONSTRAINT S_SYSTEM_TYPE_FK FOREIGN KEY (SYSTEM_TYPE_ID) REFERENCES S_SYSTEM_TYPE (UUID) DISABLE NOVALIDATE
	)

  CREATE TABLE APPLICANT
	(
	UUID             VARCHAR2 (36) NOT NULL,
	HKID             VARCHAR2 (300),
	PASSPORT_NO      VARCHAR2 (300),
	SURNAME          VARCHAR2 (40),
	GIVEN_NAME_ON_ID VARCHAR2 (40),
	GENDER           VARCHAR2 (1),
	CHINESE_NAME     NVARCHAR2 (6),
	IS_POOLING       VARCHAR2 (1),
	CREATED_BY       VARCHAR2 (20) NOT NULL,
	CREATED_DATE     DATE NOT NULL,
	MODIFIED_BY      VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE    DATE NOT NULL,
	TITLE_ID         VARCHAR2 (36),
	CONSTRAINT PK_APPLICANT PRIMARY KEY (UUID),
	CONSTRAINT APPLICANT_SYSTEM_VALUE_FK FOREIGN KEY (TITLE_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  

  
CREATE TABLE BUILDING_SAFETY_INFO
	(
	UUID               VARCHAR2 (36) NOT NULL,
	REGISTRATION_TYPE  VARCHAR2 (15) NOT NULL,
	MASTER_ID          VARCHAR2 (36),
	BUILDING_SAFETY_ID VARCHAR2 (36),
	CREATED_BY         VARCHAR2 (20) NOT NULL,
	CREATED_DATE       DATE NOT NULL,
	MODIFIED_BY        VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE      DATE NOT NULL,
	CONSTRAINT PK_BUILDING_SAFETY_INFO PRIMARY KEY (UUID),
	CONSTRAINT BSI_SYSTEM_VALUE_FK FOREIGN KEY (BUILDING_SAFETY_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  
  
  CREATE TABLE S_CATEGORY_CODE
	(
	UUID                          VARCHAR2 (36) NOT NULL,
	CODE                          VARCHAR2 (10) NOT NULL,
	ENGLISH_DESCRIPTION           VARCHAR2 (100) NOT NULL,
	CHINESE_DESCRIPTION           NVARCHAR2 (100),
	CATEGORY_GROUP_ID             VARCHAR2 (36) NOT NULL,
	REGISTRATION_TYPE             VARCHAR2 (15) NOT NULL,
	ENGLISH_SUB_TITLE_DESCRIPTION VARCHAR2 (50),
	CHINESE_SUB_TITLE_DESCRIPTION NVARCHAR2 (50),
	CREATED_BY                    VARCHAR2 (20) NOT NULL,
	CREATED_DATE                  DATE NOT NULL,
	MODIFIED_BY                   VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE                 DATE NOT NULL,
	ACTIVE                        VARCHAR2 (1),
	CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY (UUID),
	CONSTRAINT CATEGORY_C_SYSTEM_VALUE_FK FOREIGN KEY (CATEGORY_GROUP_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  
  
  
  
  
  
  
  
  
  
  
  
  CREATE TABLE COMP_APPLICATION
	(
	UUID                         VARCHAR2 (36) NOT NULL,
	REGISTRATION_TYPE            VARCHAR2 (15) NOT NULL,
	FILE_REFERENCE_NO            VARCHAR2 (20) NOT NULL,
	CERTIFICATION_NO             VARCHAR2 (20),
	BR_NO                        VARCHAR2 (8) NOT NULL,
	BRANCH_NO                    VARCHAR2 (3),
	OLD_FILE_REFERENCE           VARCHAR2 (20),
	CATEGORY_ID                  VARCHAR2 (36),
	ENGLISH_COMPANY_NAME         VARCHAR2 (150) NOT NULL,
	CHINESE_COMPANY_NAME         NVARCHAR2 (50),
	APPLICANT_NAME               VARCHAR2 (60),
	COMPANY_TYPE_ID              VARCHAR2 (36),
	ENGLISH_CARE_OF              VARCHAR2 (150),
	CHINESE_CARE_OF              NVARCHAR2 (50),
	ENGLISH_ADDRESS_ID           VARCHAR2 (36),
	CHINESE_ADDRESS_ID           VARCHAR2 (36),
	PERIOD_OF_VALIDITY_ID        VARCHAR2 (36),
	APPLICATION_FORM_ID          VARCHAR2 (36),
	APPLICATION_DATE             DATE,
	GAZETTE_DATE                 DATE,
	REGISTRATION_DATE            DATE,
	APPROVAL_DATE                DATE,
	EXPIRY_DATE                  DATE,
	RESTORE_DATE                 DATE,
	RESTORATION_APPLICATION_DATE DATE,
	RETENTION_DATE               DATE,
	RETENTION_APPLICATION_DATE   DATE,
	SUSPENSION_DATE              DATE,
	REMOVAL_DATE                 DATE,
	REMARKS                      NVARCHAR2 (1000),
	DOCUMENT_MAIL_DATE           DATE,
	MISS_DOCUMENT_TYPE           VARCHAR2 (10),
	VETTING_DATE                 DATE,
	TELEPHONE_NO1                VARCHAR2 (22),
	TELEPHONE_NO2                VARCHAR2 (22),
	TELEPHONE_NO3                VARCHAR2 (22),
	FAX_NO1                      VARCHAR2 (20),
	FAX_NO2                      VARCHAR2 (20),
	EMAIL_ADDRESS                VARCHAR2 (80),
	PROSECUTION_DISCIPLINARY_REC NVARCHAR2 (1000),
	IS_PUBLIC_INFO               VARCHAR2 (1),
	PRACTICE_NOTES_ID            VARCHAR2 (36),
	ENGLISH_BS_ADDRESS_ID        VARCHAR2 (36),
	CHINESE_BS_ADDRESS_ID        VARCHAR2 (36),
	BS_TELEPHONE_NO1             VARCHAR2 (22),
	BS_FAX_NO1                   VARCHAR2 (20),
	ENGLISH_BS_CARE_OF           VARCHAR2 (150),
	CHINESE_BS_CARE_OF           NVARCHAR2 (50),
	APPLICATION_STATUS_ID        VARCHAR2 (36),
	EXTEND_DATE                  DATE,
	REGION_CODE_ID               VARCHAR2 (36),
	CREATED_BY                   VARCHAR2 (20) NOT NULL,
	CREATED_DATE                 DATE NOT NULL,
	MODIFIED_BY                  VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE                DATE NOT NULL,
	CORRESPONDENCE_LANG_ID       VARCHAR2 (36),
	BS_EMAIL_ADDRESS             VARCHAR2 (80),
	BS_REGION_CODE_ID            VARCHAR2 (36),
	WILLINGNESS_QP               VARCHAR2 (1),
	WILLINGNESS_QP_DATE          DATE,
	DUE_DATE                     DATE,
	DUE_DATE_CLASS               VARCHAR2 (36),
	FIRST_APPLICATION_DATE       DATE,
	INTERESTED_FSS               VARCHAR2 (1),
	INTERESTED_FSS_DATE          DATE,
	CONSTRAINT PK_COMP_APPLICATION PRIMARY KEY (UUID),
	CONSTRAINT COMP_APP_CATEGORY_CODE_FK FOREIGN KEY (CATEGORY_ID) REFERENCES S_CATEGORY_CODE (UUID),
	CONSTRAINT COMP_APP_CHIN_ADDRESS_FK FOREIGN KEY (CHINESE_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT COMP_APP_CHIN_BS_ADDRESS_FK1 FOREIGN KEY (CHINESE_BS_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT COMP_APP_ENG_ADDRESS_FK FOREIGN KEY (ENGLISH_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT COMP_APP_ENG_BS_ADDRESS_FK FOREIGN KEY (ENGLISH_BS_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT COMP_APP_SVBS_FK FOREIGN KEY (BS_REGION_CODE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK FOREIGN KEY (COMPANY_TYPE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK1 FOREIGN KEY (PERIOD_OF_VALIDITY_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK2 FOREIGN KEY (APPLICATION_FORM_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK3 FOREIGN KEY (PRACTICE_NOTES_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK4 FOREIGN KEY (APPLICATION_STATUS_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT COMP_APP_SYSTEM_VALUE_FK5 FOREIGN KEY (REGION_CODE_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  
  
  
  
  
  
CREATE TABLE COMP_APPLICANT_INFO
	(
	UUID                     VARCHAR2 (36) NOT NULL,
	MASTER_ID                VARCHAR2 (36),
	APPLICANT_ID             VARCHAR2 (36),
	APPLICANT_ROLE_ID        VARCHAR2 (36),
	REMARK                   VARCHAR2 (2000),
	ACCEPT_DATE              DATE,
	REMOVAL_DATE             DATE,
	CANDIDATE_NUMBER         NUMBER (8),
	LAST_INTERVIEW_NUMBER    VARCHAR2 (30),
	LAST_ASSESSMENT_NUMBER   VARCHAR2 (30),
	VETTING_STATUS           VARCHAR2 (1),
	FILE_PATH_RESTRICTED     VARCHAR2 (100),
	APPLICANT_STATUS_ID      VARCHAR2 (36),
	FILE_PATH_NONRESTRICTED  VARCHAR2 (100),
	INTERVIEW_REFUSAL_DATE   DATE,
	INTERVIEW_WITHDRAWN_DATE DATE,
	CREATED_BY               VARCHAR2 (20) NOT NULL,
	CREATED_DATE             DATE NOT NULL,
	MODIFIED_BY              VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE            DATE NOT NULL,
	SUPPORTED_BY_ID          VARCHAR2 (36),
	CORRESPONDENCE_LANG_ID   VARCHAR2 (36),
	CARD_EXPIRY_DATE         DATE,
	CARD_ISSUE_DATE          DATE,
	CARD_RETURN_DATE         DATE,
	CARD_SERIAL_NO           VARCHAR2 (20),
	OFFICE_TEL               VARCHAR2 (22),
	MOBILE_TEL               VARCHAR2 (22),
	RES_TEL                  VARCHAR2 (22),
	EMAIL1                   VARCHAR2 (80),
	EMAIL2                   VARCHAR2 (80),
	RES_ADDRESS_E1           NVARCHAR2 (40),
	RES_ADDRESS_E2           NVARCHAR2 (40),
	RES_ADDRESS_E3           NVARCHAR2 (40),
	RES_ADDRESS_E4           NVARCHAR2 (40),
	RES_ADDRESS_E5           NVARCHAR2 (40),
	RES_ADDRESS_C1           NVARCHAR2 (40),
	RES_ADDRESS_C2           NVARCHAR2 (40),
	RES_ADDRESS_C3           NVARCHAR2 (40),
	RES_ADDRESS_C4           NVARCHAR2 (40),
	RES_ADDRESS_C5           NVARCHAR2 (40),
	CONSTRAINT PK_COMP_APPLICANT_INFO PRIMARY KEY (UUID),
	CONSTRAINT CAI_APPLICANT_FK FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT (UUID),
	CONSTRAINT CAI_COMP_APPLICANT_INFO_FK FOREIGN KEY (SUPPORTED_BY_ID) REFERENCES COMP_APPLICANT_INFO (UUID),
	CONSTRAINT CAI_COMP_APPLICATION_FK FOREIGN KEY (MASTER_ID) REFERENCES COMP_APPLICATION (UUID),
	CONSTRAINT CAI_SYSTEM_VALUE_FK1 FOREIGN KEY (APPLICANT_ROLE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT CAI_SYSTEM_VALUE_FK3 FOREIGN KEY (APPLICANT_STATUS_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)




CREATE TABLE COMP_APPLICANT_MW_ITEM
	(
	UUID                  VARCHAR2 (36) NOT NULL,
	COMPANY_APPLICANTS_ID VARCHAR2 (36),
	ITEM_TYPE_ID          VARCHAR2 (36),
	ITEM_CLASS_ID         VARCHAR2 (36),
	CREATED_BY            VARCHAR2 (20) NOT NULL,
	CREATED_DATE          DATE NOT NULL,
	MODIFIED_BY           VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE         DATE NOT NULL,
	CONSTRAINT PK_COMP_APPLICANT_MW_ITEM PRIMARY KEY (UUID),
	CONSTRAINT CAMI_COMP_APP_INFO_FK FOREIGN KEY (COMPANY_APPLICANTS_ID) REFERENCES COMP_APPLICANT_INFO (UUID),
	CONSTRAINT CAMI_SYSTEM_VALUE_FK1 FOREIGN KEY (ITEM_TYPE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT CAMI_SYSTEM_VALUE_FK2 FOREIGN KEY (ITEM_CLASS_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  
  
  
CREATE TABLE IND_APPLICATION
	(
	UUID                      VARCHAR2 (36) NOT NULL,
	REGISTRATION_TYPE         VARCHAR2 (15) NOT NULL,
	FILE_REFERENCE_NO         VARCHAR2 (36) NOT NULL,
	APPLICANT_ID              VARCHAR2 (36) NOT NULL,
	POST_TO                   VARCHAR2 (1),
	EMERGENCY_NO1             VARCHAR2 (22),
	EMERGENCY_NO2             VARCHAR2 (22),
	EMERGENCY_NO3             VARCHAR2 (22),
	TELEPHONE_NO1             VARCHAR2 (22),
	TELEPHONE_NO2             VARCHAR2 (22),
	TELEPHONE_NO3             VARCHAR2 (22),
	FAX_NO1                   VARCHAR2 (20),
	FAX_NO2                   VARCHAR2 (20),
	PRACTICE_NOTES_ID         VARCHAR2 (36),
	EMAIL                     VARCHAR2 (80),
	ENGLISH_HOME_ADDRESS_ID   VARCHAR2 (36) NOT NULL,
	CHINESE_HOME_ADDRESS_ID   VARCHAR2 (36) NOT NULL,
	ENGLISH_OFFICE_ADDRESS_ID VARCHAR2 (36) NOT NULL,
	CHINESE_OFFICE_ADDRESS_ID VARCHAR2 (36) NOT NULL,
	ENGLISH_BS_ADDRESS_ID     VARCHAR2 (36),
	CHINESE_BS_ADDRESS_ID     VARCHAR2 (36),
	BS_TELEPHONE_NO1          VARCHAR2 (22),
	BS_FAX_NO1                VARCHAR2 (20),
	REMARKS                   NVARCHAR2 (1000),
	ENGLISH_CARE_OF           VARCHAR2 (150),
	CHINESE_CARE_OF           NVARCHAR2 (50),
	ENGLISH_BS_CARE_OF        VARCHAR2 (150),
	CHINESE_BS_CARE_OF        NVARCHAR2 (50),
	QUALIFICATION             VARCHAR2 (500),
	REGION_CODE_ID            VARCHAR2 (36),
	CREATED_BY                VARCHAR2 (20) NOT NULL,
	CREATED_DATE              DATE NOT NULL,
	MODIFIED_BY               VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE             DATE NOT NULL,
	CORRESPONDENCE_LANG_ID    VARCHAR2 (36),
	BS_EMAIL                  VARCHAR2 (80),
	BS_REGION_CODE_ID         VARCHAR2 (36),
	WILLINGNESS_QP            VARCHAR2 (1),
	WILLINGNESS_QP_DATE       DATE,
	INTERESTED_FSS            VARCHAR2 (1),
	INTERESTED_FSS_DATE       DATE,
	MBIS_RI                   VARCHAR2 (1),
	CONSTRAINT PK_IND_APPLICATION PRIMARY KEY (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK1 FOREIGN KEY (ENGLISH_HOME_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK2 FOREIGN KEY (CHINESE_HOME_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK3 FOREIGN KEY (CHINESE_OFFICE_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK4 FOREIGN KEY (ENGLISH_OFFICE_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK5 FOREIGN KEY (ENGLISH_BS_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_ADDRESS_FK6 FOREIGN KEY (CHINESE_BS_ADDRESS_ID) REFERENCES ADDRESS (UUID),
	CONSTRAINT INDIVIDUAL_APP_APPLICANT_FK FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT (UUID),
	CONSTRAINT INDIVIDUAL_APP_SYS_VAL_FK FOREIGN KEY (REGION_CODE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT INDIVIDUAL_APP_SYS_VAL_FK2 FOREIGN KEY (PRACTICE_NOTES_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_APP_SV_BS_FK FOREIGN KEY (BS_REGION_CODE_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  

CREATE TABLE IND_APPLICATION_MW_ITEM
	(
	UUID            VARCHAR2 (36) NOT NULL,
	MASTER_ID       VARCHAR2 (36),
	ITEM_TYPE_ID    VARCHAR2 (36),
	ITEM_CLASS_ID   VARCHAR2 (36),
	ITEM_DETAILS_ID VARCHAR2 (36),
	SUPPORTED_BY_ID VARCHAR2 (36),
	CREATED_BY      VARCHAR2 (20) NOT NULL,
	CREATED_DATE    DATE NOT NULL,
	MODIFIED_BY     VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE   DATE NOT NULL,
	CONSTRAINT PK_IND_APPLICATION_MW_ITEM PRIMARY KEY (UUID),
	CONSTRAINT IND_APP_MW_ITEM_SYS_VAL_FK1 FOREIGN KEY (ITEM_TYPE_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_APP_MW_ITEM_SYS_VAL_FK2 FOREIGN KEY (ITEM_CLASS_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_APP_MW_ITEM_SYS_VAL_FK3 FOREIGN KEY (ITEM_DETAILS_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_MW_ITEM_IND_APP_FK FOREIGN KEY (MASTER_ID) REFERENCES IND_APPLICATION (UUID)
	)
  
  
  
  CREATE TABLE IND_CERTIFICATE
	(
	UUID                         VARCHAR2 (36) NOT NULL,
	MASTER_ID                    VARCHAR2 (36),
	CATEGORY_ID                  VARCHAR2 (36) NOT NULL,
	CERTIFICATION_NO             VARCHAR2 (20) NOT NULL,
	PERIOD_OF_VALIDITY_ID        VARCHAR2 (36),
	EXTENDED_DATE                DATE,
	GAZETTE_DATE                 DATE,
	APPROVAL_DATE                DATE,
	REGISTRATION_DATE            DATE,
	EXPIRY_DATE                  DATE,
	SUSPENSION_DATE              DATE,
	REMOVAL_DATE                 DATE,
	REMARKS                      NVARCHAR2 (500),
	RESTORE_DATE                 DATE,
	RESTORATION_APPLICATION_DATE DATE,
	RETENTION_DATE               DATE,
	RETENTION_APPLICATION_DATE   DATE,
	APPLICATION_DATE             DATE,
	APPLICATION_FORM_ID          VARCHAR2 (36),
	CANDIDATE_NUMBER             NUMBER (18),
	APPLICATION_STATUS_ID        VARCHAR2 (36),
	DOCUMENT_MAIL_DATE           DATE,
	MISS_DOCUMENT_TYPE           VARCHAR2 (10),
	VETTING_DATE                 DATE,
	USE_OLD_CATEGORY_CODE        VARCHAR2 (1),
	FILE_PATH_NONRESTRICTED      VARCHAR2 (100),
	FILE_PATH_RESTRICTED         VARCHAR2 (100),
	CREATED_BY                   VARCHAR2 (20) NOT NULL,
	CREATED_DATE                 DATE NOT NULL,
	MODIFIED_BY                  VARCHAR2 (20) NOT NULL,
	MODIFIED_DATE                DATE NOT NULL,
	CARD_EXPIRY_DATE             DATE,
	CARD_ISSUE_DATE              DATE,
	CARD_RETURN_DATE             DATE,
	CARD_SERIAL_NO               VARCHAR2 (20),
	CARD_APP_DATE                DATE,
	QP_ADDRESS_E1                NVARCHAR2 (40),
	QP_ADDRESS_E2                NVARCHAR2 (40),
	QP_ADDRESS_E3                NVARCHAR2 (40),
	QP_ADDRESS_E4                NVARCHAR2 (40),
	QP_ADDRESS_E5                NVARCHAR2 (40),
	QP_ADDRESS_C1                NVARCHAR2 (40),
	QP_ADDRESS_C2                NVARCHAR2 (40),
	QP_ADDRESS_C3                NVARCHAR2 (40),
	QP_ADDRESS_C4                NVARCHAR2 (40),
	QP_ADDRESS_C5                NVARCHAR2 (40),
	CONSTRAINT PK_IND_CERTIFICATE PRIMARY KEY (UUID),
	CONSTRAINT IND_CERT_CATEGORY_CODE_FK1 FOREIGN KEY (CATEGORY_ID) REFERENCES S_CATEGORY_CODE (UUID),
	CONSTRAINT IND_CERT_IND_APP_FK FOREIGN KEY (MASTER_ID) REFERENCES IND_APPLICATION (UUID),
	CONSTRAINT IND_CERT_SYSTEM_VALUE_FK2 FOREIGN KEY (PERIOD_OF_VALIDITY_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_CERT_SYSTEM_VALUE_FK3 FOREIGN KEY (APPLICATION_FORM_ID) REFERENCES S_SYSTEM_VALUE (UUID),
	CONSTRAINT IND_CERT_SYSTEM_VALUE_FK4 FOREIGN KEY (APPLICATION_STATUS_ID) REFERENCES S_SYSTEM_VALUE (UUID)
	)
  create or replace PACKAGE remappkg AS
/******************************************************************************
   NAME:       remap_pckg
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        10/5/2012      janma       1. Created this package.
******************************************************************************/
    function modify_char ( p_in_data varchar2) return varchar2;
 -- FUNCTION MyFunction(Param1 IN NUMBER) RETURN NUMBER;
  --PROCEDURE MyProcedure(Param1 IN NUMBER);
end;


create or replace package body     remappkg
as
    function modify_char (p_in_data varchar2) return varchar2
as
     v_return varchar2(30);
begin
    --v_return:=translate(p_in_data,'abcdefghijklmnopqrstuvwxyz','bcdefghijklmnopqrstuvwxyza');
    --v_return:=DBMS_RANDOM.STRING('A', 7);
    v_return:='Restricted';
    return v_return;
end;

END remappkg;

CREATE TABLE SYS_Email_Sender
	(
	UUID                VARCHAR2 (36) NOT NULL,
   	Recipient           VARCHAR2 (1000) NOT NULL,
    CC           	    VARCHAR2 (1000) ,
	Subject             VARCHAR2 (200) NOT NULL,
	EmailContent        VARCHAR2 (2000) ,
	Status				VARCHAR2 (200)  ,
	Attachment			BLOB ,
	
	CREATED_DATE        DATE NOT NULL,
	CREATED_BY          VARCHAR2 (100) NOT NULL,
	MODIFIED_DATE       DATE NOT NULL,
	MODIFIED_BY         VARCHAR2 (100) NOT NULL,
	PRIMARY KEY (UUID)
	)
   

