
CREATE TABLE P_S_SCU_TEAM
	(
	UUID              VARCHAR2 (36) NOT NULL,
	USER_ACCOUNT_ID   VARCHAR2 (36),
	CREATED_BY        VARCHAR2 (100) NOT NULL,
	CREATED_DATE      DATE,
	MODIFIED_BY       VARCHAR2 (100) NOT NULL,
	MODIFIED_DATE     DATE,
	SYS_POST_ID       VARCHAR2 (36),
	CHILD_SYS_POST_ID VARCHAR2 (36),
	CONSTRAINT P_SCU_TEAM_PK PRIMARY KEY (UUID)
	)
	TABLESPACE USERS
	STORAGE (BUFFER_POOL DEFAULT);

	
CREATE TABLE P_WF_ROUND_ROBIN
(

	
	UUID              VARCHAR2 (36) NOT NULL,
	WF_STATUS VARCHAR2(200)
	, CURRENT_POST VARCHAR2(200)
	,CONSTRAINT P_WF_ROUND_ROBIN_PK PRIMARY KEY (UUID)
)