-- MWMS_UNIT
  CREATE TABLE "MWMS_UNIT" 
   ("ADR_UNIT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ADR_BLK_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ADR_BLK_SL_ID" NUMBER(20,0), 
	"SYS_FLR_ALPHA_E_ID" NUMBER(20,0), 
	"FLR_NUM" NUMBER(4,0), 
	"FLR_ALPHA_E_SUFFIX" VARCHAR2(20 BYTE), 
	"UNT_DESC_E_ID" NUMBER(20,0), 
	"UNT_NO_NUM" NUMBER(5,0), 
	"UNT_NO_ALPHA" VARCHAR2(5 BYTE), 
	"UNT_NO_A_PREC" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"UNT_NO_SUF" VARCHAR2(5 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
   );

-- MWMS_BLK
  CREATE TABLE "MWMS_BLK" 
   ("ADR_BLK_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SYS_REGION_ID" NUMBER(20,0), 
	"SYS_DISTRICT_ID" NUMBER(20,0), 
	"AREA_ID" NUMBER(20,0), 
	"BLDG_NAME_E1" VARCHAR2(45 BYTE), 
	"BLDG_NAME_E2" VARCHAR2(45 BYTE), 
	"BLDG_NAME_E3" VARCHAR2(45 BYTE), 
	"BLDG_NAME_C1" VARCHAR2(80 BYTE), 
	"BLDG_NAME_C2" VARCHAR2(80 BYTE), 
	"BLDG_NAME_C3" VARCHAR2(80 BYTE), 
	"BLK_NO" VARCHAR2(163 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
   );

-- MWMS_BLK_SL
  CREATE TABLE "MWMS_BLK_SL" 
   ("ADR_BLK_SL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ADR_BLK_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SYS_ST_LOC_ID" NUMBER(20,0), 
	"ST_NO_NUM" NUMBER(4,0), 
	"ST_NO_ALPHA" VARCHAR2(2 BYTE), 
	"ST_NO_EXT" VARCHAR2(8 BYTE), 
	"UNOFF_CODE" VARCHAR2(100 BYTE), 
	"BLK_SL_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"PMS_ST_NO_CONFIRM" VARCHAR2(1 BYTE), 
	"OSADR_ST_E1" VARCHAR2(45 BYTE), 
	"OSADR_ST_E2" VARCHAR2(45 BYTE), 
	"OSADR_GEN_E" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"OSADR_ST_C" VARCHAR2(80 BYTE), 
	"OSADR_GEN_C" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
   );

-- MWMS_ST_LOC
  CREATE TABLE "MWMS_ST_LOC" 
   (	"SYS_ST_LOC_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SYS_ST_NAME_ID" NUMBER(20,0), 
	"SYS_LOC_NAME_ID1" NUMBER(20,0), 
	"SYS_LOC_NAME_ID2" NUMBER(20,0), 
	"SYS_LOC_NAME_ID3" NUMBER(20,0), 
	"SL_NAME_C" VARCHAR2(80 BYTE), 
	"NATURE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"LR_LOC" VARCHAR2(2 BYTE), 
	"LR_ST" VARCHAR2(4 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
   );

-- MWMS_ADDRESS_META_DATA
 CREATE TABLE "MWMS_ADDRESS_META_DATA" 
   ("SYS_META_DATA_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"REC_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(20,0), 
	"ENGLISH_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CHINESE_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"MODIFIED_DATE" DATE
   );