//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(C_ADDRESS_Extend))] public partial class C_ADDRESS
    {

        [Display(Name = "Address")]
        public string ADDRESS_FULL_HTML_DISPLAY
        {
            get
            {
                return
                CommonUtil.getDisplay(this.ADDRESS_LINE1 + "<BR>")
                + CommonUtil.getDisplay(this.ADDRESS_LINE2 + "<BR>")
                + CommonUtil.getDisplay(this.ADDRESS_LINE3 + "<BR>")
                + CommonUtil.getDisplay(this.ADDRESS_LINE4 + "<BR>")
                + CommonUtil.getDisplay(this.ADDRESS_LINE5 + "<BR>");
            }
        }
    }

    public partial class C_ADDRESS_Extend
    {

    }
}