//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(C_APPLICANT_Extend))] public partial class C_APPLICANT
    {
        private bool _decrypted { get; set; }
        public string FULL_NAME_DISPLAY
        {
            get { return this.SURNAME + " " + this.GIVEN_NAME_ON_ID; }
        }
        public string HKID_PASSPORT_DISPLAY
        {
            get
            {
                return this.HKID == null || this.PASSPORT_NO == null ? (this.HKID + this.PASSPORT_NO) : (this.HKID + " " + this.PASSPORT_NO);
            }
        }
        public C_APPLICANT Decrypt()
        {
            if (_decrypted) return this;
            this.HKID = string.IsNullOrWhiteSpace(this.HKID) ? "" : EncryptDecryptUtil.getDecryptHKID(this.HKID);
            this.PASSPORT_NO = string.IsNullOrWhiteSpace(this.PASSPORT_NO) ? "" : EncryptDecryptUtil.getDecryptHKID(this.PASSPORT_NO);
            _decrypted = true;
            return this;
        }
        public C_APPLICANT Encrypt()
        {
            this.HKID = string.IsNullOrWhiteSpace(this.HKID) ? "" : EncryptDecryptUtil.getEncrypt(this.HKID);
            this.PASSPORT_NO = string.IsNullOrWhiteSpace(this.PASSPORT_NO) ? "" : EncryptDecryptUtil.getEncrypt(this.PASSPORT_NO);
            return this;
        }
    }

    public partial class C_APPLICANT_Extend
    {

        [Display(Name = "HKID")]
        public string HKID { get; set; }
        [Display(Name = "Passport No.")]
        public string PASSPORT_NO { get; set; }
        [Display(Name = "Title")]
        public string TITLE_ID { get; set; }
        [Display(Name = "Surname")]
        public string SURNAME { get; set; }
        [Display(Name = "Given Name")]
        public string GIVEN_NAME_ON_ID { get; set; }

        [Display(Name = "Chinese Name")]
        public string CHINESE_NAME { get; set; }

        [Display(Name = "Pooling")]
        public string IS_POOLING { get; set; }

        [Display(Name = "Sex")]
        public string GENDER { get; set; }

        /*public string UUID { get; set; }
        public string HKID { get; set; }
        public string PASSPORT_NO { get; set; }
        public string SURNAME { get; set; }
        public string GIVEN_NAME_ON_ID { get; set; }
        public string GENDER { get; set; }
        public string CHINESE_NAME { get; set; }
        public string IS_POOLING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string TITLE_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DATE_OF_DISPOSAL { get; set; }*/
    }
}