//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(C_COMP_PROCESS_MONITOR_Extend))] public partial class C_COMP_PROCESS_MONITOR
    {
    }

    public partial class C_COMP_PROCESS_MONITOR_Extend
    {
        [Display(Name = "Vetting Officer")]
        public string VETTING_OFFICER { get; set; }
        [Display(Name = "Received Date")]
        public string RECEIVED_DATE { get; set; }
    }
}