//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(C_IND_APPLICATION_Extend))] public partial class C_IND_APPLICATION
    {
        
        [Display(Name = "QP")]
        public string QP_DISPLAY
        {
            get
            {
                return "Y".Equals(this.WILLINGNESS_QP) ? "YES"
                  : "N".Equals(this.WILLINGNESS_QP) ? "NO"
                  : "No Indication";
            }
        }

        

        [Display(Name = "Emergency Nos.")]
        public string EMERGRNCY_NOS_DISPLAY
        {
            get
            {
                return string.Join("/ ", new string[] {
                    CommonUtil.getDisplay(this.EMERGENCY_NO1)
                    , CommonUtil.getDisplay(this.EMERGENCY_NO2)
                    , CommonUtil.getDisplay(this.EMERGENCY_NO3) });
            }
        }

        [Display(Name = "Telephone Nos.")]
        public string TELEPHONE_NOS_DISPLAY
        {
            get
            {
                return string.Join("/ ", new string[] {
                    CommonUtil.getDisplay(this.TELEPHONE_NO1)
                    , CommonUtil.getDisplay(this.TELEPHONE_NO2)
                    , CommonUtil.getDisplay(this.TELEPHONE_NO3) });
            }
        }

        [Display(Name = "Fax Nos.")]
        public string FAX_NOS_DISPLAY
        {
            get
            {
                return string.Join("/ ", new string[] {
                    CommonUtil.getDisplay(this.FAX_NO1)
                    , CommonUtil.getDisplay(this.FAX_NO2) });
            }
        }
    }

    public partial class C_IND_APPLICATION_Extend
    {
        [Display(Name = "Telephone No.")]
        public Nullable<System.DateTime> BS_TELEPHONE_NO1 { get; set; }
        [Display(Name = "Fax No.")]
        public Nullable<System.DateTime> BS_FAX_NO1 { get; set; }


        [Display(Name = "File Reference No.")]
        public string FILE_REFERENCE_NO { get; set; }




        /*
            <div class="w3-col l3 m6 s12">@Html.LabelFor(o => o.C_IND_APPLICATION.BS_TELEPHONE_NO1) :</div>
            <div class="w3-col l3 m6 s12">@Html.DisplayFor(o => o.C_IND_APPLICATION.BS_TELEPHONE_NO1)</div>
            <div class="w3-col l3 m6 s12">@Html.LabelFor(o => o.C_IND_APPLICATION.BS_FAX_NO1) :</div>
            <div class="w3-col l3 m6 s12">@Html.DisplayFor(o => o.C_IND_APPLICATION.BS_FAX_NO1)</div>*/
    }
}