//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(SYS_POST_Extend))] public partial class SYS_POST
    {
    }

    public partial class SYS_POST_Extend
    {

        [Display(Name = "Portal ID")]
        public string BD_PORTAL_LOGIN { get; set; }
        [Display(Name = "Post Code")]
        public string CODE { get; set; }
        [Display(Name = "Supervisor")]
        public string SUPERVISOR_ID { get; set; }
        [Display(Name = "Fax No.")]
        public string FAX_NO { get; set; }
        [Display(Name = "DSMS Username")]
        public string DSMS_USERNAME { get; set; }
        [Display(Name = "Active")]
        public string IS_ACTIVE { get; set; }
        [Display(Name = "Rank")]
        public string SYS_RANK_ID { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Display(Name = "Phone No.")]
        public string PHONE { get; set; }
        [Display(Name = "Receive Case?")]
        public string RECEIVE_CASE { get; set; }
        [Display(Name = "Unit")]
        public string SYS_UNIT_ID { get; set; }

        [Display(Name = "Password")]
        public string PW { get; set; }
        [Display(Name = "DSMS Password")]
        public string DSMS_PW { get; set; }

    }
}