//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using MWMS2.Services;
    using MWMS2.Utility;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(W_WL_Extend))]
    public partial class W_WL : IValidatableObject
    {
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield return ValidationUtil.Validate_Mandatory(this, "SUBJECT");
            yield return ValidationUtil.Validate_Mandatory(this, "REGISTRATION_NO");
            yield return Validate_RegNo("REGISTRATION_NO");
        }

        public ValidationResult Validate_RegNo(string propName)
        {
            WarningLetterSearchService wl = new WarningLetterSearchService();
            return wl.Validate_RegNo(propName, this);
        }
        public string DISPLAY_CATEGORY
        {
            get;set;
        }
    }

    public partial class W_WL_Extend
    {

    }
}