//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_EFSCU_TBL_SC01
    {
        public string ID { get; set; }
        public string APCFMCHINAME { get; set; }
        public Nullable<byte> APCFMCONFIRMOPTION1 { get; set; }
        public Nullable<byte> APCFMCONFIRMOPTION2 { get; set; }
        public System.DateTime APCFMCREXPIREDDATE { get; set; }
        public string APCFMCRNUM1 { get; set; }
        public string APCFMCRNUM2 { get; set; }
        public string APCFMCRNUM3 { get; set; }
        public string APCFMENGNAME { get; set; }
        public string APCFMSIGN { get; set; }
        public System.DateTime APCFMSIGNDATE { get; set; }
        public System.DateTime APCFMSIGNEXPIREDDATE { get; set; }
        public string APCFMSIGNNAME { get; set; }
        public string APCFMSIGNRESULT { get; set; }
        public string APCHINAME { get; set; }
        public string APCRNUM1 { get; set; }
        public string APCRNUM2 { get; set; }
        public string APENGNAME { get; set; }
        public Nullable<byte> ARRISAPOPTION { get; set; }
        public Nullable<byte> ARRISRGBCOPTION { get; set; }
        public Nullable<byte> ARRISRMWCTYPECOPTION { get; set; }
        public Nullable<byte> ARRISRSEOPTION { get; set; }
        public Nullable<byte> ARRISSOOPTION { get; set; }
        public string ARRNAME { get; set; }
        public string ARRSIGN { get; set; }
        public System.DateTime ARRSIGNDATE { get; set; }
        public System.DateTime ARRSIGNEXPIREDDATE { get; set; }
        public string ARRSIGNNAME { get; set; }
        public string ARRSIGNRESULT { get; set; }
        public System.DateTime ASDATE { get; set; }
        public Nullable<byte> ASNOTINVOLVEDOPTION { get; set; }
        public Nullable<byte> ASWORKOPTION { get; set; }
        public string BUILDING { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM1A { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM1AQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM1B { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM1BQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM1C { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM1CQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM2A { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM2AQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM2B { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM2BQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM2C { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM2CQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM3 { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM3QTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM4A { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM4AQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM4B { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM4BQTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM5 { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM5QTY { get; set; }
        public Nullable<byte> INSPECTEDUNAUTHSIGNBOARDITEM6 { get; set; }
        public decimal INSPECTEDUNAUTHSIGNBOARDITEM6QTY { get; set; }
        public System.DateTime INSPECTIONDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public string OWNERCORPAREA { get; set; }
        public string OWNERCORPBUILDING { get; set; }
        public string OWNERCORPDISTRICT { get; set; }
        public string OWNERCORPFLAT { get; set; }
        public string OWNERCORPFLOOR { get; set; }
        public Nullable<byte> OWNERCORPFORMEDOPTION { get; set; }
        public string OWNERCORPSTREET { get; set; }
        public string OWNERCORPSTREETNO { get; set; }
        public string PRCASCFMCHINAME { get; set; }
        public string PRCASCFMENGNAME { get; set; }
        public string PRCCFMCHINAME { get; set; }
        public Nullable<byte> PRCCFMCONFIRMOPTION { get; set; }
        public System.DateTime PRCCFMCREXPIREDDATE { get; set; }
        public string PRCCFMCRNUM1 { get; set; }
        public string PRCCFMCRNUM2 { get; set; }
        public string PRCCFMENGNAME1 { get; set; }
        public string PRCCFMENGNAME2 { get; set; }
        public string PRCCFMSIGN { get; set; }
        public System.DateTime PRCCFMSIGNDATE { get; set; }
        public System.DateTime PRCCFMSIGNEXPIREDDATE { get; set; }
        public string PRCCFMSIGNNAME { get; set; }
        public string PRCCFMSIGNRESULT { get; set; }
        public string PRCCHINAME { get; set; }
        public string PRCCRNUM1 { get; set; }
        public string PRCCRNUM2 { get; set; }
        public string PRCENGNAME { get; set; }
        public Nullable<byte> PRCISRGBCOPTION { get; set; }
        public Nullable<byte> PRCISRMWCOPTION { get; set; }
        public Nullable<byte> RGBCOPTION { get; set; }
        public Nullable<byte> RMWCTYPECOPTION { get; set; }
        public string RSECFMCHINAME { get; set; }
        public System.DateTime RSECFMCREXPIREDDATE { get; set; }
        public string RSECFMCRNUM1 { get; set; }
        public string RSECFMCRNUM2 { get; set; }
        public string RSECFMENGNAME { get; set; }
        public string RSECFMSIGN { get; set; }
        public System.DateTime RSECFMSIGNDATE { get; set; }
        public System.DateTime RSECFMSIGNEXPIREDDATE { get; set; }
        public string RSECFMSIGNNAME { get; set; }
        public string RSECFMSIGNRESULT { get; set; }
        public string RSECHINAME { get; set; }
        public string RSECRNUM1 { get; set; }
        public string RSECRNUM2 { get; set; }
        public string RSEENGNAME { get; set; }
        public Nullable<byte> RSEOPTION { get; set; }
        public string SCHEMESUBMITID { get; set; }
        public Nullable<byte> SOBRCOPYOPTION { get; set; }
        public string SOBRN { get; set; }
        public string SOBUSCHINAME { get; set; }
        public string SOBUSENGNAME1 { get; set; }
        public string SOBUSENGNAME2 { get; set; }
        public string SOCHINAMEOFBUSINESS { get; set; }
        public Nullable<byte> SOCORRADDRSAMEASOPADDR { get; set; }
        public string SOCORRAREA { get; set; }
        public string SOCORRBUILDING { get; set; }
        public string SOCORRDISTRICT { get; set; }
        public string SOCORRFLAT { get; set; }
        public string SOCORRFLOOR { get; set; }
        public string SOCORRSTREET { get; set; }
        public string SOCORRSTREETNO { get; set; }
        public string SOENGNAMEOFBUSINESS1 { get; set; }
        public string SOENGNAMEOFBUSINESS2 { get; set; }
        public string SOFAX { get; set; }
        public Nullable<byte> SOLRCOPYOPTION { get; set; }
        public string SOOPBUSINESSAREA { get; set; }
        public string SOOPBUSINESSBUILDING { get; set; }
        public string SOOPBUSINESSDISTRICT { get; set; }
        public string SOOPBUSINESSFLAT { get; set; }
        public string SOOPBUSINESSFLOOR { get; set; }
        public string SOOPBUSINESSSTREET { get; set; }
        public string SOOPBUSINESSSTREETNO { get; set; }
        public string SOOTHER { get; set; }
        public Nullable<byte> SOOTHEROPTION { get; set; }
        public string SOSIGN { get; set; }
        public System.DateTime SOSIGNDATE { get; set; }
        public System.DateTime SOSIGNEXPIREDDATE { get; set; }
        public string SOSIGNNAME { get; set; }
        public string SOSIGNRESULT { get; set; }
        public string SOTEL { get; set; }
        public string STREETNO { get; set; }
        public string STREETROADVILLAGE { get; set; }
        public string UNAUTHSIGNBOARDAREA { get; set; }
        public string UNAUTHSIGNBOARDDETAILEDLOCATION { get; set; }
        public string UNAUTHSIGNBOARDDISTRICT { get; set; }
        public string UNAUTHSIGNBOARDFLAT { get; set; }
        public string UNAUTHSIGNBOARDFLOOR { get; set; }
    }
}
