//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_EFSCU_TBL_SC02C
    {
        public string ID { get; set; }
        public string APCHINAME { get; set; }
        public System.DateTime APCREXPIREDDATE { get; set; }
        public string APCRNUM1 { get; set; }
        public string APCRNUM2 { get; set; }
        public string APENGNAME { get; set; }
        public Nullable<byte> APISAPOPTION { get; set; }
        public Nullable<byte> APISRCOPTION { get; set; }
        public Nullable<byte> APISRIOPTION { get; set; }
        public Nullable<byte> APISRSEOPTION { get; set; }
        public string APSIGN { get; set; }
        public System.DateTime APSIGNDATE { get; set; }
        public System.DateTime APSIGNEXPIREDDATE { get; set; }
        public string APSIGNNAME { get; set; }
        public string APSIGNRESULT { get; set; }
        public System.DateTime COMMENCEDATE { get; set; }
        public System.DateTime COMPLETEDATE { get; set; }
        public Nullable<byte> COMPLETEDWORKSAMEASSC02OPTION { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string EMAIL { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string PRCASCHINAME { get; set; }
        public string PRCASENGNAME { get; set; }
        public string PRCCHINAME { get; set; }
        public System.DateTime PRCCREXPIREDDATE { get; set; }
        public string PRCCRNUM1 { get; set; }
        public string PRCCRNUM2 { get; set; }
        public string PRCENGNAME1 { get; set; }
        public string PRCENGNAME2 { get; set; }
        public string PRCFAX { get; set; }
        public string PRCSIGN { get; set; }
        public System.DateTime PRCSIGNDATE { get; set; }
        public System.DateTime PRCSIGNEXPIREDDATE { get; set; }
        public string PRCSIGNNAME { get; set; }
        public string PRCSIGNRESULT { get; set; }
        public string PRCTEL { get; set; }
        public string SCHEMESUBMITID { get; set; }
    }
}
