//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_EFSS_SC03
    {
        public string ID { get; set; }
        public string SUBMISSION_NO { get; set; }
        public string SIGNBOARD_LOC { get; set; }
        public string SIGNBOARD_OWNER_CHI_NAME { get; set; }
        public string SIGNBOARD_OWNER_ENG_NAME { get; set; }
        public string SIGNBOARD_OWNER_BR_NO { get; set; }
        public string SIGNBOARD_OWNER_FAX_NO { get; set; }
        public string SIGNBOARD_OWNER_TEL_NO { get; set; }
        public string SIGNBOARD_OWNER_EMAIL { get; set; }
        public string BIZ_CORR_ADDR_FLAT { get; set; }
        public string BIZ_CORR_ADDR_FLOOR { get; set; }
        public string BIZ_CORR_ADDR_BLOCK { get; set; }
        public string BIZ_CORR_ADDR_BLDG_ESTATE { get; set; }
        public string BIZ_CORR_ADDR_STREET_NAME { get; set; }
        public string BIZ_CORR_ADDR_STREET_NO { get; set; }
        public string BIZ_CORR_ADDR_DIST { get; set; }
        public string BIZ_CORR_ADDR_REGION { get; set; }
        public string OWER_COP_CORR_ADDR_FLAT { get; set; }
        public string OWER_COP_CORR_ADDR_FLOOR { get; set; }
        public string OWER_COP_CORR_ADDR_BLOCK { get; set; }
        public string OWER_COP_CORR_ADDR_BLDG_ESTATE { get; set; }
        public string OWER_COP_CORR_ADDR_STREET_NAME { get; set; }
        public string OWER_COP_CORR_ADDR_STREET_NO { get; set; }
        public string OWER_COP_CORR_ADDR_DIST { get; set; }
        public string OWER_COP_CORR_ADDR_REGION { get; set; }
        public string PAW_CHI_NAME { get; set; }
        public string PAW_ENG_NAME { get; set; }
        public string APP_TYPE { get; set; }
        public string APP_CHI_NAME { get; set; }
        public string APP_CERT_REG_NO { get; set; }
        public string APP_ENG_NAME { get; set; }
        public Nullable<System.DateTime> APP_REG_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> APP_SIGN_DATE { get; set; }
        public string PRC_CHI_NAME { get; set; }
        public string PRC_ENG_NAME { get; set; }
        public string PRC_AS_CHI_NAME { get; set; }
        public string PRC_AS_ENG_NAME { get; set; }
        public string PRC_CERT_REG_NO { get; set; }
        public Nullable<System.DateTime> PRC_REG_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> PRC_SIGN_DATE { get; set; }
        public string ISCOPIED { get; set; }
        public string BD_BLK_ID { get; set; }
        public string BD_FILE_REF { get; set; }
        public string SIGNBOARD_ADDR_FLAT { get; set; }
        public string SIGNBOARD_ADDR_FLOOR { get; set; }
        public string SIGNBOARD_ADDR_BLOCK { get; set; }
        public string SIGNBOARD_ADDR_BLDG_ESTATE { get; set; }
        public string SIGNBOARD_ADDR_STREET_NAME { get; set; }
        public string SIGNBOARD_ADDR_STREET_NO { get; set; }
        public string SIGNBOARD_ADDR_DIST { get; set; }
        public string SIGNBOARD_ADDR_REGION { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string WITH_ALTER_STRENGTH { get; set; }
    }
}
