//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_RV_TENEMENT
    {
        public string UUID { get; set; }
        public int TT_TABLE_ID { get; set; }
        public int TT_BG_TABLE_ID { get; set; }
        public string TT_ASS_NO { get; set; }
        public string TT_RATING_DESC_ENG { get; set; }
        public string TT_RATING_DESC_CHN { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
