//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_RVD
    {
        public decimal UUID { get; set; }
        public Nullable<int> RV_BLOCK_ID { get; set; }
        public Nullable<int> RV_STREET_LOCATION_ID { get; set; }
        public Nullable<int> RV_BUILDING_ID { get; set; }
        public string BLDG_NAME_ENG { get; set; }
        public string BLDG_NAME_CHN { get; set; }
        public string STREET_NAME_ENG { get; set; }
        public string STREET_NAME_CHN { get; set; }
        public string STREET_NAME_ENG_NO_ENCODED { get; set; }
        public string NDS_CODE { get; set; }
        public string NDS_DESCRIPTION_ENG { get; set; }
        public string NDS_DESCRIPTION_CHN { get; set; }
        public Nullable<short> BK_BLDG_NO_NUMERIC { get; set; }
        public string BK_BLDG_NO_ALPHA { get; set; }
        public string BK_BLDG_NO_EXT { get; set; }
        public string BUILDING_TYPE { get; set; }
        public string BUILDING_KEY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string BCIS_KEY { get; set; }
    }
}
