//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_RV_STREET_LOCATION
    {
        public string UUID { get; set; }
        public int SL_TABLE_ID { get; set; }
        public Nullable<int> SL_SM_TABLE_ID { get; set; }
        public Nullable<int> SL_LC_TABLE_ID1 { get; set; }
        public Nullable<int> SL_LC_TABLE_ID2 { get; set; }
        public Nullable<int> SL_LC_TABLE_ID3 { get; set; }
        public string SL_LOC_NATURE { get; set; }
        public string SL_NAME_CHN { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
