//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_S_SYSTEM_VALUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_S_SYSTEM_VALUE()
        {
            this.B_S_SYSTEM_VALUE1 = new HashSet<B_S_SYSTEM_VALUE>();
        }
    
        public string UUID { get; set; }
        public string SYSTEM_TYPE_ID { get; set; }
        public string CODE { get; set; }
        public string PARENT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_ACTIVE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual B_S_SYSTEM_TYPE B_S_SYSTEM_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_S_SYSTEM_VALUE> B_S_SYSTEM_VALUE1 { get; set; }
        public virtual B_S_SYSTEM_VALUE B_S_SYSTEM_VALUE2 { get; set; }
    }
}
