//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_S_LETTER_TEMPLATE
    {
        public string UUID { get; set; }
        public string LETTER_NAME { get; set; }
        public string FORM_CODE { get; set; }
        public string LETTER_TYPE { get; set; }
        public string RESULT { get; set; }
        public string FILE_PATH { get; set; }
        public string FILE_NAME { get; set; }
        public string EXTENSION { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
