//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_S_PARAMETER
    {
        public string UUID { get; set; }
        public string SYSTEM_ASSIGN { get; set; }
        public string SPO_VALIDATION { get; set; }
        public string SPO_AUDIT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public Nullable<decimal> PROCESS_S24_DAY { get; set; }
        public Nullable<decimal> PROCESS_GC_DAY { get; set; }
        public Nullable<decimal> NUMBER_OF_JOB_ASSIGN { get; set; }
        public Nullable<decimal> VALIDATION_EXPIRY_YEAR_NUM { get; set; }
        public Nullable<decimal> TARGET_DATE { get; set; }
    }
}
