//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_RECORD_ITEM_CHECKLIST_ITEM
    {
        public string UUID { get; set; }
        public string REMARKS { get; set; }
        public string S_MW_ITEM_CHECKLIST_ITEM_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string SV_RECORD_ITEM_CHECKLIST_ID { get; set; }
        public string ITEM_DETAILS { get; set; }
        public string REMARKS_TO { get; set; }
    
        public virtual B_S_MW_ITEM_CHECKLIST_ITEM B_S_MW_ITEM_CHECKLIST_ITEM { get; set; }
        public virtual B_SV_RECORD_ITEM_CHECKLIST B_SV_RECORD_ITEM_CHECKLIST { get; set; }
    }
}
