//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_COMPLAIN
    {
        public string UUID { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> COMPLAINT_DATE { get; set; }
        public string REMARKS { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string COMPLAIN_NUMBER { get; set; }
        public string CASE_NO { get; set; }
        public string CASE_ID { get; set; }
        public string FILE_REFERENCE { get; set; }
        public string ICC_OTHER_DEPT_REF_NO { get; set; }
        public string SV_ADDRESS_ID { get; set; }
        public string SOURCE_OF_REPORT { get; set; }
        public string ACTION_RECOMMENDED { get; set; }
        public string REPLY_TO_REPORTER { get; set; }
        public Nullable<System.DateTime> REPLY_DATE { get; set; }
        public string RESPONSIBLE_TO { get; set; }
        public string RESPONSIBLE_PO { get; set; }
        public string RESPONSIBLE_SPO { get; set; }
        public string RECORD_TYPE { get; set; }
    }
}
