//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_RECORD_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_SV_RECORD_ITEM()
        {
            this.B_SV_RECORD_ITEM_CHECKLIST = new HashSet<B_SV_RECORD_ITEM_CHECKLIST>();
        }
    
        public string UUID { get; set; }
        public string SV_RECORD_ID { get; set; }
        public string MW_ITEM_CODE { get; set; }
        public string LOCATION_DESCRIPTION { get; set; }
        public string REVISION { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public string CLASS_CODE { get; set; }
        public string STATUS_CODE { get; set; }
        public string RRM_SYN_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
    
        public virtual B_SV_RECORD B_SV_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_SV_RECORD_ITEM_CHECKLIST> B_SV_RECORD_ITEM_CHECKLIST { get; set; }
    }
}
