//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_AUDIT_RECORD
    {
        public string UUID { get; set; }
        public string SV_RECORD_ID { get; set; }
        public string ACTION_DESC { get; set; }
        public string ASSIGNMENT { get; set; }
        public string AUDIT_STATUS { get; set; }
        public string CONFIRMED { get; set; }
        public string AUDIT_MW_STATUS { get; set; }
        public string OTHER_HANDLING_OFFICER { get; set; }
        public string AUDIT_DESCRIPTION { get; set; }
        public string ORDER_NOTICE_LETTER_REF_NO { get; set; }
        public string AUDIT_RESULT { get; set; }
        public Nullable<System.DateTime> REFERRAL_DATE { get; set; }
        public Nullable<System.DateTime> REPLY_DATE { get; set; }
        public string AUDIT_REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string WF_STATUS { get; set; }
    
        public virtual B_SV_RECORD B_SV_RECORD { get; set; }
    }
}
