//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_SUBMISSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_SV_SUBMISSION()
        {
            this.B_SV_RECORD = new HashSet<B_SV_RECORD>();
        }
    
        public string UUID { get; set; }
        public string RECORD_TYPE { get; set; }
        public string RECORD_ID { get; set; }
        public Nullable<System.DateTime> SCU_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> RD_RECEIVED_DATE { get; set; }
        public string FORM_CODE { get; set; }
        public Nullable<System.DateTime> RD_DELIVERED_DATE { get; set; }
        public Nullable<System.DateTime> SCU_DELIVERED_DATE { get; set; }
        public string STATUS { get; set; }
        public string REFERENCE_NO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string BATCH_NO { get; set; }
        public string SV_SCANNED_DOCUMENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_SV_RECORD> B_SV_RECORD { get; set; }
        public virtual B_SV_SCANNED_DOCUMENT B_SV_SCANNED_DOCUMENT { get; set; }
    }
}
