//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_VALIDATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_SV_VALIDATION()
        {
            this.B_SV_RECORD_FORM_CHECKLIST = new HashSet<B_SV_RECORD_FORM_CHECKLIST>();
            this.B_SV_RECORD_ITEM_CHECKLIST = new HashSet<B_SV_RECORD_ITEM_CHECKLIST>();
        }
    
        public string UUID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string RECORD_STATUS { get; set; }
        public string VALIDATION_RESULT { get; set; }
        public Nullable<System.DateTime> SPO_ENDORSEMENT_DATE { get; set; }
        public string REMARKS { get; set; }
        public string VALIDATION_STATUS { get; set; }
        public Nullable<System.DateTime> SIGNBOARD_EXPIRY_DATE { get; set; }
        public string SV_RECORD_ID { get; set; }
        public string ENDORSED_BY { get; set; }
        public string LETTER_STATUS { get; set; }
        public string LETTER_MERGE_BY { get; set; }
        public string LETTER_REASON { get; set; }
        public string LETTER_REMARKS { get; set; }
        public string RECORD_ITEM_RESULT { get; set; }
        public string RECORD_ITEM_RESULT_TO { get; set; }
        public string SITE_AUDIT_RESULT { get; set; }
        public string STRUCT_CALC_CHECK { get; set; }
    
        public virtual B_SV_RECORD B_SV_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_SV_RECORD_FORM_CHECKLIST> B_SV_RECORD_FORM_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_SV_RECORD_ITEM_CHECKLIST> B_SV_RECORD_ITEM_CHECKLIST { get; set; }
    }
}
