//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SV_24_ORDER
    {
        public string UUID { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string HANDLING_OFFICER { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public string CREATED_SUBMITTED_BY { get; set; }
        public string PO_USER_ID { get; set; }
        public string SPO_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_SUBMITTED_DATE { get; set; }
        public string STAGE { get; set; }
        public string WF_STATUS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string IS_APPROVED { get; set; }
        public string STATUS_CODE { get; set; }
        public string CASE_NO { get; set; }
        public string CASE_ID { get; set; }
        public string FILE_REFERENCE { get; set; }
        public string ICC_OTHER_DEPT_REF_NO { get; set; }
        public string TYPE_CODE { get; set; }
        public string SV_ADDRESS_ID { get; set; }
        public string TO_USER_ID { get; set; }
        public string REPORT_NO { get; set; }
        public string COMPLIED_WITH { get; set; }
        public Nullable<System.DateTime> COMPLIANCE_LETTER_ISSUED_DATE { get; set; }
        public string TITLE_DESCRIPTION { get; set; }
    }
}
