//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ADDRESS()
        {
            this.C_ADDRESS_HISTORY = new HashSet<C_ADDRESS_HISTORY>();
            this.C_S_ROOM = new HashSet<C_S_ROOM>();
            this.C_COMMITTEE_MEMBER = new HashSet<C_COMMITTEE_MEMBER>();
            this.C_COMMITTEE_MEMBER1 = new HashSet<C_COMMITTEE_MEMBER>();
            this.C_COMP_APPLICATION = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION1 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION2 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION3 = new HashSet<C_COMP_APPLICATION>();
            this.C_S_ROOM1 = new HashSet<C_S_ROOM>();
            this.C_IND_APPLICATION = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION1 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION2 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION3 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION4 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION5 = new HashSet<C_IND_APPLICATION>();
        }
    
        public string UUID { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public string ADDRESS_LINE2 { get; set; }
        public string ADDRESS_LINE3 { get; set; }
        public string ADDRESS_LINE4 { get; set; }
        public string ADDRESS_LINE5 { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ADDRESS_HISTORY> C_ADDRESS_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_ROOM> C_S_ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_MEMBER> C_COMMITTEE_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_MEMBER> C_COMMITTEE_MEMBER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_ROOM> C_S_ROOM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION5 { get; set; }
    }
}
