//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMMITTEE_MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_COMMITTEE_MEMBER()
        {
            this.C_COMMITTEE_COMMITTEE_MEMBER = new HashSet<C_COMMITTEE_COMMITTEE_MEMBER>();
            this.C_COMMITTEE_GROUP_MEMBER = new HashSet<C_COMMITTEE_GROUP_MEMBER>();
            this.C_COMMITTEE_PANEL_MEMBER = new HashSet<C_COMMITTEE_PANEL_MEMBER>();
            this.C_MEETING_MEMBER = new HashSet<C_MEETING_MEMBER>();
            this.C_MEMBER_CATEGORY = new HashSet<C_MEMBER_CATEGORY>();
            this.C_COMMITTEE_MEMBER_INSTITUTE = new HashSet<C_COMMITTEE_MEMBER_INSTITUTE>();
        }
    
        public string UUID { get; set; }
        public string APPLICANT_ID { get; set; }
        public string EMAIL { get; set; }
        public string RANK { get; set; }
        public string POST { get; set; }
        public string CAREER { get; set; }
        public string TELEPHONE_NO1 { get; set; }
        public string TELEPHONE_NO2 { get; set; }
        public string TELEPHONE_NO3 { get; set; }
        public string FAX_NO1 { get; set; }
        public string FAX_NO2 { get; set; }
        public string ENGLISH_ADDRESS_ID { get; set; }
        public string CHINESE_ADDRESS_ID { get; set; }
        public string ENGLISH_CARE_OF { get; set; }
        public string CHINESE_CARE_OF { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_ADDRESS C_ADDRESS { get; set; }
        public virtual C_ADDRESS C_ADDRESS1 { get; set; }
        public virtual C_APPLICANT C_APPLICANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_COMMITTEE_MEMBER> C_COMMITTEE_COMMITTEE_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_GROUP_MEMBER> C_COMMITTEE_GROUP_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_PANEL_MEMBER> C_COMMITTEE_PANEL_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_MEETING_MEMBER> C_MEETING_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_MEMBER_CATEGORY> C_MEMBER_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_MEMBER_INSTITUTE> C_COMMITTEE_MEMBER_INSTITUTE { get; set; }
    }
}
