//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMMITTEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_COMMITTEE()
        {
            this.C_COMMITTEE_COMMITTEE_MEMBER = new HashSet<C_COMMITTEE_COMMITTEE_MEMBER>();
            this.C_COMMITTEE_GROUP = new HashSet<C_COMMITTEE_GROUP>();
        }
    
        public string UUID { get; set; }
        public Nullable<short> YEAR { get; set; }
        public string COMMITTEE_PANEL_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string COMMITTEE_TYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_COMMITTEE_MEMBER> C_COMMITTEE_COMMITTEE_MEMBER { get; set; }
        public virtual C_COMMITTEE_PANEL C_COMMITTEE_PANEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_GROUP> C_COMMITTEE_GROUP { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
