//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMP_APPLICANT_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_COMP_APPLICANT_INFO()
        {
            this.C_COMP_APPLICANT_INFO1 = new HashSet<C_COMP_APPLICANT_INFO>();
            this.C_COMP_APPLICANT_INFO_HISTORY = new HashSet<C_COMP_APPLICANT_INFO_HISTORY>();
            this.C_COMP_APPLICANT_INFO_MASTER = new HashSet<C_COMP_APPLICANT_INFO_MASTER>();
            this.C_COMP_APPLICANT_MW_ITEM = new HashSet<C_COMP_APPLICANT_MW_ITEM>();
            this.C_LEAVE_FORM = new HashSet<C_LEAVE_FORM>();
            this.C_COMP_APPLN_MW_ITEM_HISTORY = new HashSet<C_COMP_APPLN_MW_ITEM_HISTORY>();
            this.C_COMP_PROCESS_MONITOR = new HashSet<C_COMP_PROCESS_MONITOR>();
        }
    
        public string UUID { get; set; }
        public string MASTER_ID { get; set; }
        public string APPLICANT_ID { get; set; }
        public string APPLICANT_ROLE_ID { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public Nullable<System.DateTime> REMOVAL_DATE { get; set; }
        public Nullable<int> CANDIDATE_NUMBER { get; set; }
        public string LAST_INTERVIEW_NUMBER { get; set; }
        public string LAST_ASSESSMENT_NUMBER { get; set; }
        public string VETTING_STATUS { get; set; }
        public string FILE_PATH_RESTRICTED { get; set; }
        public string APPLICANT_STATUS_ID { get; set; }
        public string FILE_PATH_NONRESTRICTED { get; set; }
        public Nullable<System.DateTime> INTERVIEW_REFUSAL_DATE { get; set; }
        public Nullable<System.DateTime> INTERVIEW_WITHDRAWN_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string SUPPORTED_BY_ID { get; set; }
        public string CORRESPONDENCE_LANG_ID { get; set; }
        public Nullable<System.DateTime> CARD_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> CARD_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> CARD_RETURN_DATE { get; set; }
        public string CARD_SERIAL_NO { get; set; }
        public string OFFICE_TEL { get; set; }
        public string MOBILE_TEL { get; set; }
        public string RES_TEL { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string RES_ADDRESS_E1 { get; set; }
        public string RES_ADDRESS_E2 { get; set; }
        public string RES_ADDRESS_E3 { get; set; }
        public string RES_ADDRESS_E4 { get; set; }
        public string RES_ADDRESS_E5 { get; set; }
        public string RES_ADDRESS_C1 { get; set; }
        public string RES_ADDRESS_C2 { get; set; }
        public string RES_ADDRESS_C3 { get; set; }
        public string RES_ADDRESS_C4 { get; set; }
        public string RES_ADDRESS_C5 { get; set; }
    
        public virtual C_APPLICANT C_APPLICANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO> C_COMP_APPLICANT_INFO1 { get; set; }
        public virtual C_COMP_APPLICANT_INFO C_COMP_APPLICANT_INFO2 { get; set; }
        public virtual C_COMP_APPLICATION C_COMP_APPLICATION { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_HISTORY> C_COMP_APPLICANT_INFO_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_MASTER> C_COMP_APPLICANT_INFO_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_MW_ITEM> C_COMP_APPLICANT_MW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_LEAVE_FORM> C_LEAVE_FORM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLN_MW_ITEM_HISTORY> C_COMP_APPLN_MW_ITEM_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_PROCESS_MONITOR> C_COMP_PROCESS_MONITOR { get; set; }
    }
}
