//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMP_APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_COMP_APPLICATION()
        {
            this.C_COMP_APPLICANT_INFO = new HashSet<C_COMP_APPLICANT_INFO>();
            this.C_COMP_APPLICATION_HISTORY = new HashSet<C_COMP_APPLICATION_HISTORY>();
            this.C_COMP_PROCESS_MONITOR = new HashSet<C_COMP_PROCESS_MONITOR>();
            this.C_COMP_APPLICATION_MW_ITEM = new HashSet<C_COMP_APPLICATION_MW_ITEM>();
            this.C_POOLING = new HashSet<C_POOLING>();
        }
    
        public string UUID { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public string FILE_REFERENCE_NO { get; set; }
        public string CERTIFICATION_NO { get; set; }
        public string BR_NO { get; set; }
        public string BRANCH_NO { get; set; }
        public string OLD_FILE_REFERENCE { get; set; }
        public string CATEGORY_ID { get; set; }
        public string ENGLISH_COMPANY_NAME { get; set; }
        public string CHINESE_COMPANY_NAME { get; set; }
        public string APPLICANT_NAME { get; set; }
        public string COMPANY_TYPE_ID { get; set; }
        public string ENGLISH_CARE_OF { get; set; }
        public string CHINESE_CARE_OF { get; set; }
        public string ENGLISH_ADDRESS_ID { get; set; }
        public string CHINESE_ADDRESS_ID { get; set; }
        public string PERIOD_OF_VALIDITY_ID { get; set; }
        public string APPLICATION_FORM_ID { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> GAZETTE_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> RESTORE_DATE { get; set; }
        public Nullable<System.DateTime> RESTORATION_APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> RETENTION_DATE { get; set; }
        public Nullable<System.DateTime> RETENTION_APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> SUSPENSION_DATE { get; set; }
        public Nullable<System.DateTime> REMOVAL_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> DOCUMENT_MAIL_DATE { get; set; }
        public string MISS_DOCUMENT_TYPE { get; set; }
        public Nullable<System.DateTime> VETTING_DATE { get; set; }
        public string TELEPHONE_NO1 { get; set; }
        public string TELEPHONE_NO2 { get; set; }
        public string TELEPHONE_NO3 { get; set; }
        public string FAX_NO1 { get; set; }
        public string FAX_NO2 { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string PROSECUTION_DISCIPLINARY_REC { get; set; }
        public string IS_PUBLIC_INFO { get; set; }
        public string PRACTICE_NOTES_ID { get; set; }
        public string ENGLISH_BS_ADDRESS_ID { get; set; }
        public string CHINESE_BS_ADDRESS_ID { get; set; }
        public string BS_TELEPHONE_NO1 { get; set; }
        public string BS_FAX_NO1 { get; set; }
        public string ENGLISH_BS_CARE_OF { get; set; }
        public string CHINESE_BS_CARE_OF { get; set; }
        public string APPLICATION_STATUS_ID { get; set; }
        public Nullable<System.DateTime> EXTEND_DATE { get; set; }
        public string REGION_CODE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string CORRESPONDENCE_LANG_ID { get; set; }
        public string BS_EMAIL_ADDRESS { get; set; }
        public string BS_REGION_CODE_ID { get; set; }
        public string WILLINGNESS_QP { get; set; }
        public Nullable<System.DateTime> WILLINGNESS_QP_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string DUE_DATE_CLASS { get; set; }
        public Nullable<System.DateTime> FIRST_APPLICATION_DATE { get; set; }
        public string INTERESTED_FSS { get; set; }
        public Nullable<System.DateTime> INTERESTED_FSS_DATE { get; set; }
        public string SERVICE_IN_MWIS { get; set; }
    
        public virtual C_ADDRESS C_ADDRESS { get; set; }
        public virtual C_ADDRESS C_ADDRESS1 { get; set; }
        public virtual C_ADDRESS C_ADDRESS2 { get; set; }
        public virtual C_ADDRESS C_ADDRESS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO> C_COMP_APPLICANT_INFO { get; set; }
        public virtual C_S_CATEGORY_CODE C_S_CATEGORY_CODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_HISTORY> C_COMP_APPLICATION_HISTORY { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE1 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE2 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE3 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE4 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE5 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_PROCESS_MONITOR> C_COMP_PROCESS_MONITOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_MW_ITEM> C_COMP_APPLICATION_MW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_POOLING> C_POOLING { get; set; }
    }
}
