//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMMITTEE_PANEL_MEMBER
    {
        public string UUID { get; set; }
        public string COMMITTEE_PANEL_ID { get; set; }
        public string MEMBER_ID { get; set; }
        public string PANEL_ROLE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string MEMBER_STATUS_ID { get; set; }
        public Nullable<System.DateTime> TERMINATED_DATE { get; set; }
    
        public virtual C_COMMITTEE_MEMBER C_COMMITTEE_MEMBER { get; set; }
        public virtual C_COMMITTEE_PANEL C_COMMITTEE_PANEL { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE1 { get; set; }
    }
}
