//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INTERVIEW_CANDIDATES
    {
        public string UUID { get; set; }
        public string INTERVIEW_SCHEDULE_ID { get; set; }
        public int CANDIDATE_NUMBER { get; set; }
        public string MEETING_NUMBER { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public string IS_ABSENT { get; set; }
        public string REMARKS { get; set; }
        public string RESULT_ID { get; set; }
        public Nullable<System.DateTime> RESULT_DATE { get; set; }
        public string INTERVIEW_TYPE { get; set; }
        public string INTERVIEW_NUMBER { get; set; }
        public string ASSESSMENT_NUMBER { get; set; }
        public string ALIAS_NUMBER { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string ASSESSMENT_RES_PATH { get; set; }
        public string MW_APPLY { get; set; }
        public string MW_APPROVED { get; set; }
    
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_INTERVIEW_SCHEDULE C_INTERVIEW_SCHEDULE { get; set; }
    }
}
