//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IND_CERTIFICATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_IND_CERTIFICATE()
        {
            this.C_IND_CERTIFICATE_HISTORY = new HashSet<C_IND_CERTIFICATE_HISTORY>();
        }
    
        public string UUID { get; set; }
        public string MASTER_ID { get; set; }
        public string CATEGORY_ID { get; set; }
        public string CERTIFICATION_NO { get; set; }
        public string PERIOD_OF_VALIDITY_ID { get; set; }
        public Nullable<System.DateTime> EXTENDED_DATE { get; set; }
        public Nullable<System.DateTime> GAZETTE_DATE { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> SUSPENSION_DATE { get; set; }
        public Nullable<System.DateTime> REMOVAL_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> RESTORE_DATE { get; set; }
        public Nullable<System.DateTime> RESTORATION_APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> RETENTION_DATE { get; set; }
        public Nullable<System.DateTime> RETENTION_APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public string APPLICATION_FORM_ID { get; set; }
        public Nullable<long> CANDIDATE_NUMBER { get; set; }
        public string APPLICATION_STATUS_ID { get; set; }
        public Nullable<System.DateTime> DOCUMENT_MAIL_DATE { get; set; }
        public string MISS_DOCUMENT_TYPE { get; set; }
        public Nullable<System.DateTime> VETTING_DATE { get; set; }
        public string USE_OLD_CATEGORY_CODE { get; set; }
        public string FILE_PATH_NONRESTRICTED { get; set; }
        public string FILE_PATH_RESTRICTED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> CARD_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> CARD_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> CARD_RETURN_DATE { get; set; }
        public string CARD_SERIAL_NO { get; set; }
        public Nullable<System.DateTime> CARD_APP_DATE { get; set; }
        public string QP_ADDRESS_E1 { get; set; }
        public string QP_ADDRESS_E2 { get; set; }
        public string QP_ADDRESS_E3 { get; set; }
        public string QP_ADDRESS_E4 { get; set; }
        public string QP_ADDRESS_E5 { get; set; }
        public string QP_ADDRESS_C1 { get; set; }
        public string QP_ADDRESS_C2 { get; set; }
        public string QP_ADDRESS_C3 { get; set; }
        public string QP_ADDRESS_C4 { get; set; }
        public string QP_ADDRESS_C5 { get; set; }
    
        public virtual C_IND_APPLICATION C_IND_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE_HISTORY> C_IND_CERTIFICATE_HISTORY { get; set; }
        public virtual C_S_CATEGORY_CODE C_S_CATEGORY_CODE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE1 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE2 { get; set; }
    }
}
