//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IND_APPLICATION_MW_ITEM_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_IND_APPLICATION_MW_ITEM_MASTER()
        {
            this.C_IND_APPLICATION_MW_ITEM_DETAIL = new HashSet<C_IND_APPLICATION_MW_ITEM_DETAIL>();
        }
    
        public string UUID { get; set; }
        public string MASTER_ID { get; set; }
        public string APPLICATION_FORM_ID { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string SV_MWITEM_VERSION_ID { get; set; }
        public string ITEM_REMOVE { get; set; }
    
        public virtual C_IND_APPLICATION C_IND_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM_DETAIL> C_IND_APPLICATION_MW_ITEM_DETAIL { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
