//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IND_PROCESS_MONITOR
    {
        public string UUID { get; set; }
        public string MASTER_ID { get; set; }
        public string CATEGORY_ID { get; set; }
        public string CATEGORY_GROUP_ID { get; set; }
        public string AUDIT_TEXT { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> REFERENCE_ASK_DATE { get; set; }
        public Nullable<System.DateTime> REFERENCE_REPLY_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATION_ASK_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATION_REPLY_DATE { get; set; }
        public Nullable<System.DateTime> INTERVIEW_NOTIFY_DATE { get; set; }
        public Nullable<System.DateTime> INTERVIEW_DATE { get; set; }
        public Nullable<System.DateTime> RESULT_ACCEPT_DATE { get; set; }
        public Nullable<System.DateTime> RESULT_DEFER_DATE { get; set; }
        public Nullable<System.DateTime> RESULT_REFUSE_DATE { get; set; }
        public Nullable<System.DateTime> SUPPLE_DOCUMENT_DATE { get; set; }
        public Nullable<System.DateTime> DEFER_DATE { get; set; }
        public Nullable<System.DateTime> GAZETTE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string VETTING_OFFICER { get; set; }
        public Nullable<System.DateTime> WITHDRAWAL_DATE { get; set; }
        public Nullable<System.DateTime> NOTIFICATION_LETTER_DUEDATE { get; set; }
        public Nullable<System.DateTime> INTERVIEW_DUEDATE { get; set; }
        public Nullable<System.DateTime> REMOVAL_DATE { get; set; }
        public string APPLICATION_FORM_ID { get; set; }
        public Nullable<System.DateTime> OS_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string APPLY_STATUS { get; set; }
    
        public virtual C_IND_APPLICATION C_IND_APPLICATION { get; set; }
        public virtual C_S_CATEGORY_CODE C_S_CATEGORY_CODE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE1 { get; set; }
    }
}
