//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INTERVIEW_SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_INTERVIEW_SCHEDULE()
        {
            this.C_INTERVIEW_CANDIDATES = new HashSet<C_INTERVIEW_CANDIDATES>();
        }
    
        public string UUID { get; set; }
        public System.DateTime INTERVIEW_DATE { get; set; }
        public string TIME_SESSION_ID { get; set; }
        public string ROOM_ID { get; set; }
        public string MEETING_NUMBER { get; set; }
        public string REPORT_TO { get; set; }
        public string IS_CANCEL { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MEETING_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_INTERVIEW_CANDIDATES> C_INTERVIEW_CANDIDATES { get; set; }
        public virtual C_MEETING C_MEETING { get; set; }
        public virtual C_S_ROOM C_S_ROOM { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
