//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LEAVE_FORM
    {
        public string UUID { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public string MASTER_ID { get; set; }
        public string COMPANY_APPLICANT_ID { get; set; }
        public string FILE_PATH_BA21 { get; set; }
        public string FILE_PATH_REPLACEMENT { get; set; }
        public string FILE_PATH_LEAVE { get; set; }
        public string FILE_PATH_CANCELLATION { get; set; }
        public string IS_CANCEL { get; set; }
        public string CERTIFICATION_NO { get; set; }
        public Nullable<System.DateTime> LEAVE_END_DATE { get; set; }
        public Nullable<System.DateTime> LEAVE_START_DATE { get; set; }
        public string RECORD_TYPE { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_COMP_APPLICANT_INFO C_COMP_APPLICANT_INFO { get; set; }
    }
}
