//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MEETING_MEMBER
    {
        public string UUID { get; set; }
        public string MEETING_ID { get; set; }
        public string MEMBER_ID { get; set; }
        public string COMMITTEE_ROLE_ID { get; set; }
        public string IS_ABSENT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_COMMITTEE_MEMBER C_COMMITTEE_MEMBER { get; set; }
        public virtual C_MEETING C_MEETING { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
