//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_QP_CARD_HISTORY
    {
        public string UUID { get; set; }
        public string HKID { get; set; }
        public string PASSPORT_NO { get; set; }
        public string CARD_SERIAL_NO { get; set; }
        public Nullable<System.DateTime> CARD_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> CARD_EXPIRY_DATE { get; set; }
        public string QP_REGISTRATION { get; set; }
        public Nullable<System.DateTime> CARD_RETURN_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
