//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_REPORT_RPR
    {
        public decimal RPT_ID { get; set; }
        public string RPT_KEY { get; set; }
        public string FILE_REFERENCE_NO { get; set; }
        public string NAME { get; set; }
        public string HKID { get; set; }
        public string CATEGORY { get; set; }
        public string CLASS { get; set; }
        public string MTYPE { get; set; }
        public string ROLE { get; set; }
        public string LINE_NO { get; set; }
        public string ITEM { get; set; }
        public string AREA { get; set; }
        public string DISCIPLINES { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string ESTATUS { get; set; }
    }
}
