//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_S_CATEGORY_CODE_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_S_CATEGORY_CODE_DETAIL()
        {
            this.C_IND_QUALIFICATION_DETAIL = new HashSet<C_IND_QUALIFICATION_DETAIL>();
        }
    
        public string UUID { get; set; }
        public string S_CATEGORY_CODE_ID { get; set; }
        public string CODE { get; set; }
        public string ENGLISH_DESCRIPTION { get; set; }
        public string CHINESE_DESCRIPTION { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_QUALIFICATION_DETAIL> C_IND_QUALIFICATION_DETAIL { get; set; }
        public virtual C_S_CATEGORY_CODE C_S_CATEGORY_CODE { get; set; }
    }
}
