//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_S_SYSTEM_VALUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_S_SYSTEM_VALUE()
        {
            this.C_APPLICANT = new HashSet<C_APPLICANT>();
            this.C_BUILDING_SAFETY_INFO = new HashSet<C_BUILDING_SAFETY_INFO>();
            this.C_COMMITTEE = new HashSet<C_COMMITTEE>();
            this.C_COMMITTEE_COMMITTEE_MEMBER = new HashSet<C_COMMITTEE_COMMITTEE_MEMBER>();
            this.C_COMMITTEE_GROUP = new HashSet<C_COMMITTEE_GROUP>();
            this.C_COMMITTEE_GROUP_MEMBER = new HashSet<C_COMMITTEE_GROUP_MEMBER>();
            this.C_COMMITTEE_MEMBER_INSTITUTE = new HashSet<C_COMMITTEE_MEMBER_INSTITUTE>();
            this.C_COMMITTEE_PANEL = new HashSet<C_COMMITTEE_PANEL>();
            this.C_COMMITTEE_PANEL_MEMBER = new HashSet<C_COMMITTEE_PANEL_MEMBER>();
            this.C_COMMITTEE_PANEL_MEMBER1 = new HashSet<C_COMMITTEE_PANEL_MEMBER>();
            this.C_COMP_APPLICANT_INFO = new HashSet<C_COMP_APPLICANT_INFO>();
            this.C_COMP_APPLICANT_INFO1 = new HashSet<C_COMP_APPLICANT_INFO>();
            this.C_COMP_APPLICANT_INFO_DETAIL = new HashSet<C_COMP_APPLICANT_INFO_DETAIL>();
            this.C_COMP_APPLICANT_INFO_DETAIL1 = new HashSet<C_COMP_APPLICANT_INFO_DETAIL>();
            this.C_COMP_APPLICANT_INFO_HISTORY = new HashSet<C_COMP_APPLICANT_INFO_HISTORY>();
            this.C_COMP_APPLICANT_INFO_MASTER = new HashSet<C_COMP_APPLICANT_INFO_MASTER>();
            this.C_COMP_APPLICANT_MW_ITEM = new HashSet<C_COMP_APPLICANT_MW_ITEM>();
            this.C_COMP_APPLICANT_MW_ITEM1 = new HashSet<C_COMP_APPLICANT_MW_ITEM>();
            this.C_COMP_APPLICATION = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION1 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION2 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION3 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION4 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION5 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION6 = new HashSet<C_COMP_APPLICATION>();
            this.C_COMP_APPLICATION_HISTORY = new HashSet<C_COMP_APPLICATION_HISTORY>();
            this.C_COMP_APPLICATION_HISTORY1 = new HashSet<C_COMP_APPLICATION_HISTORY>();
            this.C_COMP_APPLICATION_MW_ITEM = new HashSet<C_COMP_APPLICATION_MW_ITEM>();
            this.C_COMP_APPLICATION_MW_ITEM1 = new HashSet<C_COMP_APPLICATION_MW_ITEM>();
            this.C_COMP_APPLN_MW_ITEM_HISTORY = new HashSet<C_COMP_APPLN_MW_ITEM_HISTORY>();
            this.C_COMP_APPLN_MW_ITEM_HISTORY1 = new HashSet<C_COMP_APPLN_MW_ITEM_HISTORY>();
            this.C_COMP_CONVICTION = new HashSet<C_COMP_CONVICTION>();
            this.C_COMP_CONVICTION1 = new HashSet<C_COMP_CONVICTION>();
            this.C_COMP_PROCESS_MONITOR = new HashSet<C_COMP_PROCESS_MONITOR>();
            this.C_COMP_PROCESS_MONITOR1 = new HashSet<C_COMP_PROCESS_MONITOR>();
            this.C_IND_APPL_MW_ITEM_HISTORY = new HashSet<C_IND_APPL_MW_ITEM_HISTORY>();
            this.C_IND_APPL_MW_ITEM_HISTORY1 = new HashSet<C_IND_APPL_MW_ITEM_HISTORY>();
            this.C_IND_APPL_MW_ITEM_HISTORY2 = new HashSet<C_IND_APPL_MW_ITEM_HISTORY>();
            this.C_IND_APPLICATION = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION1 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION2 = new HashSet<C_IND_APPLICATION>();
            this.C_IND_APPLICATION_MW_ITEM = new HashSet<C_IND_APPLICATION_MW_ITEM>();
            this.C_IND_APPLICATION_MW_ITEM1 = new HashSet<C_IND_APPLICATION_MW_ITEM>();
            this.C_IND_APPLICATION_MW_ITEM2 = new HashSet<C_IND_APPLICATION_MW_ITEM>();
            this.C_IND_APPLICATION_MW_ITEM_DETAIL = new HashSet<C_IND_APPLICATION_MW_ITEM_DETAIL>();
            this.C_IND_APPLICATION_MW_ITEM_DETAIL1 = new HashSet<C_IND_APPLICATION_MW_ITEM_DETAIL>();
            this.C_IND_APPLICATION_MW_ITEM_DETAIL2 = new HashSet<C_IND_APPLICATION_MW_ITEM_DETAIL>();
            this.C_IND_APPLICATION_MW_ITEM_MASTER = new HashSet<C_IND_APPLICATION_MW_ITEM_MASTER>();
            this.C_IND_CERTIFICATE = new HashSet<C_IND_CERTIFICATE>();
            this.C_IND_CERTIFICATE1 = new HashSet<C_IND_CERTIFICATE>();
            this.C_IND_CERTIFICATE2 = new HashSet<C_IND_CERTIFICATE>();
            this.C_IND_CERTIFICATE_HISTORY = new HashSet<C_IND_CERTIFICATE_HISTORY>();
            this.C_IND_CERTIFICATE_HISTORY1 = new HashSet<C_IND_CERTIFICATE_HISTORY>();
            this.C_IND_CERTIFICATE_HISTORY2 = new HashSet<C_IND_CERTIFICATE_HISTORY>();
            this.C_IND_CONVICTION = new HashSet<C_IND_CONVICTION>();
            this.C_IND_CONVICTION1 = new HashSet<C_IND_CONVICTION>();
            this.C_IND_PROCESS_MONITOR = new HashSet<C_IND_PROCESS_MONITOR>();
            this.C_IND_PROCESS_MONITOR1 = new HashSet<C_IND_PROCESS_MONITOR>();
            this.C_IND_QUALIFICATION = new HashSet<C_IND_QUALIFICATION>();
            this.C_IND_QUALIFICATION1 = new HashSet<C_IND_QUALIFICATION>();
            this.C_INTERVIEW_CANDIDATES = new HashSet<C_INTERVIEW_CANDIDATES>();
            this.C_INTERVIEW_SCHEDULE = new HashSet<C_INTERVIEW_SCHEDULE>();
            this.C_MEETING = new HashSet<C_MEETING>();
            this.C_MEETING_MEMBER = new HashSet<C_MEETING_MEMBER>();
            this.C_MEMBER_CATEGORY = new HashSet<C_MEMBER_CATEGORY>();
            this.C_S_AUTHORITY = new HashSet<C_S_AUTHORITY>();
            this.C_S_BUILDING_SAFETY_ITEM = new HashSet<C_S_BUILDING_SAFETY_ITEM>();
            this.C_S_CATEGORY_CODE = new HashSet<C_S_CATEGORY_CODE>();
            this.C_S_HTML_NOTES = new HashSet<C_S_HTML_NOTES>();
            this.C_S_SEARCH_LEVEL = new HashSet<C_S_SEARCH_LEVEL>();
            this.C_S_SYSTEM_VALUE1 = new HashSet<C_S_SYSTEM_VALUE>();
            this.C_S_USER_GROUP_CONV_INFO = new HashSet<C_S_USER_GROUP_CONV_INFO>();
        }
    
        public string UUID { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public string SYSTEM_TYPE_ID { get; set; }
        public string CODE { get; set; }
        public string PARENT_ID { get; set; }
        public string ENGLISH_DESCRIPTION { get; set; }
        public string CHINESE_DESCRIPTION { get; set; }
        public string IS_ACTIVE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string SV_MWITEM_VERSION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_APPLICANT> C_APPLICANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BUILDING_SAFETY_INFO> C_BUILDING_SAFETY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE> C_COMMITTEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_COMMITTEE_MEMBER> C_COMMITTEE_COMMITTEE_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_GROUP> C_COMMITTEE_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_GROUP_MEMBER> C_COMMITTEE_GROUP_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_MEMBER_INSTITUTE> C_COMMITTEE_MEMBER_INSTITUTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_PANEL> C_COMMITTEE_PANEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_PANEL_MEMBER> C_COMMITTEE_PANEL_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMMITTEE_PANEL_MEMBER> C_COMMITTEE_PANEL_MEMBER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO> C_COMP_APPLICANT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO> C_COMP_APPLICANT_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_DETAIL> C_COMP_APPLICANT_INFO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_DETAIL> C_COMP_APPLICANT_INFO_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_HISTORY> C_COMP_APPLICANT_INFO_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_INFO_MASTER> C_COMP_APPLICANT_INFO_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_MW_ITEM> C_COMP_APPLICANT_MW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICANT_MW_ITEM> C_COMP_APPLICANT_MW_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION> C_COMP_APPLICATION6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_HISTORY> C_COMP_APPLICATION_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_HISTORY> C_COMP_APPLICATION_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_MW_ITEM> C_COMP_APPLICATION_MW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLICATION_MW_ITEM> C_COMP_APPLICATION_MW_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLN_MW_ITEM_HISTORY> C_COMP_APPLN_MW_ITEM_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_APPLN_MW_ITEM_HISTORY> C_COMP_APPLN_MW_ITEM_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_CONVICTION> C_COMP_CONVICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_CONVICTION> C_COMP_CONVICTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_PROCESS_MONITOR> C_COMP_PROCESS_MONITOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_COMP_PROCESS_MONITOR> C_COMP_PROCESS_MONITOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPL_MW_ITEM_HISTORY> C_IND_APPL_MW_ITEM_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPL_MW_ITEM_HISTORY> C_IND_APPL_MW_ITEM_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPL_MW_ITEM_HISTORY> C_IND_APPL_MW_ITEM_HISTORY2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION> C_IND_APPLICATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM> C_IND_APPLICATION_MW_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM> C_IND_APPLICATION_MW_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM> C_IND_APPLICATION_MW_ITEM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM_DETAIL> C_IND_APPLICATION_MW_ITEM_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM_DETAIL> C_IND_APPLICATION_MW_ITEM_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM_DETAIL> C_IND_APPLICATION_MW_ITEM_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_APPLICATION_MW_ITEM_MASTER> C_IND_APPLICATION_MW_ITEM_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE> C_IND_CERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE> C_IND_CERTIFICATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE> C_IND_CERTIFICATE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE_HISTORY> C_IND_CERTIFICATE_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE_HISTORY> C_IND_CERTIFICATE_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CERTIFICATE_HISTORY> C_IND_CERTIFICATE_HISTORY2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CONVICTION> C_IND_CONVICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_CONVICTION> C_IND_CONVICTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_PROCESS_MONITOR> C_IND_PROCESS_MONITOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_PROCESS_MONITOR> C_IND_PROCESS_MONITOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_QUALIFICATION> C_IND_QUALIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_IND_QUALIFICATION> C_IND_QUALIFICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_INTERVIEW_CANDIDATES> C_INTERVIEW_CANDIDATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_INTERVIEW_SCHEDULE> C_INTERVIEW_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_MEETING> C_MEETING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_MEETING_MEMBER> C_MEETING_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_MEMBER_CATEGORY> C_MEMBER_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_AUTHORITY> C_S_AUTHORITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_BUILDING_SAFETY_ITEM> C_S_BUILDING_SAFETY_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_CATEGORY_CODE> C_S_CATEGORY_CODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_HTML_NOTES> C_S_HTML_NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_SEARCH_LEVEL> C_S_SEARCH_LEVEL { get; set; }
        public virtual C_S_SYSTEM_TYPE C_S_SYSTEM_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_SYSTEM_VALUE> C_S_SYSTEM_VALUE1 { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_S_USER_GROUP_CONV_INFO> C_S_USER_GROUP_CONV_INFO { get; set; }
    }
}
