//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_S_BUILDING_SAFETY_ITEM
    {
        public string UUID { get; set; }
        public string BUILDING_SAFETY_ID { get; set; }
        public string CATEGORY_ID { get; set; }
        public string CHINESE_HTML_HEADER { get; set; }
        public string ENGLISH_HTML_HEADER { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_S_CATEGORY_CODE C_S_CATEGORY_CODE { get; set; }
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
