//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_S_MW_IND_CAPA_MAIN
    {
        public string UUID { get; set; }
        public string S_MW_IND_CAPA_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string SHOW_BOX { get; set; }
        public string SELECTED { get; set; }
        public string CHECKBOX_CODE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_S_MW_IND_CAPA C_S_MW_IND_CAPA { get; set; }
    }
}
