//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_S_AUTHORITY
    {
        public string UUID { get; set; }
        public string CATEGORY_GROUP_ID { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string ENGLISH_RANK { get; set; }
        public string CHINESE_RANK { get; set; }
        public string TELEPHONE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string ENGLISH_ACTION_NAME { get; set; }
        public string CHINESE_ACTION_NAME { get; set; }
        public string ENGLISH_ACTION_RANK { get; set; }
        public string CHINESE_ACTION_RANK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual C_S_SYSTEM_VALUE C_S_SYSTEM_VALUE { get; set; }
    }
}
