//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VQPEXPORT
    {
        public string CERTIFICATION_NO { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string ENGLISH_LINE1 { get; set; }
        public string ENGLISH_LINE2 { get; set; }
        public string ENGLISH_LINE3 { get; set; }
        public string ENGLISH_LINE4 { get; set; }
        public string ENGLISH_LINE5 { get; set; }
        public string CHINESE_LINE1 { get; set; }
        public string CHINESE_LINE2 { get; set; }
        public string CHINESE_LINE3 { get; set; }
        public string CHINESE_LINE4 { get; set; }
        public string CHINESE_LINE5 { get; set; }
        public string FAX_NO1 { get; set; }
        public string FAX_NO2 { get; set; }
    }
}
