//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EntitiesAddress : EntityFilter
    {
        public EntitiesAddress() : base("name=EntitiesAddress")
        {
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MWMS_ADDRESS_META_DATA> MWMS_ADDRESS_META_DATA { get; set; }
        public virtual DbSet<MWMS_BLK> MWMS_BLK { get; set; }
        public virtual DbSet<MWMS_BLK_FILEREF> MWMS_BLK_FILEREF { get; set; }
        public virtual DbSet<MWMS_BLK_SL> MWMS_BLK_SL { get; set; }
        public virtual DbSet<MWMS_DISTRICT> MWMS_DISTRICT { get; set; }
        public virtual DbSet<MWMS_ST_LOC> MWMS_ST_LOC { get; set; }
        public virtual DbSet<MWMS_ST_NAME> MWMS_ST_NAME { get; set; }
        public virtual DbSet<MWMS_UNIT> MWMS_UNIT { get; set; }
    }
}
