//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EntitiesSignboard : EntityFilter
    {
        public EntitiesSignboard()
           : base("name=EntitiesSBConnection")
        {
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_CRM_PBP_PRC> B_CRM_PBP_PRC { get; set; }
        public virtual DbSet<B_CRM_PBP_PRC_CAPACITY> B_CRM_PBP_PRC_CAPACITY { get; set; }
        public virtual DbSet<B_EFSS_ATTACHMENT_LIST> B_EFSS_ATTACHMENT_LIST { get; set; }
        public virtual DbSet<B_EFSS_SC01> B_EFSS_SC01 { get; set; }
        public virtual DbSet<B_EFSS_SC01_MW_ITEM> B_EFSS_SC01_MW_ITEM { get; set; }
        public virtual DbSet<B_EFSS_SC01_VALIDATION> B_EFSS_SC01_VALIDATION { get; set; }
        public virtual DbSet<B_EFSS_SC01C> B_EFSS_SC01C { get; set; }
        public virtual DbSet<B_EFSS_SC01C_MW_ITEM> B_EFSS_SC01C_MW_ITEM { get; set; }
        public virtual DbSet<B_EFSS_SC01C_VALIDATION> B_EFSS_SC01C_VALIDATION { get; set; }
        public virtual DbSet<B_EFSS_SC02> B_EFSS_SC02 { get; set; }
        public virtual DbSet<B_EFSS_SC02_MW_ITEM> B_EFSS_SC02_MW_ITEM { get; set; }
        public virtual DbSet<B_EFSS_SC02_VALIDATION> B_EFSS_SC02_VALIDATION { get; set; }
        public virtual DbSet<B_EFSS_SC02C> B_EFSS_SC02C { get; set; }
        public virtual DbSet<B_EFSS_SC02C_MW_ITEM> B_EFSS_SC02C_MW_ITEM { get; set; }
        public virtual DbSet<B_EFSS_SC02C_VALIDATION> B_EFSS_SC02C_VALIDATION { get; set; }
        public virtual DbSet<B_EFSS_SC03> B_EFSS_SC03 { get; set; }
        public virtual DbSet<B_EFSS_SC03_MW_ITEM> B_EFSS_SC03_MW_ITEM { get; set; }
        public virtual DbSet<B_EFSS_SC03_VALIDATION> B_EFSS_SC03_VALIDATION { get; set; }
        public virtual DbSet<B_RV_BLOCK> B_RV_BLOCK { get; set; }
        public virtual DbSet<B_RV_BUILDING> B_RV_BUILDING { get; set; }
        public virtual DbSet<B_RV_DEVELOPMENT_NAME> B_RV_DEVELOPMENT_NAME { get; set; }
        public virtual DbSet<B_RV_LOCATION_NAME> B_RV_LOCATION_NAME { get; set; }
        public virtual DbSet<B_RV_NEW_DISTRICT> B_RV_NEW_DISTRICT { get; set; }
        public virtual DbSet<B_RV_STREET_LOCATION> B_RV_STREET_LOCATION { get; set; }
        public virtual DbSet<B_RV_STREET_NAME> B_RV_STREET_NAME { get; set; }
        public virtual DbSet<B_RV_TENEMENT> B_RV_TENEMENT { get; set; }
        public virtual DbSet<B_RV_UNIT> B_RV_UNIT { get; set; }
        public virtual DbSet<B_RVD> B_RVD { get; set; }
        public virtual DbSet<B_S_AUDIT_CHECK_PERCENTAGE> B_S_AUDIT_CHECK_PERCENTAGE { get; set; }
        public virtual DbSet<B_S_LETTER_TEMPLATE> B_S_LETTER_TEMPLATE { get; set; }
        public virtual DbSet<B_S_MW_ITEM_CHECKLIST_ITEM> B_S_MW_ITEM_CHECKLIST_ITEM { get; set; }
        public virtual DbSet<B_S_PARAMETER> B_S_PARAMETER { get; set; }
        public virtual DbSet<B_S_SYSTEM_TYPE> B_S_SYSTEM_TYPE { get; set; }
        public virtual DbSet<B_S_SYSTEM_VALUE> B_S_SYSTEM_VALUE { get; set; }
        public virtual DbSet<B_SV_24_ORDER> B_SV_24_ORDER { get; set; }
        public virtual DbSet<B_SV_ADDRESS> B_SV_ADDRESS { get; set; }
        public virtual DbSet<B_SV_APPOINTED_PROFESSIONAL> B_SV_APPOINTED_PROFESSIONAL { get; set; }
        public virtual DbSet<B_SV_AUDIT_RECORD> B_SV_AUDIT_RECORD { get; set; }
        public virtual DbSet<B_SV_COMMENT> B_SV_COMMENT { get; set; }
        public virtual DbSet<B_SV_COMPLAIN> B_SV_COMPLAIN { get; set; }
        public virtual DbSet<B_SV_GC> B_SV_GC { get; set; }
        public virtual DbSet<B_SV_PERSON_CONTACT> B_SV_PERSON_CONTACT { get; set; }
        public virtual DbSet<B_SV_PHOTO_LIBRARY> B_SV_PHOTO_LIBRARY { get; set; }
        public virtual DbSet<B_SV_RECORD> B_SV_RECORD { get; set; }
        public virtual DbSet<B_SV_RECORD_ADDRESS_INFO> B_SV_RECORD_ADDRESS_INFO { get; set; }
        public virtual DbSet<B_SV_RECORD_FORM_CHECKLIST> B_SV_RECORD_FORM_CHECKLIST { get; set; }
        public virtual DbSet<B_SV_RECORD_ITEM> B_SV_RECORD_ITEM { get; set; }
        public virtual DbSet<B_SV_RECORD_ITEM_CHECKLIST> B_SV_RECORD_ITEM_CHECKLIST { get; set; }
        public virtual DbSet<B_SV_RECORD_ITEM_CHECKLIST_ITEM> B_SV_RECORD_ITEM_CHECKLIST_ITEM { get; set; }
        public virtual DbSet<B_SV_RECORD_VALIDATION_ITEM> B_SV_RECORD_VALIDATION_ITEM { get; set; }
        public virtual DbSet<B_SV_REFERENCE_NO> B_SV_REFERENCE_NO { get; set; }
        public virtual DbSet<B_SV_RFID> B_SV_RFID { get; set; }
        public virtual DbSet<B_SV_RV_ADDRESS> B_SV_RV_ADDRESS { get; set; }
        public virtual DbSet<B_SV_SCANNED_DOCUMENT> B_SV_SCANNED_DOCUMENT { get; set; }
        public virtual DbSet<B_SV_SIGNBOARD> B_SV_SIGNBOARD { get; set; }
        public virtual DbSet<B_SV_SIGNBOARD_RELATION> B_SV_SIGNBOARD_RELATION { get; set; }
        public virtual DbSet<B_SV_SUBMISSION> B_SV_SUBMISSION { get; set; }
        public virtual DbSet<B_SV_UPLOAD_LOG> B_SV_UPLOAD_LOG { get; set; }
        public virtual DbSet<B_SV_VALIDATION> B_SV_VALIDATION { get; set; }
        public virtual DbSet<B_WF_ASSIGNMENT> B_WF_ASSIGNMENT { get; set; }
        public virtual DbSet<B_WF_INFO> B_WF_INFO { get; set; }
        public virtual DbSet<B_WF_TASK> B_WF_TASK { get; set; }
        public virtual DbSet<B_WF_TASK_USER> B_WF_TASK_USER { get; set; }
        public virtual DbSet<B_S_SCU_TEAM> B_S_SCU_TEAM { get; set; }
        public virtual DbSet<B_S_TEAM> B_S_TEAM { get; set; }
        public virtual DbSet<B_EFSS_FORM_ATTACHMENTS> B_EFSS_FORM_ATTACHMENTS { get; set; }
        public virtual DbSet<B_EFSS_FORM_MASTER> B_EFSS_FORM_MASTER { get; set; }
        public virtual DbSet<B_EFSS_SUBMISSION_MAP> B_EFSS_SUBMISSION_MAP { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC01> B_EFSCU_TBL_SC01 { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC01_ITEM> B_EFSCU_TBL_SC01_ITEM { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC01C> B_EFSCU_TBL_SC01C { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC01C_ITEM> B_EFSCU_TBL_SC01C_ITEM { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC02> B_EFSCU_TBL_SC02 { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC02_ITEM> B_EFSCU_TBL_SC02_ITEM { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC02C> B_EFSCU_TBL_SC02C { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC02C_ITEM> B_EFSCU_TBL_SC02C_ITEM { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC03> B_EFSCU_TBL_SC03 { get; set; }
        public virtual DbSet<B_EFSCU_TBL_SC03_ITEM> B_EFSCU_TBL_SC03_ITEM { get; set; }
    }
}
