//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EntitiesWarningLetter : EntityFilter
    {
        public EntitiesWarningLetter()
                    : base("name=EntitiesWNConnection")
        {
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<W_WL> W_WL { get; set; }
        public virtual DbSet<W_S_OFFENSE_SCORE> W_S_OFFENSE_SCORE { get; set; }
        public virtual DbSet<W_S_SYSTEM_TYPE> W_S_SYSTEM_TYPE { get; set; }
        public virtual DbSet<W_S_SYSTEM_VALUE> W_S_SYSTEM_VALUE { get; set; }
        public virtual DbSet<W_WL_FILE> W_WL_FILE { get; set; }
        public virtual DbSet<W_WL_MW_ITEM> W_WL_MW_ITEM { get; set; }
        public virtual DbSet<W_WL_TYPE_OF_OFFENSE> W_WL_TYPE_OF_OFFENSE { get; set; }
    }
}
