//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMWProcessing : EntityFilter
    {
        public EntitiesMWProcessing()
            : base("name=EntitiesMWPConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_IMPORT_36> P_IMPORT_36 { get; set; }
        public virtual DbSet<P_IMPORT_36_ITEM> P_IMPORT_36_ITEM { get; set; }
        public virtual DbSet<P_LETTER_INFO> P_LETTER_INFO { get; set; }
        public virtual DbSet<P_MOD_BD106> P_MOD_BD106 { get; set; }
        public virtual DbSet<P_MOD_BD106_ITEM> P_MOD_BD106_ITEM { get; set; }
        public virtual DbSet<P_MW_A_LETTER> P_MW_A_LETTER { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER> P_MW_ACK_LETTER { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER_FREEZE_DETAIL> P_MW_ACK_LETTER_FREEZE_DETAIL { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER_FREEZE_MASTER> P_MW_ACK_LETTER_FREEZE_MASTER { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER_ITEM> P_MW_ACK_LETTER_ITEM { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER_PREAUDIT> P_MW_ACK_LETTER_PREAUDIT { get; set; }
        public virtual DbSet<P_MW_ACK_LETTER_REFERRAL> P_MW_ACK_LETTER_REFERRAL { get; set; }
        public virtual DbSet<P_MW_ADDRESS> P_MW_ADDRESS { get; set; }
        public virtual DbSet<P_MW_APPOINTED_PROF_ASSIGN> P_MW_APPOINTED_PROF_ASSIGN { get; set; }
        public virtual DbSet<P_MW_APPOINTED_PROF_HISTORY> P_MW_APPOINTED_PROF_HISTORY { get; set; }
        public virtual DbSet<P_MW_APPOINTED_PROFESSIONAL> P_MW_APPOINTED_PROFESSIONAL { get; set; }
        public virtual DbSet<P_MW_AUDIT_INSPECTION_RECORD> P_MW_AUDIT_INSPECTION_RECORD { get; set; }
        public virtual DbSet<P_MW_COMMENT> P_MW_COMMENT { get; set; }
        public virtual DbSet<P_MW_COMPLAINT_CHECKLIST> P_MW_COMPLAINT_CHECKLIST { get; set; }
        public virtual DbSet<P_MW_COMPLAINT_CHECKLIST_COMMENT> P_MW_COMPLAINT_CHECKLIST_COMMENT { get; set; }
        public virtual DbSet<P_MW_COMPLAINT_CHECKLIST_SECTION> P_MW_COMPLAINT_CHECKLIST_SECTION { get; set; }
        public virtual DbSet<P_MW_DECLARARTION> P_MW_DECLARARTION { get; set; }
        public virtual DbSet<P_MW_DIRECT_RETURN> P_MW_DIRECT_RETURN { get; set; }
        public virtual DbSet<P_MW_DIRECT_RETURN_IRREGULARITIES> P_MW_DIRECT_RETURN_IRREGULARITIES { get; set; }
        public virtual DbSet<P_MW_DSN> P_MW_DSN { get; set; }
        public virtual DbSet<P_MW_DW_LETTER> P_MW_DW_LETTER { get; set; }
        public virtual DbSet<P_MW_DW_LETTER_ITEM> P_MW_DW_LETTER_ITEM { get; set; }
        public virtual DbSet<P_MW_ENQUIRY_CHECKLIST> P_MW_ENQUIRY_CHECKLIST { get; set; }
        public virtual DbSet<P_MW_ENQUIRY_CHECKLIST_ITEM> P_MW_ENQUIRY_CHECKLIST_ITEM { get; set; }
        public virtual DbSet<P_MW_FORM> P_MW_FORM { get; set; }
        public virtual DbSet<P_MW_FORM_09> P_MW_FORM_09 { get; set; }
        public virtual DbSet<P_MW_GENERAL_RECORD> P_MW_GENERAL_RECORD { get; set; }
        public virtual DbSet<P_MW_GENERAL_RECORD_ACTION> P_MW_GENERAL_RECORD_ACTION { get; set; }
        public virtual DbSet<P_MW_GENERAL_RECORD_ADDRESS_INFO> P_MW_GENERAL_RECORD_ADDRESS_INFO { get; set; }
        public virtual DbSet<P_MW_GENERAL_RECORD_LETTER_INFO> P_MW_GENERAL_RECORD_LETTER_INFO { get; set; }
        public virtual DbSet<P_MW_GENERAL_RECORD_RELATED_CASE> P_MW_GENERAL_RECORD_RELATED_CASE { get; set; }
        public virtual DbSet<P_MW_IMPORT_XML> P_MW_IMPORT_XML { get; set; }
        public virtual DbSet<P_MW_IMPORTED_36_TASK> P_MW_IMPORTED_36_TASK { get; set; }
        public virtual DbSet<P_MW_IMPORTED_36_TASK_ITEM> P_MW_IMPORTED_36_TASK_ITEM { get; set; }
        public virtual DbSet<P_MW_IMPORTED_TASK> P_MW_IMPORTED_TASK { get; set; }
        public virtual DbSet<P_MW_IMPORTED_TASK_ITEM> P_MW_IMPORTED_TASK_ITEM { get; set; }
        public virtual DbSet<P_MW_ITEM_CHECKBOX> P_MW_ITEM_CHECKBOX { get; set; }
        public virtual DbSet<P_MW_MODIFICATION> P_MW_MODIFICATION { get; set; }
        public virtual DbSet<P_MW_MODIFICATION_NO> P_MW_MODIFICATION_NO { get; set; }
        public virtual DbSet<P_MW_MODIFICATION_RELATED_MWNO> P_MW_MODIFICATION_RELATED_MWNO { get; set; }
        public virtual DbSet<P_MW_PERSON_CONTACT> P_MW_PERSON_CONTACT { get; set; }
        public virtual DbSet<P_MW_RECORD> P_MW_RECORD { get; set; }
        public virtual DbSet<P_MW_RECORD_ADDRESS_INFO> P_MW_RECORD_ADDRESS_INFO { get; set; }
        public virtual DbSet<P_MW_RECORD_AUDIT> P_MW_RECORD_AUDIT { get; set; }
        public virtual DbSet<P_MW_RECORD_AUDIT_REFERRAL> P_MW_RECORD_AUDIT_REFERRAL { get; set; }
        public virtual DbSet<P_MW_RECORD_BLOCK> P_MW_RECORD_BLOCK { get; set; }
        public virtual DbSet<P_MW_RECORD_FORM_CHECKLIST> P_MW_RECORD_FORM_CHECKLIST { get; set; }
        public virtual DbSet<P_MW_RECORD_FORM_CHECKLIST_PO> P_MW_RECORD_FORM_CHECKLIST_PO { get; set; }
        public virtual DbSet<P_MW_RECORD_ITEM> P_MW_RECORD_ITEM { get; set; }
        public virtual DbSet<P_MW_RECORD_ITEM_CHECKLIST> P_MW_RECORD_ITEM_CHECKLIST { get; set; }
        public virtual DbSet<P_MW_RECORD_ITEM_CHECKLIST_ITEM> P_MW_RECORD_ITEM_CHECKLIST_ITEM { get; set; }
        public virtual DbSet<P_MW_RECORD_ITEM_HISTORY> P_MW_RECORD_ITEM_HISTORY { get; set; }
        public virtual DbSet<P_MW_RECORD_ITEM_INFO> P_MW_RECORD_ITEM_INFO { get; set; }
        public virtual DbSet<P_MW_RECORD_KEYWORD> P_MW_RECORD_KEYWORD { get; set; }
        public virtual DbSet<P_MW_RECORD_KEYWORD_TOBEDROP> P_MW_RECORD_KEYWORD_TOBEDROP { get; set; }
        public virtual DbSet<P_MW_RECORD_LETTER_INFO> P_MW_RECORD_LETTER_INFO { get; set; }
        public virtual DbSet<P_MW_RECORD_PSAC> P_MW_RECORD_PSAC { get; set; }
        public virtual DbSet<P_MW_RECORD_PSAC_IMAGE> P_MW_RECORD_PSAC_IMAGE { get; set; }
        public virtual DbSet<P_MW_RECORD_SAC> P_MW_RECORD_SAC { get; set; }
        public virtual DbSet<P_MW_REFERENCE_NO> P_MW_REFERENCE_NO { get; set; }
        public virtual DbSet<P_MW_RRM_REQUEST> P_MW_RRM_REQUEST { get; set; }
        public virtual DbSet<P_MW_SCANNED_DOCUMENT> P_MW_SCANNED_DOCUMENT { get; set; }
        public virtual DbSet<P_MW_SMI_C> P_MW_SMI_C { get; set; }
        public virtual DbSet<P_MW_SUBMISSION_PROCESSING_INFO> P_MW_SUBMISSION_PROCESSING_INFO { get; set; }
        public virtual DbSet<P_MW_SUMMARY_MW_ITEM_CHECKLIST> P_MW_SUMMARY_MW_ITEM_CHECKLIST { get; set; }
        public virtual DbSet<P_MW_TASK_MANAGEMENT> P_MW_TASK_MANAGEMENT { get; set; }
        public virtual DbSet<P_MW_UPLOAD> P_MW_UPLOAD { get; set; }
        public virtual DbSet<P_MW_UPLOAD_ITEM> P_MW_UPLOAD_ITEM { get; set; }
        public virtual DbSet<P_MW_VERIFICATION> P_MW_VERIFICATION { get; set; }
        public virtual DbSet<P_MW_VERIFICATION_LOG> P_MW_VERIFICATION_LOG { get; set; }
        public virtual DbSet<P_MW_VERIFICATION_LOG_ITEM> P_MW_VERIFICATION_LOG_ITEM { get; set; }
        public virtual DbSet<P_MW_XML_VALUE> P_MW_XML_VALUE { get; set; }
        public virtual DbSet<P_RV_BLOCK> P_RV_BLOCK { get; set; }
        public virtual DbSet<P_RV_BUILDING> P_RV_BUILDING { get; set; }
        public virtual DbSet<P_RV_DEVELOPMENT_NAME> P_RV_DEVELOPMENT_NAME { get; set; }
        public virtual DbSet<P_RV_LOCATION_NAME> P_RV_LOCATION_NAME { get; set; }
        public virtual DbSet<P_RV_NEW_DISTRICT> P_RV_NEW_DISTRICT { get; set; }
        public virtual DbSet<P_RV_STREET_LOCATION> P_RV_STREET_LOCATION { get; set; }
        public virtual DbSet<P_RV_STREET_NAME> P_RV_STREET_NAME { get; set; }
        public virtual DbSet<P_RV_TENEMENT> P_RV_TENEMENT { get; set; }
        public virtual DbSet<P_RV_UNIT> P_RV_UNIT { get; set; }
        public virtual DbSet<P_S_AUDIT_CHECK_PERCENTAGE> P_S_AUDIT_CHECK_PERCENTAGE { get; set; }
        public virtual DbSet<P_S_AUDIT_TRAIL> P_S_AUDIT_TRAIL { get; set; }
        public virtual DbSet<P_S_AUDIT_TRAIL_VALUE> P_S_AUDIT_TRAIL_VALUE { get; set; }
        public virtual DbSet<P_S_CAPACITY_OF_PRC> P_S_CAPACITY_OF_PRC { get; set; }
        public virtual DbSet<P_S_DAILY_DIRECT_RT_OVER_CNT> P_S_DAILY_DIRECT_RT_OVER_CNT { get; set; }
        public virtual DbSet<P_S_FORM_CHECK_ITEM> P_S_FORM_CHECK_ITEM { get; set; }
        public virtual DbSet<P_S_FORM_CHECK_ITEM_RESULT> P_S_FORM_CHECK_ITEM_RESULT { get; set; }
        public virtual DbSet<P_S_FORM_TYPE> P_S_FORM_TYPE { get; set; }
        public virtual DbSet<P_S_IMPORT_MW_ITEM> P_S_IMPORT_MW_ITEM { get; set; }
        public virtual DbSet<P_S_MW_CLASS> P_S_MW_CLASS { get; set; }
        public virtual DbSet<P_S_MW_ITEM> P_S_MW_ITEM { get; set; }
        public virtual DbSet<P_S_MW_ITEM_CHECKBOX> P_S_MW_ITEM_CHECKBOX { get; set; }
        public virtual DbSet<P_S_MW_ITEM_CHECKLIST_ITEM> P_S_MW_ITEM_CHECKLIST_ITEM { get; set; }
        public virtual DbSet<P_S_MW_ITEM_LOCATION> P_S_MW_ITEM_LOCATION { get; set; }
        public virtual DbSet<P_S_MW_ITEM_NATURE> P_S_MW_ITEM_NATURE { get; set; }
        public virtual DbSet<P_S_MW_NO_SECURITY_LEVEL> P_S_MW_NO_SECURITY_LEVEL { get; set; }
        public virtual DbSet<P_S_MW_NUMBER> P_S_MW_NUMBER { get; set; }
        public virtual DbSet<P_S_MW_TYPE> P_S_MW_TYPE { get; set; }
        public virtual DbSet<P_S_PUBLIC_HOLIDAY> P_S_PUBLIC_HOLIDAY { get; set; }
        public virtual DbSet<P_S_REFERRAL> P_S_REFERRAL { get; set; }
        public virtual DbSet<P_S_ROLE> P_S_ROLE { get; set; }
        public virtual DbSet<P_S_RULE_OF_CON_LETTER_AND_REF> P_S_RULE_OF_CON_LETTER_AND_REF { get; set; }
        public virtual DbSet<P_S_SYSTEM_TYPE> P_S_SYSTEM_TYPE { get; set; }
        public virtual DbSet<P_S_SYSTEM_VALUE> P_S_SYSTEM_VALUE { get; set; }
        public virtual DbSet<P_S_TEMPLATE> P_S_TEMPLATE { get; set; }
        public virtual DbSet<P_S_TO_DETAILS> P_S_TO_DETAILS { get; set; }
        public virtual DbSet<P_WF_INFO> P_WF_INFO { get; set; }
        public virtual DbSet<P_WF_TASK> P_WF_TASK { get; set; }
        public virtual DbSet<P_WF_TASK_USER> P_WF_TASK_USER { get; set; }
        public virtual DbSet<P_WF_TASKTOUSER> P_WF_TASKTOUSER { get; set; }
        public virtual DbSet<V_CRM_INFO> V_CRM_INFO { get; set; }
        public virtual DbSet<P_MOD_BD106_ANNUAL_INSP> P_MOD_BD106_ANNUAL_INSP { get; set; }
        public virtual DbSet<P_S_SCU_TEAM> P_S_SCU_TEAM { get; set; }
        public virtual DbSet<P_WF_ROUND_ROBIN> P_WF_ROUND_ROBIN { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW01> P_EFMWU_TBL_MW01 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW01_ITEM> P_EFMWU_TBL_MW01_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW02> P_EFMWU_TBL_MW02 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW02_ITEM1> P_EFMWU_TBL_MW02_ITEM1 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW02_ITEM2> P_EFMWU_TBL_MW02_ITEM2 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW02_ITEM3> P_EFMWU_TBL_MW02_ITEM3 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW03> P_EFMWU_TBL_MW03 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW03_ITEM> P_EFMWU_TBL_MW03_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW04> P_EFMWU_TBL_MW04 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW04_ITEM2> P_EFMWU_TBL_MW04_ITEM2 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW04_ITEM3> P_EFMWU_TBL_MW04_ITEM3 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW05> P_EFMWU_TBL_MW05 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW05_ITEM> P_EFMWU_TBL_MW05_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW06> P_EFMWU_TBL_MW06 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW06_ITEM> P_EFMWU_TBL_MW06_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW06_ITEMAS> P_EFMWU_TBL_MW06_ITEMAS { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW07> P_EFMWU_TBL_MW07 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW08> P_EFMWU_TBL_MW08 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW09> P_EFMWU_TBL_MW09 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW09_ITEM> P_EFMWU_TBL_MW09_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW10> P_EFMWU_TBL_MW10 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW10_ITEM> P_EFMWU_TBL_MW10_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW11> P_EFMWU_TBL_MW11 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW11_ITEM> P_EFMWU_TBL_MW11_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW12> P_EFMWU_TBL_MW12 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW12_ITEM> P_EFMWU_TBL_MW12_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW31> P_EFMWU_TBL_MW31 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW31_ITEM> P_EFMWU_TBL_MW31_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW32> P_EFMWU_TBL_MW32 { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW32_ITEM> P_EFMWU_TBL_MW32_ITEM { get; set; }
        public virtual DbSet<P_EFMWU_TBL_MW33> P_EFMWU_TBL_MW33 { get; set; }
        public virtual DbSet<P_EFSS_FORM_ATTACHMENTS> P_EFSS_FORM_ATTACHMENTS { get; set; }
        public virtual DbSet<P_EFSS_FORM_MASTER> P_EFSS_FORM_MASTER { get; set; }
        public virtual DbSet<P_EFSS_REJECT_REASONS> P_EFSS_REJECT_REASONS { get; set; }
        public virtual DbSet<P_MW_RECORD_AL_FOLLOW_UP> P_MW_RECORD_AL_FOLLOW_UP { get; set; }
        public virtual DbSet<P_MW_RECORD_AL_FOLLOW_UP_OFFENCES> P_MW_RECORD_AL_FOLLOW_UP_OFFENCES { get; set; }
        public virtual DbSet<P_EFSS_SUBMISSION_MAP> P_EFSS_SUBMISSION_MAP { get; set; }
        public virtual DbSet<P_MW_RECORD_REFERRED_TO_LSS_EBD> P_MW_RECORD_REFERRED_TO_LSS_EBD { get; set; }
        public virtual DbSet<P_MW_RECORD_WL_FOLLOW_UP> P_MW_RECORD_WL_FOLLOW_UP { get; set; }
        public virtual DbSet<P_S_ADDRESS_LIST> P_S_ADDRESS_LIST { get; set; }
        public virtual DbSet<P_S_DIRECT_RETURN_ROSTER> P_S_DIRECT_RETURN_ROSTER { get; set; }
        public virtual DbSet<P_MW_FILEREF> P_MW_FILEREF { get; set; }
        public virtual DbSet<SYS_EMAIL_SENDER> SYS_EMAIL_SENDER { get; set; }
    }
}
