//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWMS_BLK_FILEREF
    {
        public decimal ADR_BLK_FILEREF_ID { get; set; }
        public Nullable<decimal> ADR_BLK_ID { get; set; }
        public string FREF_SEQ { get; set; }
        public string FREF_YR { get; set; }
    }
}
