//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWMS_DISTRICT
    {
        public decimal SYS_DISTRICT_ID { get; set; }
        public string CODE { get; set; }
        public decimal REGION_ID { get; set; }
        public string DESCRIP { get; set; }
        public string DESCRIP_C { get; set; }
    }
}
