//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWMS_ST_LOC
    {
        public decimal SYS_ST_LOC_ID { get; set; }
        public Nullable<decimal> SYS_ST_NAME_ID { get; set; }
        public Nullable<decimal> SYS_LOC_NAME_ID1 { get; set; }
        public Nullable<decimal> SYS_LOC_NAME_ID2 { get; set; }
        public Nullable<decimal> SYS_LOC_NAME_ID3 { get; set; }
        public string SL_NAME_C { get; set; }
        public string NATURE { get; set; }
        public string LR_LOC { get; set; }
        public string LR_ST { get; set; }
    }
}
