//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWMS_BLK_SL
    {
        public decimal ADR_BLK_SL_ID { get; set; }
        public decimal ADR_BLK_ID { get; set; }
        public Nullable<decimal> SYS_ST_LOC_ID { get; set; }
        public Nullable<short> ST_NO_NUM { get; set; }
        public string ST_NO_ALPHA { get; set; }
        public string ST_NO_EXT { get; set; }
        public string UNOFF_CODE { get; set; }
        public string BLK_SL_TYPE { get; set; }
        public string PMS_ST_NO_CONFIRM { get; set; }
        public string OSADR_ST_E1 { get; set; }
        public string OSADR_ST_E2 { get; set; }
        public string OSADR_GEN_E { get; set; }
        public string OSADR_ST_C { get; set; }
        public string OSADR_GEN_C { get; set; }
    }
}
