//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW11
    {
        public string ID { get; set; }
        public Nullable<byte> ADDITIONPAGE { get; set; }
        public decimal ADDPAGENUM { get; set; }
        public string AMWSIGN { get; set; }
        public System.DateTime AMWSIGNDATE { get; set; }
        public System.DateTime AMWSIGNEXPIREDDATE { get; set; }
        public string AMWSIGNNAME { get; set; }
        public string AMWSIGNRESULT { get; set; }
        public string APPCHINAME { get; set; }
        public string APPENGNAME1 { get; set; }
        public string APPENGNAME2 { get; set; }
        public string APPSIGN { get; set; }
        public System.DateTime APPSIGNDATE { get; set; }
        public System.DateTime APPSIGNEXPIREDDATE { get; set; }
        public string APPSIGNNAME { get; set; }
        public string APPSIGNRESULT { get; set; }
        public string ASCHINAME { get; set; }
        public string ASENGNAME1 { get; set; }
        public string ASENGNAME2 { get; set; }
        public string AUTHCHINAME { get; set; }
        public System.DateTime AUTHCREXPIREDDATE { get; set; }
        public string AUTHCRNUM1 { get; set; }
        public string AUTHCRNUM2 { get; set; }
        public string AUTHENGNAME { get; set; }
        public string AUTHFAX { get; set; }
        public string AUTHSIGN { get; set; }
        public System.DateTime AUTHSIGNDATE { get; set; }
        public System.DateTime AUTHSIGNEXPIREDDATE { get; set; }
        public string AUTHSIGNNAME { get; set; }
        public string AUTHSIGNRESULT { get; set; }
        public string AUTHTEL { get; set; }
        public string COMBUILDING { get; set; }
        public string COMDISTRICT { get; set; }
        public string COMDISTRICTOPTION { get; set; }
        public string COMEMAIL { get; set; }
        public string COMFAX { get; set; }
        public string COMFLOOR { get; set; }
        public System.DateTime COMMENDATE { get; set; }
        public string COMNAME { get; set; }
        public Nullable<byte> COMOPTION { get; set; }
        public string COMROOM { get; set; }
        public string COMSRV { get; set; }
        public string COMSTREETNO { get; set; }
        public string COMTEL { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string EMAIL { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string RCCHINAME { get; set; }
        public string RCCRNUM1 { get; set; }
        public string RCCRNUM2 { get; set; }
        public string RCENGNAME1 { get; set; }
        public string RCENGNAME2 { get; set; }
        public System.DateTime RCEXPIREDDATE { get; set; }
        public string RCFAX { get; set; }
        public string RCSIGN { get; set; }
        public System.DateTime RCSIGNDATE { get; set; }
        public System.DateTime RCSIGNEXPIREDDATE { get; set; }
        public string RCSIGNNAME { get; set; }
        public string RCSIGNRESULT { get; set; }
        public string RCTEL { get; set; }
        public string RGECHINAME { get; set; }
        public System.DateTime RGECREXPIREDDATE { get; set; }
        public string RGECRNUM1 { get; set; }
        public string RGECRNUM2 { get; set; }
        public string RGEENGNAME { get; set; }
        public string RGESIGN { get; set; }
        public System.DateTime RGESIGNDATE { get; set; }
        public System.DateTime RGESIGNEXPIREDDATE { get; set; }
        public string RGESIGNNAME { get; set; }
        public string RGESIGNRESULT { get; set; }
        public string RGETEL { get; set; }
        public string RSECHINAME { get; set; }
        public System.DateTime RSECREXPIREDDATE { get; set; }
        public string RSECRNUM1 { get; set; }
        public string RSECRNUM2 { get; set; }
        public string RSEENGNAME { get; set; }
        public string RSESIGN { get; set; }
        public System.DateTime RSESIGNDATE { get; set; }
        public System.DateTime RSESIGNEXPIREDDATE { get; set; }
        public string RSESIGNNAME { get; set; }
        public string RSESIGNRESULT { get; set; }
        public string RSETEL { get; set; }
        public Nullable<byte> SAMEDATEOPTION { get; set; }
        public string SOBRN { get; set; }
        public Nullable<byte> SOBRNOPTION { get; set; }
        public string SOCHINAME { get; set; }
        public Nullable<byte> SOCORRADDOPTION { get; set; }
        public string SOCORRBUILDING { get; set; }
        public string SOCORRDISTRICT { get; set; }
        public string SOCORRDISTRICTOPTION { get; set; }
        public string SOCORRFLOOR { get; set; }
        public string SOCORRROOM { get; set; }
        public string SOCORRSRV { get; set; }
        public string SOCORRSTREETNO { get; set; }
        public string SOEMAIL { get; set; }
        public string SOENGNAME1 { get; set; }
        public string SOENGNAME2 { get; set; }
        public string SOFAX { get; set; }
        public string SOHKIDNUM { get; set; }
        public Nullable<byte> SOHKIDOPTION { get; set; }
        public Nullable<byte> SOOPTION { get; set; }
        public Nullable<byte> SOOPTIONN { get; set; }
        public string SOOTHERDESC { get; set; }
        public string SOOTHERNO { get; set; }
        public Nullable<byte> SOOTHEROPTION { get; set; }
        public string SOPASSPORTISSUECNTRY { get; set; }
        public string SOPN { get; set; }
        public Nullable<byte> SOPNOPTION { get; set; }
        public string SOSIGN { get; set; }
        public System.DateTime SOSIGNDATE { get; set; }
        public System.DateTime SOSIGNEXPIREDDATE { get; set; }
        public string SOSIGNNAME { get; set; }
        public string SOSIGNRESULT { get; set; }
        public string SOTEL { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<byte> STARTDATEOPTION { get; set; }
    }
}
