//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFSS_FORM_MASTER
    {
        public string ID { get; set; }
        public decimal REFERENCEID { get; set; }
        public string FILENAME { get; set; }
        public string FILEEXTENSION { get; set; }
        public byte[] FILECONTENT { get; set; }
        public string STATUS { get; set; }
        public string PROCESSRESULT { get; set; }
        public string SOURCE { get; set; }
        public string FOURPLUSTWO { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public System.DateTime UPDATEDDATE { get; set; }
        public string FORMID { get; set; }
        public string FORMCONTENTID { get; set; }
        public string FORMHANDLER { get; set; }
        public string PRIORITY { get; set; }
        public string SECTION { get; set; }
        public string REMARK { get; set; }
        public string SUBMISSIONNO { get; set; }
        public byte ISAUDITCASEFORREG { get; set; }
        public string BK_ID { get; set; }
    }
}
