//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW32
    {
        public string ID { get; set; }
        public Nullable<byte> ADDITIONPAGE { get; set; }
        public decimal ADDPAGENUM { get; set; }
        public string AMWSIGN { get; set; }
        public System.DateTime AMWSIGNDATE { get; set; }
        public System.DateTime AMWSIGNEXPIREDDATE { get; set; }
        public string AMWSIGNNAME { get; set; }
        public string AMWSIGNRESULT { get; set; }
        public string ARRCHINAME { get; set; }
        public string ARRENGNAME1 { get; set; }
        public string ARRENGNAME2 { get; set; }
        public string ASCHINAME { get; set; }
        public string ASENGNAME1 { get; set; }
        public string ASENGNAME2 { get; set; }
        public string BUILDING { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string DISTRICT { get; set; }
        public string DISTRICTOPTION { get; set; }
        public string DRGRACCOUNTNO { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime EXPECTEDCOMMENCEDATE { get; set; }
        public System.DateTime EXPECTEDCOMPLETEDATE { get; set; }
        public string FLAT { get; set; }
        public string FLOOR { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWLOCATION { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string RCCHINAME { get; set; }
        public System.DateTime RCCREXPIREDDATE { get; set; }
        public string RCCRNUM1 { get; set; }
        public string RCCRNUM2 { get; set; }
        public string RCENGNAME1 { get; set; }
        public string RCENGNAME2 { get; set; }
        public string RCFAX { get; set; }
        public string RCSIGN { get; set; }
        public System.DateTime RCSIGNDATE { get; set; }
        public System.DateTime RCSIGNEXPIREDDATE { get; set; }
        public string RCSIGNNAME { get; set; }
        public string RCSIGNRESULT { get; set; }
        public string RCTEL { get; set; }
        public decimal SIGNBOARDALTEREDNO { get; set; }
        public decimal SIGNBOARDERECTEDNO { get; set; }
        public string SOCHINAME { get; set; }
        public string SOENGNAME1 { get; set; }
        public string SOENGNAME2 { get; set; }
        public string STREETNO { get; set; }
        public string STREETROADVILLAGE { get; set; }
    }
}
