//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW04
    {
        public string ID { get; set; }
        public Nullable<byte> ADDITIONALPAGE3 { get; set; }
        public decimal ADDITIONAPAGENO3 { get; set; }
        public Nullable<byte> ADDITIONPAGE2 { get; set; }
        public decimal ADDPAGENUM2 { get; set; }
        public string AMWSIGN { get; set; }
        public System.DateTime AMWSIGNDATE1 { get; set; }
        public System.DateTime AMWSIGNDATE2 { get; set; }
        public System.DateTime AMWSIGNEXPIREDDATE { get; set; }
        public string AMWSIGNNAME { get; set; }
        public string AMWSIGNRESULT { get; set; }
        public string ARCCHINAME { get; set; }
        public string ARCENGNAME1 { get; set; }
        public string ARCENGNAME2 { get; set; }
        public string ARCSIGN { get; set; }
        public System.DateTime ARCSIGNDATE { get; set; }
        public System.DateTime ARCSIGNEXPIREDDATE { get; set; }
        public string ARCSIGNNAME { get; set; }
        public string ARCSIGNRESULT { get; set; }
        public string ASCHINAME { get; set; }
        public string ASENGNAME { get; set; }
        public System.DateTime COMPLETDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string EMAIL { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string RCCHINAME { get; set; }
        public System.DateTime RCCREXPIREDDATE { get; set; }
        public string RCCRNUM1 { get; set; }
        public string RCCRNUM2 { get; set; }
        public string RCENGNAME1 { get; set; }
        public string RCENGNAME2 { get; set; }
        public string RCFAX { get; set; }
        public string RCSIGN { get; set; }
        public System.DateTime RCSIGNDATE { get; set; }
        public System.DateTime RCSIGNEXPIREDDATE { get; set; }
        public string RCSIGNNAME { get; set; }
        public string RCSIGNRESULT { get; set; }
        public string RCTEL { get; set; }
        public string SOBRN { get; set; }
        public Nullable<byte> SOBRNOPTION { get; set; }
        public string SOCHINAME { get; set; }
        public Nullable<byte> SOCORRADD { get; set; }
        public string SOCORRBUILDING { get; set; }
        public string SOCORRDISTRICT { get; set; }
        public string SOCORRDISTRICTOPTION { get; set; }
        public string SOCORRFLOOR { get; set; }
        public string SOCORRROOM { get; set; }
        public string SOCORRSRV { get; set; }
        public string SOCORRSTREETNO { get; set; }
        public string SOEMAIL { get; set; }
        public string SOENGNAME1 { get; set; }
        public string SOENGNAME2 { get; set; }
        public string SOFAX { get; set; }
        public string SOHKIDNUM { get; set; }
        public Nullable<byte> SOHKIDOPTION { get; set; }
        public Nullable<byte> SOOPTION { get; set; }
        public Nullable<byte> SOOPTIONN { get; set; }
        public string SOOTHERDESC { get; set; }
        public string SOOTHERNO { get; set; }
        public Nullable<byte> SOOTHEROPTION { get; set; }
        public string SOPASSPORTISSUECNTRY { get; set; }
        public string SOPN { get; set; }
        public Nullable<byte> SOPNOPTION { get; set; }
        public string SOSIGN { get; set; }
        public System.DateTime SOSIGNDATE { get; set; }
        public System.DateTime SOSIGNEXPIREDDATE { get; set; }
        public string SOSIGNNAME { get; set; }
        public string SOSIGNRESULT { get; set; }
        public string SOTEL { get; set; }
    }
}
