//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW33
    {
        public string ID { get; set; }
        public string APCHINAME { get; set; }
        public System.DateTime APCREXPIREDDATE { get; set; }
        public string APCRNUM1 { get; set; }
        public string APCRNUM2 { get; set; }
        public string APENGNAME1 { get; set; }
        public string APENGNAME2 { get; set; }
        public string APFAX { get; set; }
        public Nullable<byte> APOPTION { get; set; }
        public string APSIGN { get; set; }
        public System.DateTime APSIGNDATE { get; set; }
        public System.DateTime APSIGNEXPIREDDATE { get; set; }
        public string APSIGNNAME { get; set; }
        public string APSIGNRESULT { get; set; }
        public string APTEL { get; set; }
        public string ASCHINAME { get; set; }
        public string ASENGNAME1 { get; set; }
        public string ASENGNAME2 { get; set; }
        public Nullable<byte> CATALOGOPTION { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<byte> DEMOPROPOSALOPTION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<byte> GAROPTION { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public Nullable<byte> MATERIALINVOPTION { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string OTHER { get; set; }
        public Nullable<byte> OTHEROPTION { get; set; }
        public Nullable<byte> PHOTOALLCOMPLETEDOPTION { get; set; }
        public Nullable<byte> PHOTOPREMISEBEFOREOPTION { get; set; }
        public Nullable<byte> PRCOPTION { get; set; }
        public Nullable<byte> REVISEDPLANOPTION { get; set; }
        public Nullable<byte> RGEOPTION { get; set; }
        public Nullable<byte> RIOPTION { get; set; }
        public Nullable<byte> RSEOPTION { get; set; }
        public Nullable<byte> STRUCAPPRREPORTOPTION { get; set; }
        public Nullable<byte> STRUCCALOPTION { get; set; }
        public Nullable<byte> SUPERVISIONPLANOPTION { get; set; }
        public Nullable<byte> TEMPSAFETYOPTION { get; set; }
    }
}
