//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW10_ITEM
    {
        public string ID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<byte> DELETED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MW10ID { get; set; }
        public string MWDESC { get; set; }
        public string MWITEM { get; set; }
        public string MWREFNO { get; set; }
    }
}
