//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW01
    {
        public string ID { get; set; }
        public decimal ADDEDPAGENO { get; set; }
        public Nullable<byte> ADDITIONAL { get; set; }
        public string AMWSIGN { get; set; }
        public System.DateTime AMWSIGNDATE { get; set; }
        public System.DateTime AMWSIGNEXPIREDDATE { get; set; }
        public string AMWSIGNNAME { get; set; }
        public string AMWSIGNRESULT { get; set; }
        public string APCFMSIGN { get; set; }
        public System.DateTime APCFMSIGNDATE { get; set; }
        public System.DateTime APCFMSIGNEXPIREDDATE { get; set; }
        public string APCFMSIGNNAME { get; set; }
        public string APCFMSIGNRESULT { get; set; }
        public string APRICERTNUM1 { get; set; }
        public string APRICERTNUM2 { get; set; }
        public string APRICHINAME { get; set; }
        public string APRIENGNAME1 { get; set; }
        public string APRIENGNAME2 { get; set; }
        public string APTPASCHINAME { get; set; }
        public string APTPASENGNAME1 { get; set; }
        public string APTPASENGNAME2 { get; set; }
        public string APTPCERTNUM1 { get; set; }
        public string APTPCERTNUM2 { get; set; }
        public string ARCFMCHINAME { get; set; }
        public string ARCFMCRNUM1 { get; set; }
        public string ARCFMCRNUM2 { get; set; }
        public string ARCFMENGNAME1 { get; set; }
        public string ARCFMENGNAME2 { get; set; }
        public string ARCFMFAX { get; set; }
        public System.DateTime ARCFMREGEXPIREDATE { get; set; }
        public string ARCFMTEL { get; set; }
        public string ARRFAX { get; set; }
        public string ARRSIGN { get; set; }
        public System.DateTime ARRSIGNDATE { get; set; }
        public System.DateTime ARRSIGNEXPIREDDATE { get; set; }
        public string ARRSIGNNAME { get; set; }
        public string ARRSIGNRESULT { get; set; }
        public string ARRTEL { get; set; }
        public string ASCHINAME { get; set; }
        public string ASENGNAME1 { get; set; }
        public string ASENGNAME2 { get; set; }
        public Nullable<byte> AUTHPERSONOPTION { get; set; }
        public string BRN { get; set; }
        public Nullable<byte> BRNOPTION { get; set; }
        public string BUILDING { get; set; }
        public string COMBUILDING { get; set; }
        public string COMDISTRICT { get; set; }
        public string COMDISTRICTOPTION { get; set; }
        public string COMEMAIL { get; set; }
        public string COMFAX { get; set; }
        public string COMFLOOR { get; set; }
        public System.DateTime COMMDATE { get; set; }
        public string COMNAME { get; set; }
        public string COMROOM { get; set; }
        public string COMSRV { get; set; }
        public string COMSTREET { get; set; }
        public string COMTEL { get; set; }
        public Nullable<byte> CORRADDOPTION { get; set; }
        public string CORRADDSTREET { get; set; }
        public string CORRBUILDING { get; set; }
        public string CORRDISTRICT { get; set; }
        public string CORRDISTRICTOPTION { get; set; }
        public string CORRFLOOR { get; set; }
        public string CORRROOM { get; set; }
        public string CORRSTREETNO { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string DESC_ { get; set; }
        public string DISTRICT { get; set; }
        public string DISTRICTOPTION { get; set; }
        public string DRGRACCOUNT { get; set; }
        public string EMAIL { get; set; }
        public string FLATROOM { get; set; }
        public string FLOOR { get; set; }
        public string HKIDNUM { get; set; }
        public Nullable<byte> HKIDOPTION { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string LOCATION { get; set; }
        public string MWCHINAME { get; set; }
        public string MWENGNAME1 { get; set; }
        public string MWENGNAME2 { get; set; }
        public string MWITEM { get; set; }
        public string MWSUBMITID { get; set; }
        public string OTHERDESC { get; set; }
        public string OTHERNO { get; set; }
        public Nullable<byte> OTHEROPTION { get; set; }
        public string PASSPORT { get; set; }
        public string PASSPORTISSUECNTRY { get; set; }
        public Nullable<byte> PASSPORTOPTION { get; set; }
        public string PREMWSUBMITID { get; set; }
        public string PREVMWSUBMISSIONID { get; set; }
        public string RCCFMCHINAME { get; set; }
        public string RCCFMCRNUM1 { get; set; }
        public string RCCFMCRNUM2 { get; set; }
        public string RCCFMENGNAME1 { get; set; }
        public string RCCFMENGNAME2 { get; set; }
        public string RCCFMFAX { get; set; }
        public System.DateTime RCCFMREGEXPIREDATE { get; set; }
        public string RCCFMSIGN { get; set; }
        public System.DateTime RCCFMSIGNDATE { get; set; }
        public System.DateTime RCCFMSIGNEXPIREDDATE { get; set; }
        public string RCCFMSIGNNAME { get; set; }
        public string RCCFMSIGNRESULT { get; set; }
        public string RCCFMTEL { get; set; }
        public string REFNO { get; set; }
        public Nullable<byte> REGINSPECOPTION { get; set; }
        public string RGECERTNUM1 { get; set; }
        public string RGECERTNUM2 { get; set; }
        public string RGECFMCHINAME { get; set; }
        public string RGECFMCRNUM1 { get; set; }
        public string RGECFMCRNUM2 { get; set; }
        public string RGECFMENGNAME { get; set; }
        public System.DateTime RGECFMREGEXPIREDATE { get; set; }
        public string RGECFMSIGN { get; set; }
        public System.DateTime RGECFMSIGNDATE { get; set; }
        public System.DateTime RGECFMSIGNEXPIREDDATE { get; set; }
        public string RGECFMSIGNNAME { get; set; }
        public string RGECFMSIGNRESULT { get; set; }
        public string RGECFMTEL { get; set; }
        public string RGECHINAME { get; set; }
        public string RGEENGNAME { get; set; }
        public Nullable<byte> RGEOPTION { get; set; }
        public string RSECERTNUM1 { get; set; }
        public string RSECERTNUM2 { get; set; }
        public string RSECFMCHINAME { get; set; }
        public string RSECFMCRNUM1 { get; set; }
        public string RSECFMCRNUM2 { get; set; }
        public string RSECFMENGNAME { get; set; }
        public System.DateTime RSECFMREGEXPIREDATE { get; set; }
        public string RSECFMSIGN { get; set; }
        public System.DateTime RSECFMSIGNDATE { get; set; }
        public System.DateTime RSECFMSIGNEXPIREDDATE { get; set; }
        public string RSECFMSIGNNAME { get; set; }
        public string RSECFMSIGNRESULT { get; set; }
        public string RSECFMTEL { get; set; }
        public string RSECHINAME { get; set; }
        public string RSEENGNAME { get; set; }
        public Nullable<byte> RSEOPTION { get; set; }
        public string SOBRN { get; set; }
        public Nullable<byte> SOBRNOPTION { get; set; }
        public string SOBUILDING { get; set; }
        public string SOCHINAME { get; set; }
        public Nullable<byte> SOCORRADDRESS { get; set; }
        public string SODISTRICT { get; set; }
        public string SODISTRICTNO { get; set; }
        public string SOEMAIL { get; set; }
        public string SOENGNAME1 { get; set; }
        public string SOENGNAME2 { get; set; }
        public string SOFAX { get; set; }
        public string SOFLOOR { get; set; }
        public string SOHKIDNUM { get; set; }
        public Nullable<byte> SOHKIDOPTION { get; set; }
        public string SOOTHERDESC { get; set; }
        public string SOOTHERNO { get; set; }
        public Nullable<byte> SOOTHEROPTION { get; set; }
        public string SOPASSPORT { get; set; }
        public string SOPASSPORTISSUECNTRY { get; set; }
        public Nullable<byte> SOPASSPORTOPTION { get; set; }
        public string SOROOM { get; set; }
        public string SOSIGN { get; set; }
        public System.DateTime SOSIGNDATE { get; set; }
        public System.DateTime SOSIGNEXPIREDDATE { get; set; }
        public string SOSIGNNAME { get; set; }
        public string SOSIGNRESULT { get; set; }
        public string SOSRV { get; set; }
        public string SOSTREETNUM { get; set; }
        public string SOTEL { get; set; }
        public string STREETNO { get; set; }
        public string STREETROADVILLAGE { get; set; }
    }
}
