//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW12
    {
        public string ID { get; set; }
        public Nullable<byte> ADDITIONPAGE { get; set; }
        public decimal ADDPAGENUM { get; set; }
        public string AMWSIGN { get; set; }
        public System.DateTime AMWSIGNDATE { get; set; }
        public System.DateTime AMWSIGNEXPIREDDATE { get; set; }
        public string AMWSIGNNAME { get; set; }
        public string AMWSIGNRESULT { get; set; }
        public string ARRCHINAME { get; set; }
        public string ARRENGNAME1 { get; set; }
        public string ARRENGNAME2 { get; set; }
        public string ARRSIGN { get; set; }
        public System.DateTime ARRSIGNDATE { get; set; }
        public System.DateTime ARRSIGNEXPIREDDATE { get; set; }
        public string ARRSIGNNAME { get; set; }
        public string ARRSIGNRESULT { get; set; }
        public string COMBUILDING { get; set; }
        public string COMDISTRICT { get; set; }
        public string COMDISTRICTOPTION { get; set; }
        public string COMEMAIL { get; set; }
        public string COMFAX { get; set; }
        public string COMFLOOR { get; set; }
        public System.DateTime COMMENDATE { get; set; }
        public string COMNAME { get; set; }
        public Nullable<byte> COMOPTION { get; set; }
        public string COMROOM { get; set; }
        public string COMSRV { get; set; }
        public string COMSTREETNO { get; set; }
        public string COMTEL { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string EMAIL { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string RCASCHINAME { get; set; }
        public string RCASENGNAME1 { get; set; }
        public string RCASENGNAME2 { get; set; }
        public string RCCHINAME { get; set; }
        public System.DateTime RCCREXPIREDDATE { get; set; }
        public string RCCRNUM1 { get; set; }
        public string RCCRNUM2 { get; set; }
        public string RCENGNAME1 { get; set; }
        public string RCENGNAME2 { get; set; }
        public string RCFAX { get; set; }
        public string RCSIGN { get; set; }
        public System.DateTime RCSIGNDATE { get; set; }
        public System.DateTime RCSIGNEXPIREDDATE { get; set; }
        public string RCSIGNNAME { get; set; }
        public string RCSIGNRESULT { get; set; }
        public string RCTEL { get; set; }
        public string SOBRN { get; set; }
        public Nullable<byte> SOBRNOPTION { get; set; }
        public string SOCHINAME { get; set; }
        public Nullable<byte> SOCORRADDOPTION { get; set; }
        public string SOCORRBUILDING { get; set; }
        public string SOCORRDISTRICT { get; set; }
        public string SOCORRDISTRICTOPTION { get; set; }
        public string SOCORRFLOOR { get; set; }
        public string SOCORRROOM { get; set; }
        public string SOCORRSRV { get; set; }
        public string SOCORRSTREETNO { get; set; }
        public string SOEMAIL { get; set; }
        public string SOENGNAME1 { get; set; }
        public string SOENGNAME2 { get; set; }
        public string SOFAX { get; set; }
        public string SOHKIDNUM { get; set; }
        public Nullable<byte> SOHKIDOPTION { get; set; }
        public Nullable<byte> SOOPTION { get; set; }
        public Nullable<byte> SOOPTIONN { get; set; }
        public string SOOTHERDESC { get; set; }
        public string SOOTHERNO { get; set; }
        public Nullable<byte> SOOTHEROPTION { get; set; }
        public string SOPASSPORTISSUECNTRY { get; set; }
        public string SOPN { get; set; }
        public Nullable<byte> SOPNOPTION { get; set; }
        public string SOSIGN { get; set; }
        public System.DateTime SOSIGNDATE { get; set; }
        public System.DateTime SOSIGNEXPIREDDATE { get; set; }
        public string SOSIGNNAME { get; set; }
        public string SOSIGNRESULT { get; set; }
        public string SOTEL { get; set; }
    }
}
