//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW09
    {
        public string ID { get; set; }
        public Nullable<byte> APOPTION { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<System.DateTime> EFFECTFROMDATE { get; set; }
        public System.DateTime EFFECTTODATE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<byte> ILLOPTION { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string NOMINATORCHINAME { get; set; }
        public Nullable<System.DateTime> NOMINATORCREXPIREDDATE { get; set; }
        public string NOMINATORCRNUM1 { get; set; }
        public string NOMINATORCRNUM2 { get; set; }
        public string NOMINATORENGNAME1 { get; set; }
        public string NOMINATORFAX { get; set; }
        public string NOMINATORSIGN { get; set; }
        public Nullable<System.DateTime> NOMINATORSIGNDATE { get; set; }
        public System.DateTime NOMINATORSIGNEXPIREDDATE { get; set; }
        public string NOMINATORSIGNNAME { get; set; }
        public string NOMINATORSIGNRESULT { get; set; }
        public string NOMINATORTEL { get; set; }
        public string NOMINEECHINAME { get; set; }
        public Nullable<System.DateTime> NOMINEECREXPIREDDATE { get; set; }
        public string NOMINEECRNUM1 { get; set; }
        public string NOMINEECRNUM2 { get; set; }
        public string NOMINEEEMAIL { get; set; }
        public string NOMINEEENGNAME { get; set; }
        public string NOMINEEFAX { get; set; }
        public string NOMINEESIGN { get; set; }
        public Nullable<System.DateTime> NOMINEESIGNDATE { get; set; }
        public System.DateTime NOMINEESIGNEXPIREDDATE { get; set; }
        public string NOMINEESIGNNAME { get; set; }
        public string NOMINEESIGNRESULT { get; set; }
        public string NOMINEETEL { get; set; }
        public Nullable<byte> PERIODUNKNOWNOPTION { get; set; }
        public Nullable<byte> RGEOPTION { get; set; }
        public Nullable<byte> RIOPTION { get; set; }
        public Nullable<byte> RSEOPTION { get; set; }
        public Nullable<byte> TAOPTION { get; set; }
    }
}
