//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EFMWU_TBL_MW07
    {
        public string ID { get; set; }
        public string APCHINAME { get; set; }
        public string APENGNAME1 { get; set; }
        public string APENGNAME2 { get; set; }
        public string APFAX { get; set; }
        public string APRICHINAME { get; set; }
        public System.DateTime APRICREXPIREDDATE { get; set; }
        public string APRICRNUM1 { get; set; }
        public string APRICRNUM2 { get; set; }
        public string APRIENGNAME { get; set; }
        public string APRIFAX { get; set; }
        public string APRISIGN { get; set; }
        public System.DateTime APRISIGNDATE { get; set; }
        public System.DateTime APRISIGNEXPIREDDATE { get; set; }
        public string APRISIGNNAME { get; set; }
        public string APRISIGNRESULT { get; set; }
        public string APRITEL { get; set; }
        public string APSIGN { get; set; }
        public System.DateTime APSIGNDATE { get; set; }
        public System.DateTime APSIGNEXPIREDDATE { get; set; }
        public string APSIGNNAME { get; set; }
        public string APSIGNRESULT { get; set; }
        public string APTEL { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public System.DateTime EFFECTDATE { get; set; }
        public string EMAIL { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string MWSUBMISSIONID { get; set; }
        public string RCCFMASCHINAME { get; set; }
        public string RCCFMASENGNAME1 { get; set; }
        public string RCCFMASENGNAME2 { get; set; }
        public string RCCFMCHINAME { get; set; }
        public System.DateTime RCCFMCREXPIREDDATE { get; set; }
        public string RCCFMCRNUM1 { get; set; }
        public string RCCFMCRNUM2 { get; set; }
        public string RCCFMENGNAME1 { get; set; }
        public string RCCFMENGNAME2 { get; set; }
        public string RCCFMFAX { get; set; }
        public string RCCFMSIGN { get; set; }
        public System.DateTime RCCFMSIGNDATE { get; set; }
        public System.DateTime RCCFMSIGNEXPIREDDATE { get; set; }
        public string RCCFMSIGNNAME { get; set; }
        public string RCCFMSIGNRESULT { get; set; }
        public string RCCFMTEL { get; set; }
        public string RCCHINAME { get; set; }
        public string RCCRNUM1 { get; set; }
        public string RCCRNUM2 { get; set; }
        public string RCENGNAME1 { get; set; }
        public string RCENGNAME2 { get; set; }
        public Nullable<byte> RCOPTION { get; set; }
        public string RGECFMCHINAME { get; set; }
        public System.DateTime RGECFMCREXPIREDDATE { get; set; }
        public string RGECFMCRNUM1 { get; set; }
        public string RGECFMCRNUM2 { get; set; }
        public string RGECFMENGNAME { get; set; }
        public string RGECFMFAX { get; set; }
        public string RGECFMSIGN { get; set; }
        public System.DateTime RGECFMSIGNDATE { get; set; }
        public System.DateTime RGECFMSIGNEXPIREDDATE { get; set; }
        public string RGECFMSIGNNAME { get; set; }
        public string RGECFMSIGNRESULT { get; set; }
        public string RGECFMTEL { get; set; }
        public string RGECHINAME { get; set; }
        public string RGECRNUM1 { get; set; }
        public string RGECRNUM2 { get; set; }
        public string RGEENGNAME { get; set; }
        public Nullable<byte> RGEOPTION { get; set; }
        public string RSECFMCHINAME { get; set; }
        public System.DateTime RSECFMCREXPIREDDATE { get; set; }
        public string RSECFMCRNUM1 { get; set; }
        public string RSECFMCRNUM2 { get; set; }
        public string RSECFMENGNAME { get; set; }
        public string RSECFMFAX { get; set; }
        public string RSECFMSIGN { get; set; }
        public System.DateTime RSECFMSIGNDATE { get; set; }
        public System.DateTime RSECFMSIGNEXPIREDDATE { get; set; }
        public string RSECFMSIGNNAME { get; set; }
        public string RSECFMSIGNRESULT { get; set; }
        public string RSECFMTEL { get; set; }
        public string RSECHINAME { get; set; }
        public string RSECRNUM1 { get; set; }
        public string RSECRNUM2 { get; set; }
        public string RSEENGNAME { get; set; }
        public Nullable<byte> RSEOPTION { get; set; }
    }
}
