//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_LETTER_INFO
    {
        public decimal LETTERID { get; set; }
        public string NAME { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime SENDTIME { get; set; }
        public string FROMUSER { get; set; }
        public string RECIPIENT { get; set; }
        public string LETTER_TYPE { get; set; }
        public string LANGUAGE_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
