//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MOD_BD106
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MOD_BD106()
        {
            this.P_MOD_BD106_ITEM = new HashSet<P_MOD_BD106_ITEM>();
            this.P_MOD_BD106_ANNUAL_INSP = new HashSet<P_MOD_BD106_ANNUAL_INSP>();
        }
    
        public string UUID { get; set; }
        public string MW_MODIFICATION_ID { get; set; }
        public string MW_SCANNED_DOC_ID { get; set; }
        public string MW_FILE_REF_NO { get; set; }
        public string BCIS_UNIT_ID { get; set; }
        public string BLOCK_ID { get; set; }
        public string ADDRESS_ENG { get; set; }
        public string ADDRESS_CHI { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE_OF_FORM_BA16 { get; set; }
        public string RESULT_OF_THE_APPLICATION { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE_OF_BD106 { get; set; }
        public string NO_OF_APPROVED_FLATS_INVOLVED { get; set; }
        public Nullable<System.DateTime> NO_OF_CUBICLES_AFTER_SUBDIVISION { get; set; }
        public string FLOOR_AREA_OF_SUBDIVIDED_CUBICLES { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public Nullable<System.DateTime> ANNUAL_INSPECTION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> LSS_REFERRAL_DATE { get; set; }
        public Nullable<System.DateTime> EBD_REFERRAL_DATE { get; set; }
        public string SITE_INSP_COMPLETED { get; set; }
        public Nullable<System.DateTime> SITE_INSP_DATE { get; set; }
        public string INSP_RESULT { get; set; }
        public string IS_VALID { get; set; }
        public string PERMIT_NO { get; set; }
        public string OUR_REF_NO { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MOD_BD106_ITEM> P_MOD_BD106_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MOD_BD106_ANNUAL_INSP> P_MOD_BD106_ANNUAL_INSP { get; set; }
    }
}
