//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_RECORD_PSAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_RECORD_PSAC()
        {
            this.P_MW_RECORD_PSAC_IMAGE = new HashSet<P_MW_RECORD_PSAC_IMAGE>();
        }
    
        public string UUID { get; set; }
        public string RECORD_ID { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public string CHK_MW_NOT_YET_COMM { get; set; }
        public string CHK_MW_COMM_AND_COMP { get; set; }
        public string CHK_MW_IN_PROGRESS { get; set; }
        public string CHK_INACCESSIBLE { get; set; }
        public string BS_NAME { get; set; }
        public string BS_POST { get; set; }
        public Nullable<System.DateTime> BS_SIGNATURE_DATE { get; set; }
        public string SO_NAME { get; set; }
        public string SO_POST { get; set; }
        public Nullable<System.DateTime> SO_SIGNATURE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string HANDLING_UNIT { get; set; }
        public Nullable<System.DateTime> RECEIPT_DATE { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_PSAC_IMAGE> P_MW_RECORD_PSAC_IMAGE { get; set; }
    }
}
