//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_FORM_09
    {
        public string UUID { get; set; }
        public string MW_RECORD_ID { get; set; }
        public string MW_NUMBER { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string TO_CHECKING { get; set; }
        public string TO_RMK { get; set; }
        public string PO_AGREEMENT { get; set; }
        public string PO_RMK { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
    }
}
