//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_GENERAL_RECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_GENERAL_RECORD()
        {
            this.P_MW_GENERAL_RECORD_RELATED_CASE = new HashSet<P_MW_GENERAL_RECORD_RELATED_CASE>();
            this.P_MW_GENERAL_RECORD_ADDRESS_INFO = new HashSet<P_MW_GENERAL_RECORD_ADDRESS_INFO>();
            this.P_MW_GENERAL_RECORD_LETTER_INFO = new HashSet<P_MW_GENERAL_RECORD_LETTER_INFO>();
            this.P_MW_GENERAL_RECORD_RELATED_CASE1 = new HashSet<P_MW_GENERAL_RECORD_RELATED_CASE>();
            this.P_MW_GENERAL_RECORD_ACTION = new HashSet<P_MW_GENERAL_RECORD_ACTION>();
        }
    
        public string UUID { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> SUBMISSION_DATE { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string DATE_TIME { get; set; }
        public string VENUE { get; set; }
        public string SECTION_UNIT_REF { get; set; }
        public string CONTACT_ID { get; set; }
        public string LANGUAGE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> REFERRAL_DATE { get; set; }
        public string CASE_TITLE { get; set; }
        public Nullable<System.DateTime> FINAL_REPLY_DATE { get; set; }
        public string SUBJECT_OFFICER { get; set; }
        public string TO_CC { get; set; }
        public string DB_RELATED { get; set; }
        public string NATURE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string RECORD_TYPE { get; set; }
        public string FOLLOW_UP { get; set; }
        public string DESCRIPTION { get; set; }
        public string PROGRESS { get; set; }
        public string SUBMIT_TYPE { get; set; }
        public string STATUS { get; set; }
        public string FORM_STATUS { get; set; }
        public Nullable<System.DateTime> FINAL_REPLY_DUE_DATE { get; set; }
        public Nullable<System.DateTime> INTERIM_REPLY_DATE { get; set; }
        public Nullable<System.DateTime> INTERIM_REPLY_DUE_DATE { get; set; }
        public string CHANNEL { get; set; }
        public string SOURCE { get; set; }
        public string SUBJECT_MATTER { get; set; }
        public string REMARK { get; set; }
        public string ICC_NUMBER { get; set; }
        public string ICC_TYPE { get; set; }
        public string ICC_OFFICER_TYPE { get; set; }
        public string ICC_OFFICER_ID { get; set; }
        public string FLOW_STATUS { get; set; }
        public string ADDRESS_AREA { get; set; }
        public string KEY_WORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_GENERAL_RECORD_RELATED_CASE> P_MW_GENERAL_RECORD_RELATED_CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_GENERAL_RECORD_ADDRESS_INFO> P_MW_GENERAL_RECORD_ADDRESS_INFO { get; set; }
        public virtual P_MW_REFERENCE_NO P_MW_REFERENCE_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_GENERAL_RECORD_LETTER_INFO> P_MW_GENERAL_RECORD_LETTER_INFO { get; set; }
        public virtual P_MW_PERSON_CONTACT P_MW_PERSON_CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_GENERAL_RECORD_RELATED_CASE> P_MW_GENERAL_RECORD_RELATED_CASE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_GENERAL_RECORD_ACTION> P_MW_GENERAL_RECORD_ACTION { get; set; }
    }
}
