//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_RECORD_REFERRED_TO_LSS_EBD
    {
        public string UUID { get; set; }
        public string MW_RECORD_ID { get; set; }
        public Nullable<System.DateTime> DROPPED_WITHDRAWN_DATE { get; set; }
        public Nullable<System.DateTime> SUMMON_DATE { get; set; }
        public Nullable<System.DateTime> HEARING_DATE { get; set; }
        public string TOTAL_FINE { get; set; }
        public string REMARKS { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string HANDLING_UNIT { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
    }
}
