//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_AUDIT_INSPECTION_RECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_AUDIT_INSPECTION_RECORD()
        {
            this.P_MW_ENQUIRY_CHECKLIST = new HashSet<P_MW_ENQUIRY_CHECKLIST>();
        }
    
        public string UUID { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> SELECTION_DATE { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public Nullable<System.DateTime> INSPECTION_TIME_FROM { get; set; }
        public Nullable<System.DateTime> INSPECTION_TIME_TO { get; set; }
        public string REPERSENTATIVE_TYPE { get; set; }
        public string REPERSENTATIVE_NAME { get; set; }
        public string REMARK { get; set; }
        public string STATUS_ID { get; set; }
        public string ACCORDED_SUB_PHOTO { get; set; }
        public string ACCORDED_SUB_PLAN { get; set; }
        public string RESULT { get; set; }
        public string ADDED_BY { get; set; }
        public string MW_RECORD_ITEM_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual P_MW_RECORD_ITEM P_MW_RECORD_ITEM { get; set; }
        public virtual P_S_SYSTEM_VALUE P_S_SYSTEM_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_ENQUIRY_CHECKLIST> P_MW_ENQUIRY_CHECKLIST { get; set; }
    }
}
