//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_RECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_RECORD()
        {
            this.P_MW_APPOINTED_PROFESSIONAL = new HashSet<P_MW_APPOINTED_PROFESSIONAL>();
            this.P_MW_FORM = new HashSet<P_MW_FORM>();
            this.P_MW_FORM_09 = new HashSet<P_MW_FORM_09>();
            this.P_MW_RECORD_ADDRESS_INFO = new HashSet<P_MW_RECORD_ADDRESS_INFO>();
            this.P_MW_RECORD_LETTER_INFO = new HashSet<P_MW_RECORD_LETTER_INFO>();
            this.P_MW_RECORD_AUDIT = new HashSet<P_MW_RECORD_AUDIT>();
            this.P_MW_VERIFICATION = new HashSet<P_MW_VERIFICATION>();
            this.P_MW_RECORD_FORM_CHECKLIST = new HashSet<P_MW_RECORD_FORM_CHECKLIST>();
            this.P_MW_RECORD_ITEM = new HashSet<P_MW_RECORD_ITEM>();
            this.P_MW_RECORD_PSAC = new HashSet<P_MW_RECORD_PSAC>();
            this.P_MW_RECORD_SAC = new HashSet<P_MW_RECORD_SAC>();
            this.P_S_AUDIT_TRAIL = new HashSet<P_S_AUDIT_TRAIL>();
            this.P_MW_SUMMARY_MW_ITEM_CHECKLIST = new HashSet<P_MW_SUMMARY_MW_ITEM_CHECKLIST>();
            this.P_MW_SUBMISSION_PROCESSING_INFO = new HashSet<P_MW_SUBMISSION_PROCESSING_INFO>();
            this.P_MW_VERIFICATION_LOG = new HashSet<P_MW_VERIFICATION_LOG>();
            this.P_MW_RECORD_REFERRED_TO_LSS_EBD = new HashSet<P_MW_RECORD_REFERRED_TO_LSS_EBD>();
            this.P_MW_RECORD_WL_FOLLOW_UP = new HashSet<P_MW_RECORD_WL_FOLLOW_UP>();
        }
    
        public string UUID { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public string LOCATION_ADDRESS_ID { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_SUBMISSION_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public string SIGNBOARD_PERFROMER_ID { get; set; }
        public string S_FORM_TYPE_CODE { get; set; }
        public string PLAN_NO { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string CLASS_CODE { get; set; }
        public string MW_PROGRESS_STATUS_CODE { get; set; }
        public string IS_DATA_ENTRY { get; set; }
        public Nullable<System.DateTime> COMPLETION_SUBMISSION_DATE { get; set; }
        public string LOCATION_OF_MINOR_WORK { get; set; }
        public string FILE_REFERENCE { get; set; }
        public string OWNER_ID { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_ACKNOWLEDGE_DATE { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_CONDINTIONAL_DATE { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_REFUSE_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_ACKNOWLEDGE_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_CONDINTIONAL_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_REFUSE_DATE { get; set; }
        public string SUBMIT_TYPE { get; set; }
        public Nullable<System.DateTime> FIRST_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> LAST_RECEIVED_DATE { get; set; }
        public string VERIFICATION_SPO { get; set; }
        public string SPO_COMPLETE { get; set; }
        public string MW_DSN { get; set; }
        public string PERMIT_NO { get; set; }
        public string RRM_SYN_STATUS { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public string FORM_VERSION { get; set; }
        public string OI_ID { get; set; }
        public string MW05_ITEM36 { get; set; }
        public string NO_OF_PREMISES { get; set; }
        public string FILEREF_FOUR { get; set; }
        public string FILEREF_TWO { get; set; }
        public string AUDIT_RELATED { get; set; }
        public string IMPORT_FORM_TYPE { get; set; }
        public string EFSS_REF_NO { get; set; }
        public string SITE_AUDIT_RELATED { get; set; }
        public string PRE_SITE_AUDIT_RELATED { get; set; }
        public string VERIFICATION_SPO_SMM { get; set; }
        public string SPO_COMPLETE_SMM { get; set; }
        public string SITE_AUDIT_RELATED_MW { get; set; }
        public string SITE_AUDIT_RELATED_SB { get; set; }
    
        public virtual P_MW_ADDRESS P_MW_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_APPOINTED_PROFESSIONAL> P_MW_APPOINTED_PROFESSIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_FORM> P_MW_FORM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_FORM_09> P_MW_FORM_09 { get; set; }
        public virtual P_MW_PERSON_CONTACT P_MW_PERSON_CONTACT { get; set; }
        public virtual P_MW_PERSON_CONTACT P_MW_PERSON_CONTACT1 { get; set; }
        public virtual P_MW_PERSON_CONTACT P_MW_PERSON_CONTACT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_ADDRESS_INFO> P_MW_RECORD_ADDRESS_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_LETTER_INFO> P_MW_RECORD_LETTER_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_AUDIT> P_MW_RECORD_AUDIT { get; set; }
        public virtual P_MW_REFERENCE_NO P_MW_REFERENCE_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_VERIFICATION> P_MW_VERIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_FORM_CHECKLIST> P_MW_RECORD_FORM_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_ITEM> P_MW_RECORD_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_PSAC> P_MW_RECORD_PSAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_SAC> P_MW_RECORD_SAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_AUDIT_TRAIL> P_S_AUDIT_TRAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_SUMMARY_MW_ITEM_CHECKLIST> P_MW_SUMMARY_MW_ITEM_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_SUBMISSION_PROCESSING_INFO> P_MW_SUBMISSION_PROCESSING_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_VERIFICATION_LOG> P_MW_VERIFICATION_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_REFERRED_TO_LSS_EBD> P_MW_RECORD_REFERRED_TO_LSS_EBD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_WL_FOLLOW_UP> P_MW_RECORD_WL_FOLLOW_UP { get; set; }
    }
}
