//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_DIRECT_RETURN
    {
        public string UUID { get; set; }
        public string DSN { get; set; }
        public string FORM_TYPE { get; set; }
        public string CONTRACTOR_REG_NO { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string HANDING_STAFF_1 { get; set; }
        public string HANDING_STAFF_2 { get; set; }
        public string HANDING_STAFF_3 { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LANGUAGE { get; set; }
        public string ADDRESS { get; set; }
    }
}
