//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_VERIFICATION_LOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_VERIFICATION_LOG()
        {
            this.P_MW_VERIFICATION_LOG_ITEM = new HashSet<P_MW_VERIFICATION_LOG_ITEM>();
        }
    
        public string UUID { get; set; }
        public string MW_RECORD_ID { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string REASON { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_VERIFICATION_LOG_ITEM> P_MW_VERIFICATION_LOG_ITEM { get; set; }
    }
}
