//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_RECORD_SAC
    {
        public string UUID { get; set; }
        public string RECORD_ID { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public string CHK_COMMENCEMENT { get; set; }
        public string CHK_COMPLETION { get; set; }
        public string DESK_STUDY_A_CORR_MW_ITEM { get; set; }
        public string DESK_STUDY_B_LAST_INSP_RECORD { get; set; }
        public string SITE_INSAP_A_COMPATIBLE_SITE_INSP { get; set; }
        public string SITE_INSAP_B_ADEQUATE_PRECAUTION { get; set; }
        public string SITE_INSAP_C_NO_OBVIOUS_CONTRAVENTION { get; set; }
        public string SITE_INSAP_D_COMPATIBLE_SITE_INSP { get; set; }
        public string SITE_INSAP_E_NO_MATERIAL_DEVIATION { get; set; }
        public string SITE_INSAP_F_NO_CONTRAVENTION { get; set; }
        public string ACTION_TAKEN_CHK_NA { get; set; }
        public string ACTION_TAKEN_CHK_INFORM { get; set; }
        public string ACTION_TAKEN_CHK_INFORM_PBP { get; set; }
        public string ACTION_TAKEN_CHK_INFORM_PRC { get; set; }
        public Nullable<System.DateTime> ACTION_TAKEN_INFORM_DATE { get; set; }
        public string ACTION_TAKEN_CHK_INFORM_PHONE { get; set; }
        public string ACTION_TAKEN_CHK_INFORM_LETTER { get; set; }
        public string ACTION_TAKEN_CHK_IRR { get; set; }
        public string ACTION_TAKEN_CHK_IRR_PBP { get; set; }
        public string ACTION_TAKEN_CHK_IRR_PRC { get; set; }
        public string ACTION_TAKEN_CHK_IRR_COMPLETE { get; set; }
        public string ACTION_TAKEN_CHK_IRR_PARTLY { get; set; }
        public Nullable<System.DateTime> ACTION_TAKEN_IRR_DATE { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_NA { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_ID { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_NON_ID { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OTHER { get; set; }
        public string IRR_NOT_RECTIFIED_OTHER { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_MW { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_MW_DISCIPLINARY { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_MW_PBP { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_MW_PRC { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_MW_PROSECUTION { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OS_IRR { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OS_DISCIPLINARY { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OS_PBP { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OS_PRC { get; set; }
        public string IRR_NOT_RECTIFIED_CHK_OS_PROSECUTION { get; set; }
        public string INSP_OFFICER_1_NAME { get; set; }
        public Nullable<System.DateTime> INSP_OFFICER_1_DATE { get; set; }
        public string INSP_OFFICER_2_NAME { get; set; }
        public Nullable<System.DateTime> INSP_OFFICER_2_DATE { get; set; }
        public Nullable<System.DateTime> UNIT_HEAD_ENDORSEMENT_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string SYS_PAGE_CODE { get; set; }
        public string HANDLING_UNIT { get; set; }
    
        public virtual P_MW_RECORD P_MW_RECORD { get; set; }
    }
}
