//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_TASK_MANAGEMENT
    {
        public string UUID { get; set; }
        public string ASSINGED_USER_ID { get; set; }
        public Nullable<System.DateTime> ASSINGED_DATE { get; set; }
        public string FUNCTION_ID { get; set; }
        public string REFER_NO { get; set; }
        public string S_STATUS_CODE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    }
}
