//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_COMPLAINT_CHECKLIST_SECTION
    {
        public string UUID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string SECTION_UNIT_DIVISION { get; set; }
        public string OFFICER { get; set; }
        public string RESULT { get; set; }
        public string MW_COMPLAINT_CHECKLIST_ID { get; set; }
        public string DSN { get; set; }
    
        public virtual P_MW_COMPLAINT_CHECKLIST P_MW_COMPLAINT_CHECKLIST { get; set; }
    }
}
