//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_A_LETTER
    {
        public string UUID { get; set; }
        public string MW_ACK_LETTER_ID { get; set; }
        public Nullable<System.DateTime> LETTER_DATE { get; set; }
        public string LANGUAGE { get; set; }
        public string ADDRESS { get; set; }
        public string ITEM_A { get; set; }
        public string ITEM_B { get; set; }
        public string ITEM_C { get; set; }
        public string ITEM_D { get; set; }
        public string ITEM_E { get; set; }
        public string ITEM_F { get; set; }
        public string ITEM_G { get; set; }
        public string ITEM_H { get; set; }
        public string ITEM_I { get; set; }
        public string ITEM_J { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
