//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_ENQUIRY_CHECKLIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_MW_ENQUIRY_CHECKLIST()
        {
            this.P_MW_ENQUIRY_CHECKLIST_ITEM = new HashSet<P_MW_ENQUIRY_CHECKLIST_ITEM>();
        }
    
        public string UUID { get; set; }
        public string ENQUIRY_NO { get; set; }
        public Nullable<System.DateTime> ACTUAL_REPLY_DATE { get; set; }
        public Nullable<System.DateTime> TARGET_REPLY_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string NATURE { get; set; }
        public string STATUS_ID { get; set; }
        public string INSPECTION_RECORD_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual P_MW_AUDIT_INSPECTION_RECORD P_MW_AUDIT_INSPECTION_RECORD { get; set; }
        public virtual P_S_SYSTEM_VALUE P_S_SYSTEM_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_ENQUIRY_CHECKLIST_ITEM> P_MW_ENQUIRY_CHECKLIST_ITEM { get; set; }
    }
}
