//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MW_DECLARARTION
    {
        public string UUID { get; set; }
        public string TYPE_ID { get; set; }
        public string RESULT { get; set; }
        public string APPOINTED_PROFESSIONAL_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        public virtual P_MW_APPOINTED_PROFESSIONAL P_MW_APPOINTED_PROFESSIONAL { get; set; }
        public virtual P_S_SYSTEM_VALUE P_S_SYSTEM_VALUE { get; set; }
    }
}
