//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_RV_BLOCK
    {
        public string UUID { get; set; }
        public int BK_TABLE_ID { get; set; }
        public int BK_BG_TABLE_ID { get; set; }
        public Nullable<int> BK_SL_TABLE_ID { get; set; }
        public Nullable<short> BK_BLDG_NO_NUMERIC { get; set; }
        public string BK_BLDG_NO_ALPHA { get; set; }
        public string BK_BLDG_NO_EXT { get; set; }
        public Nullable<short> BK_BLK_ID_NUMERIC { get; set; }
        public string BK_BLK_ID_ALPHA { get; set; }
        public string BK_BLK_ID_ALPHA_PREC_IND { get; set; }
        public string BK_BLK_DESC { get; set; }
        public string BK_BLK_DESC_CHN { get; set; }
        public string BK_DESC_PREC_IND { get; set; }
        public string BK_BLDG_NAME_ENG_LINE_1 { get; set; }
        public string BK_BLDG_NAME_ENG_LINE_2 { get; set; }
        public string BK_BLDG_NAME_ENG_LINE_3 { get; set; }
        public string BK_BLDG_NAME_CHN_LINE_1 { get; set; }
        public string BK_BLDG_NAME_CHN_LINE_2 { get; set; }
        public string BK_BLDG_NAME_CHN_LINE_3 { get; set; }
        public string BK_FULL_ADDR_ENG { get; set; }
        public string BK_FULL_ADDR2_ENG { get; set; }
        public string BK_FULL_ADDR_CHN { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
