//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_RV_STREET_NAME
    {
        public string UUID { get; set; }
        public int SM_TABLE_ID { get; set; }
        public string SM_NAME_ENG { get; set; }
        public string SM_TYPE_ENG { get; set; }
        public string SM_DIRECTION_ENG { get; set; }
        public string SM_TYPE_ENG_PREC_IND { get; set; }
        public string SM_NAME_CHN { get; set; }
        public string SM_TYPE_CHN { get; set; }
        public string SM_DIRECTION_CHN { get; set; }
        public string SM_TYPE_CHN_PREC_IND { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
