//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_S_MW_ITEM_CHECKLIST_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_S_MW_ITEM_CHECKLIST_ITEM()
        {
            this.P_MW_RECORD_ITEM_CHECKLIST_ITEM = new HashSet<P_MW_RECORD_ITEM_CHECKLIST_ITEM>();
            this.P_S_MW_ITEM_CHECKLIST_ITEM1 = new HashSet<P_S_MW_ITEM_CHECKLIST_ITEM>();
        }
    
        public string UUID { get; set; }
        public string MW_ITEM_NO { get; set; }
        public string CHECKLIST_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string CHECKLIST_TYPE { get; set; }
        public string VALUE_TYPE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string PARENT_ID { get; set; }
        public string ENABLE_BY_VALUE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string SUBMISSION_TYPE { get; set; }
        public Nullable<decimal> MW_ITEM_VERSION { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_ITEM_CHECKLIST_ITEM> P_MW_RECORD_ITEM_CHECKLIST_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_MW_ITEM_CHECKLIST_ITEM> P_S_MW_ITEM_CHECKLIST_ITEM1 { get; set; }
        public virtual P_S_MW_ITEM_CHECKLIST_ITEM P_S_MW_ITEM_CHECKLIST_ITEM2 { get; set; }
    }
}
