//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_S_TO_DETAILS
    {
        public string UUID { get; set; }
        public string TO_POST { get; set; }
        public string TO_POST_ENG { get; set; }
        public string TO_POST_CHI { get; set; }
        public string TO_NAME_ENG { get; set; }
        public string TO_NAME_CHI { get; set; }
        public string TO_CONTACT { get; set; }
        public string PO_POST { get; set; }
        public string PO_POST_ENG { get; set; }
        public string PO_POST_CHI { get; set; }
        public string PO_NAME_ENG { get; set; }
        public string PO_NAME_CHI { get; set; }
        public string PO_CONTACT { get; set; }
        public string SPO_POST { get; set; }
        public string SPO_POST_ENG { get; set; }
        public string SPO_POST_CHI { get; set; }
        public string SPO_NAME_ENG { get; set; }
        public string SPO_NAME_CHI { get; set; }
        public string SPO_CONTACT { get; set; }
        public string IS_ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    }
}
