//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_S_TEMPLATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_S_TEMPLATE()
        {
            this.P_S_AUDIT_TRAIL_VALUE = new HashSet<P_S_AUDIT_TRAIL_VALUE>();
            this.P_S_REFERRAL = new HashSet<P_S_REFERRAL>();
        }
    
        public string UUID { get; set; }
        public string TYPE_ID { get; set; }
        public string CODE { get; set; }
        public string FORMAT { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public string REMARKS { get; set; }
        public string SENDER_NAME { get; set; }
        public string SENDER_ADDRESS { get; set; }
        public string REPLY_NAME { get; set; }
        public string REPLAY_ADDRESS { get; set; }
        public string IS_ACTIVE { get; set; }
        public string LANGUAGE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_AUDIT_TRAIL_VALUE> P_S_AUDIT_TRAIL_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_REFERRAL> P_S_REFERRAL { get; set; }
        public virtual P_S_SYSTEM_VALUE P_S_SYSTEM_VALUE { get; set; }
        public virtual P_S_SYSTEM_VALUE P_S_SYSTEM_VALUE1 { get; set; }
    }
}
