//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_S_SYSTEM_VALUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_S_SYSTEM_VALUE()
        {
            this.P_MOD_BD106_ITEM = new HashSet<P_MOD_BD106_ITEM>();
            this.P_MW_AUDIT_INSPECTION_RECORD = new HashSet<P_MW_AUDIT_INSPECTION_RECORD>();
            this.P_MW_DECLARARTION = new HashSet<P_MW_DECLARARTION>();
            this.P_MW_DSN = new HashSet<P_MW_DSN>();
            this.P_MW_DSN1 = new HashSet<P_MW_DSN>();
            this.P_MW_DW_LETTER_ITEM = new HashSet<P_MW_DW_LETTER_ITEM>();
            this.P_MW_ENQUIRY_CHECKLIST = new HashSet<P_MW_ENQUIRY_CHECKLIST>();
            this.P_MW_RECORD_FORM_CHECKLIST = new HashSet<P_MW_RECORD_FORM_CHECKLIST>();
            this.P_MW_RECORD_FORM_CHECKLIST1 = new HashSet<P_MW_RECORD_FORM_CHECKLIST>();
            this.P_MW_RECORD_ITEM_CHECKLIST = new HashSet<P_MW_RECORD_ITEM_CHECKLIST>();
            this.P_S_TEMPLATE = new HashSet<P_S_TEMPLATE>();
            this.P_S_TEMPLATE1 = new HashSet<P_S_TEMPLATE>();
            this.P_MW_RECORD_AL_FOLLOW_UP_OFFENCES = new HashSet<P_MW_RECORD_AL_FOLLOW_UP_OFFENCES>();
        }
    
        public string UUID { get; set; }
        public string SYSTEM_TYPE_ID { get; set; }
        public string CODE { get; set; }
        public string PARENT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_ACTIVE { get; set; }
        public Nullable<decimal> ORDERING { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string DESCRIPTION_E { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MOD_BD106_ITEM> P_MOD_BD106_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_AUDIT_INSPECTION_RECORD> P_MW_AUDIT_INSPECTION_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_DECLARARTION> P_MW_DECLARARTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_DSN> P_MW_DSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_DSN> P_MW_DSN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_DW_LETTER_ITEM> P_MW_DW_LETTER_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_ENQUIRY_CHECKLIST> P_MW_ENQUIRY_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_FORM_CHECKLIST> P_MW_RECORD_FORM_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_FORM_CHECKLIST> P_MW_RECORD_FORM_CHECKLIST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_ITEM_CHECKLIST> P_MW_RECORD_ITEM_CHECKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_TEMPLATE> P_S_TEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_S_TEMPLATE> P_S_TEMPLATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_MW_RECORD_AL_FOLLOW_UP_OFFENCES> P_MW_RECORD_AL_FOLLOW_UP_OFFENCES { get; set; }
    }
}
