//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_S_MW_ITEM_NATURE
    {
        public string UUID { get; set; }
        public string ITEM_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string NATURE_CODE { get; set; }
        public string NATURE_DESC { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public Nullable<decimal> MW_ITEM_VERSION { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
    }
}
