//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_QUICK_SEARCH
    {
        public string UUID { get; set; }
        public string KEYWORD { get; set; }
        public string RECORD_UUID { get; set; }
        public string RECORD_TYPE { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string APPLICANT_SURNAME { get; set; }
        public string APPLICANT_GIVEN_NAME { get; set; }
        public string APPLICANT_CHINESE_NAME { get; set; }
        public string COMP_NAME { get; set; }
        public string COMP_CHI_NAME { get; set; }
        public string AS_SURNAME { get; set; }
        public string AS_GIVEN_NAME { get; set; }
        public string AS_CHI_NAME { get; set; }
        public string HKID { get; set; }
        public string PASSPORT { get; set; }
        public string UKEY { get; set; }
        public string KEYWORD_TYPE { get; set; }
        public string COMP_IND_TYPE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
    }
}
