//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_RANK()
        {
            this.SYS_POST = new HashSet<SYS_POST>();
        }
    
        public string UUID { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_POST { get; set; }
        public string CREATED_NAME { get; set; }
        public string CREATED_SECTION { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DT { get; set; }
        public string LAST_MODIFIED_POST { get; set; }
        public string LAST_MODIFIED_NAME { get; set; }
        public string LAST_MODIFIED_SECTION { get; set; }
        public Nullable<decimal> RECVERSION { get; set; }
        public string RANK_GROUP { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_POST> SYS_POST { get; set; }
    }
}
