//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWMS2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CRM_INFO
    {
        public string UUID { get; set; }
        public string CODE { get; set; }
        public string CERTIFICATION_NO { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string ROLE_CODE { get; set; }
        public string CLASS_CODE { get; set; }
        public string TYPE_CODE { get; set; }
        public string CHINESE_NAME { get; set; }
        public string GIVEN_NAME { get; set; }
        public string SURNAME { get; set; }
        public string AS_CHINESE_NAME { get; set; }
        public string AS_GIVEN_NAME { get; set; }
        public string AS_SURNAME { get; set; }
        public string ITEM_CODE { get; set; }
        public string FILE_PATH_NONRESTRICTED { get; set; }
        public string FILE_PATH_RESTRICTED { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> COMPANY_EXPIRY_DATE { get; set; }
        public string CN_ADDRESS_LINE1 { get; set; }
        public string CN_ADDRESS_LINE2 { get; set; }
        public string CN_ADDRESS_LINE3 { get; set; }
        public string CN_ADDRESS_LINE4 { get; set; }
        public string CN_ADDRESS_LINE5 { get; set; }
        public string EN_ADDRESS_LINE1 { get; set; }
        public string EN_ADDRESS_LINE2 { get; set; }
        public string EN_ADDRESS_LINE3 { get; set; }
        public string EN_ADDRESS_LINE4 { get; set; }
        public string EN_ADDRESS_LINE5 { get; set; }
        public string COMP_UUID { get; set; }
        public string FAX_NO { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public Nullable<System.DateTime> AS_EXPIRY_DATE { get; set; }
        public string STATUS { get; set; }
        public string COMP_STATUS { get; set; }
        public Nullable<System.DateTime> DISPLAY_COMP_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> DISPLAY_COMP_REMOVAL_DATE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string BS_EMAIL_ADDRESS { get; set; }
    }
}
